// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.24/06       [399366]
Creator        : vince402
Date           : Thu Oct 21 14:09:45 2021
Host           : Linux kunpl 5.4.0-88-generic #99-Ubuntu SMP Thu Sep 23 17:29:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/vince402/Upsilon3S/BDT
Training events: 16581
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "True" [Create PDFs for classifier outputs (signal and background)]
NTrees: "300" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "15%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "4000" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "7.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
BaggedSampleFraction: "4.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "giniindex" [Separation criterion for node splitting]
PruneMethod: "costcomplexity" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "1.000000e+00" [Pruning strength]
PruningValFraction: "3.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
Shrinkage: "1.000000e+00" [Learning rate for BoostType=Grad algorithm]
UseNvars: "3" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "4.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 7
QQMassErr                     QQMassErr                     QQMassErr                     Dimu Mass error               F                                 'F'    [0.034439470619,8.64249420166]
ctau3D                        ctau3D                        ctau3D                        3 dim ctau of the dimuon      F                                 'F'    [-13.2866334915,5.10851335526]
ctau                          ctau                          ctau                          2 dim ctau of the dimuon      F                                 'F'    [-9.55745506287,3.85293912888]
QQVtxProb                     QQVtxProb                     QQVtxProb                     Vtx prob                      F                                 'F'    [0,0.999945223331]
QQdca                         QQdca                         QQdca                         QQdca                         F                                 'F'    [5.96046447754e-07,16.1395244598]
cosAlpha                      cosAlpha                      cosAlpha                      cos alpha for trajectory angleF                                 'F'    [-1,1]
cosAlpha3D                    cosAlpha3D                    cosAlpha3D                    cos alpha for trajectory angle 3DF                                 'F'    [-0.999979019165,0.999999165535]
NSpec 8
pt1                           pt1                           pt1                           Single muon pt1               F                                 'F'    [3.50152468681,14.6436300278]
pt2                           pt2                           pt2                           Single muon pt2               F                                 'F'    [3.50013756752,14.5111913681]
eta1                          eta1                          eta1                          Single muon eta1              F                                 'F'    [-2.39842867851,2.39941501617]
eta2                          eta2                          eta2                          Single muon eta2              F                                 'F'    [-2.39901804924,2.39938855171]
cBin                          cBin                          cBin                          Centrality times 2 bin        F                                 'F'    [1,180]
mass                          mass                          mass                          Dimuon mass                   F                                 'F'    [8.00288677216,11.4964799881]
pt                            pt                            pt                            Dimuon pt                     F                                 'F'    [12.0000104904,14.9999666214]
y                             y                             y                             Dimuon y                      F                                 'F'    [-2.36508369446,2.36175251007]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#include <algorithm>
#include <limits>

#define NN new BDTNode

#ifndef BDTNode__def
#define BDTNode__def

class BDTNode {

public:

   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 

//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 

//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] >= fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}

//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}

#endif

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 7 )
   {
      // the training input variables
      const char* inputVars[] = { "QQMassErr", "ctau3D", "ctau", "QQVtxProb", "QQdca", "cosAlpha", "cosAlpha3D" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[7];
   double fVmax[7];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[7];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
}

void ReadBDT::Initialize()
{
  double inf = std::numeric_limits<double>::infinity();
  double nan = std::numeric_limits<double>::quiet_NaN();
  // itree = 0
  fBoostWeights.push_back(0.831703994809437);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.00768273, 1, 1, 0.723776,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.181961,-99) , 
4, 0.0194282, 1, 0, 0.478719,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.614978);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0964005, 0, 1, 0.656126,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.212319,-99) , 
3, 0.105466, 0, 0, 0.486122,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.531889);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.744773,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451645,-99) , 
2, -0.00489681, 0, 0, 0.649579,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.3183,-99) , 
4, 0.0149547, 1, 0, 0.495038,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.616297);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.750586,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.364362,-99) , 
2, 0.00698992, 1, 0, 0.614622,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.299683,-99) , 
2, -0.00724, 0, 0, 0.511498,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.450071);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0994899, 0, 1, 0.657993,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.348274,-99) , 
3, 0.133707, 0, 0, 0.530951,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.461569);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.658759,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.610695,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.31491,-99) , 
4, 0.00772826, 1, 0, 0.417681,-99) , 
0, 0.110292, 0, 0, 0.477184,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.268394);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.58353, 1, 1, 0.55519,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.360877,-99) , 
4, 0.0149542, 1, 0, 0.463726,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.460378);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.654098,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.340004,-99) , 
1, 0.00602869, 1, 0, 0.538309,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.336292,-99) , 
2, -0.00657441, 0, 0, 0.471274,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.2784);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.620822,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52075,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.371021,-99) , 
4, 0.00736003, 1, 0, 0.426788,-99) , 
0, 0.103532, 0, 0, 0.483935,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.277854);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.682595,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554255,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.403067,-99) , 
5, 0.619095, 0, 0, 0.465444,-99) , 
6, -0.873984, 1, 0, 0.504609,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.268677);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0860462, 0, 1, 0.598221,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.410341,-99) , 
4, 0.0210813, 1, 0, 0.523037,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.32814);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.626512,-99) , 
NN(
0, 
0, 
-1, 0.00352676, 1, -1, 0.388956,-99) , 
0, 0.10421, 0, 0, 0.45114,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.342332);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.667875,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463004,-99) , 
2, 0.00683551, 1, 0, 0.591457,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.37854,-99) , 
2, -0.00647632, 0, 0, 0.518369,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.253871);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.652784,-99) , 
NN(
0, 
0, 
-1, 0.00632476, 1, -1, 0.42879,-99) , 
6, -0.797036, 1, 0, 0.479527,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.362206);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.637144,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430074,-99) , 
2, -0.00593725, 0, 0, 0.563768,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.308621,-99) , 
3, 0.837732, 1, 0, 0.520543,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.208943);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.10744, 0, 1, 0.563055,-99) , 
NN(
0, 
0, 
-1, 0.00795742, 1, -1, 0.405661,-99) , 
0, 0.077469, 0, 0, 0.507621,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.288513);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.662273,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438641,-99) , 
3, 0.739899, 1, 0, 0.578612,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42781,-99) , 
4, 0.0165271, 1, 0, 0.512578,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.281248);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.630085,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.582699,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.404832,-99) , 
6, -0.504575, 1, 0, 0.488049,-99) , 
5, 0.857536, 0, 0, 0.522142,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.311562);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0896388, 1, 1, 0.610715,-99) , 
NN(
0, 
0, 
-1, 0.484352, 1, -1, 0.392579,-99) , 
0, 0.0795199, 0, 0, 0.528346,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.256852);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.705531,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454501,-99) , 
1, -0.00507989, 0, 0, 0.5624,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510918,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.328659,-99) , 
5, 0.682575, 0, 0, 0.443553,-99) , 
5, -0.0722319, 1, 0, 0.498847,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.243071);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.683942,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480666,-99) , 
3, 0.775994, 1, 0, 0.612638,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447139,-99) , 
4, 0.0135785, 1, 0, 0.521805,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.222725);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.610023,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.564026,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430373,-99) , 
5, 0.859036, 0, 0, 0.470145,-99) , 
6, -0.725999, 1, 0, 0.506459,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.290796);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.637781,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.40219,-99) , 
3, 0.836495, 1, 0, 0.58032,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442156,-99) , 
4, 0.0242051, 1, 0, 0.529839,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.257493);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.704122,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492493,-99) , 
1, -0.00278452, 0, 0, 0.581563,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407357,-99) , 
2, 0.00657467, 1, 0, 0.531827,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.226429);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.503563, 1, 1, 0.648379,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517455,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476823,-99) , 
0, 0.0904955, 0, 0, 0.49709,-99) , 
3, 0.276666, 0, 0, 0.567795,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.35933);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.748034, 1, 1, 0.618067,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.358084,-99) , 
1, 0.00584613, 1, 0, 0.536098,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.203132);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.00844243, 1, 1, 0.560236,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.364044,-99) , 
3, 0.843993, 1, 0, 0.529647,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.23722);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0765986, 0, 1, 0.640442,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545414,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441693,-99) , 
6, -0.54008, 1, 0, 0.480426,-99) , 
4, 0.00897256, 1, 0, 0.536423,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.216982);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.645755,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471187,-99) , 
1, 0.000785937, 1, 0, 0.52097,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.397406,-99) , 
1, -0.00398251, 0, 0, 0.475995,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.235328);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.00339235, 1, 1, 0.5761,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.402645,-99) , 
2, -0.00705922, 0, 0, 0.517646,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.163712);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.00301331, 1, 1, 0.573631,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468134,-99) , 
2, -0.00560196, 0, 0, 0.534662,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.255905);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.610011,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.616438,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423219,-99) , 
0, 0.120041, 0, 0, 0.462811,-99) , 
4, 0.00538962, 1, 0, 0.494961,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.213522);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.609951,-99) , 
NN(
0, 
0, 
-1, 0.652024, 0, -1, 0.436729,-99) , 
6, -0.73655, 1, 0, 0.482748,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.343635);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.650295,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.605241,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.390759,-99) , 
5, 0.55927, 0, 0, 0.495702,-99) , 
5, -0.796051, 1, 0, 0.542557,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.18865);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.195701, 0, 1, 0.564543,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426985,-99) , 
2, 0.00679393, 1, 0, 0.525125,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.199568);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.611407,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497902,-99) , 
4, 0.00804035, 1, 0, 0.544677,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55236,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.386579,-99) , 
6, -0.708032, 1, 0, 0.437698,-99) , 
0, 0.0901198, 1, 0, 0.491351,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.233204);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.659012,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.578339,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437639,-99) , 
4, 0.00678927, 1, 0, 0.478304,-99) , 
5, 0.955011, 0, 0, 0.50883,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.335763);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.126717, 1, 1, 0.627299,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.58922,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.38973,-99) , 
6, 0.126447, 1, 0, 0.476651,-99) , 
0, 0.0787347, 0, 0, 0.571922,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.225377);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.646316,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533459,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.398407,-99) , 
1, -0.00632841, 0, 0, 0.478833,-99) , 
6, 0.819493, 0, 0, 0.515719,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.234062);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.614155,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468565,-99) , 
6, 0.826897, 1, 0, 0.531479,-99) , 
NN(
0, 
0, 
-1, 0.686679, 1, -1, 0.407331,-99) , 
5, 0.27968, 0, 0, 0.455288,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.325898);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.61438,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423305,-99) , 
2, 0.0047753, 1, 0, 0.546241,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.350376,-99) , 
3, 0.688585, 1, 0, 0.492357,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.232278);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.740885,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477848,-99) , 
2, 0.000480268, 1, 0, 0.543689,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.408875,-99) , 
2, -0.00605763, 0, 0, 0.493446,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.218831);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.677933,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55352,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448929,-99) , 
3, 0.246314, 0, 0, 0.494908,-99) , 
6, 0.834527, 0, 0, 0.531831,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.283885);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.640611,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568792,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.400142,-99) , 
6, 0.652025, 0, 0, 0.471864,-99) , 
6, -0.783009, 1, 0, 0.513682,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.229007);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.668757,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479764,-99) , 
1, -0.000606955, 0, 0, 0.536392,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.38063,-99) , 
2, 0.00679497, 1, 0, 0.489836,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.31659);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.630157,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.418751,-99) , 
3, 0.605307, 1, 0, 0.559887,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.395359,-99) , 
1, -0.00597885, 0, 0, 0.511529,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.183343);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.685178, 1, 1, 0.592397,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51092,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426053,-99) , 
5, -0.00524766, 0, 0, 0.46739,-99) , 
4, 0.0119632, 1, 0, 0.52299,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.223142);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.904024, 0, 1, 0.58068,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429511,-99) , 
3, 0.837745, 1, 0, 0.556138,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.267613);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.910635, 0, 1, 0.573503,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5384,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.298528,-99) , 
5, 0.566055, 0, 0, 0.436229,-99) , 
5, -0.546613, 1, 0, 0.489892,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.268485);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.619078,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448291,-99) , 
1, -0.00541918, 0, 0, 0.541654,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.389077,-99) , 
1, 0.00610563, 1, 0, 0.499452,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.194673);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562085,-99) , 
NN(
0, 
0, 
-1, 0.287408, 1, -1, 0.428816,-99) , 
0, 0.10783, 0, 0, 0.459609,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.248949);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.910525, 0, 1, 0.587626,-99) , 
NN(
0, 
0, 
-1, 0.470495, 0, -1, 0.41184,-99) , 
6, -0.563593, 1, 0, 0.469531,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.17682);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.629527,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493776,-99) , 
2, -0.00676626, 0, 0, 0.563426,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449961,-99) , 
2, 0.00617814, 1, 0, 0.524504,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.196661);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.588102,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468855,-99) , 
4, 0.0225072, 1, 0, 0.536874,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.401914,-99) , 
0, 0.0651217, 0, 0, 0.512807,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.283596);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.283159, 1, 1, 0.605507,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553035,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.38657,-99) , 
5, 0.328168, 0, 0, 0.440244,-99) , 
0, 0.0893983, 1, 0, 0.525588,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.253557);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.597791,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447298,-99) , 
3, 0.631297, 1, 0, 0.556278,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.390338,-99) , 
0, 0.0664108, 0, 0, 0.527434,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.242202);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.616239,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492595,-99) , 
2, 0.00317915, 1, 0, 0.562339,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559485,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.350422,-99) , 
0, 0.106642, 0, 0, 0.457995,-99) , 
0, 0.090905, 1, 0, 0.511259,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.145343);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.10429, 0, 1, 0.53868,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.382547,-99) , 
5, 0.953512, 1, 0, 0.512828,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.227763);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.575807,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.570268,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.413975,-99) , 
5, -0.90876, 1, 0, 0.453757,-99) , 
5, 0.891527, 0, 0, 0.480906,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.256144);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580006,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442111,-99) , 
1, -0.00604885, 0, 0, 0.520167,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.366363,-99) , 
1, 0.00610563, 1, 0, 0.47136,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.250425);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.627022,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545107,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.379437,-99) , 
5, -0.084229, 1, 0, 0.482835,-99) , 
6, 0.760069, 0, 0, 0.523291,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.266787);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.00296126, 1, 1, 0.595396,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550877,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.379181,-99) , 
6, -0.841694, 1, 0, 0.448079,-99) , 
2, -0.00280289, 0, 0, 0.525625,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.172319);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.594998,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509377,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.400396,-99) , 
5, -0.315171, 1, 0, 0.455846,-99) , 
6, 0.881443, 0, 0, 0.481241,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.174968);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.539366, 0, 1, 0.554142,-99) , 
NN(
0, 
0, 
-1, 0.0013664, 1, -1, 0.426647,-99) , 
0, 0.0940046, 1, 0, 0.500895,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.23164);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580168,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43343,-99) , 
2, -0.00732038, 0, 0, 0.513717,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.394793,-99) , 
5, 0.87853, 1, 0, 0.483327,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.218519);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.567499,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.567303,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.409988,-99) , 
0, 0.104336, 0, 0, 0.467174,-99) , 
0, 0.0764977, 1, 0, 0.497728,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.219803);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.647451,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477547,-99) , 
2, -0.00666106, 0, 0, 0.536043,-99) , 
NN(
0, 
0, 
-1, 0.765156, 0, -1, 0.409754,-99) , 
6, 0.112744, 1, 0, 0.472924,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.187144);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.666124,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499701,-99) , 
0, 0.0787115, 0, 0, 0.561342,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526722,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.398388,-99) , 
3, 0.323896, 0, 0, 0.449681,-99) , 
0, 0.0915484, 1, 0, 0.508395,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.330413);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.928018, 0, 1, 0.634819,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.600583,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.390595,-99) , 
4, 0.00806834, 1, 0, 0.451282,-99) , 
6, -0.589104, 1, 0, 0.510394,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.204444);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.602615,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460681,-99) , 
1, 0.00219071, 1, 0, 0.546147,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438169,-99) , 
3, 0.56507, 1, 0, 0.512017,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.261416);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.661708,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454762,-99) , 
6, 0.929096, 1, 0, 0.557216,-99) , 
NN(
0, 
0, 
-1, 0.231925, 1, -1, 0.412911,-99) , 
6, 0.621528, 0, 0, 0.460407,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.212231);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0886697, 1, 1, 0.59088,-99) , 
NN(
0, 
0, 
-1, -0.476632, 1, -1, 0.436977,-99) , 
6, 0.207627, 0, 0, 0.504371,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.156498);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0736376, 1, 1, 0.601342,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482178,-99) , 
4, 0.0149539, 1, 0, 0.536166,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.224673);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0963998, 0, 1, 0.601991,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450561,-99) , 
3, 0.127211, 0, 0, 0.537352,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.206086);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.694528,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.604259,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467862,-99) , 
0, 0.116107, 0, 0, 0.497041,-99) , 
4, 0.00403578, 1, 0, 0.53132,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.266301);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.950916, 1, 1, 0.614354,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558458,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.386065,-99) , 
2, -0.00555747, 1, 0, 0.474907,-99) , 
5, 0.627593, 0, 0, 0.516399,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.279516);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.646818,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.647617,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442796,-99) , 
5, 0.904024, 0, 0, 0.496438,-99) , 
6, -0.681062, 1, 0, 0.536667,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.298786);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.659224,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468713,-99) , 
3, 0.227931, 1, 0, 0.558022,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.35359,-99) , 
0, 0.11569, 1, 0, 0.506658,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.205825);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.635869,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486142,-99) , 
1, 0.00580637, 1, 0, 0.575958,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468571,-99) , 
5, -0.902524, 0, 0, 0.548804,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.255456);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.642941,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468936,-99) , 
3, 0.650802, 1, 0, 0.581694,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434861,-99) , 
2, -0.00705922, 0, 0, 0.530766,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.150332);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.677562, 1, 1, 0.581823,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487897,-99) , 
4, 0.0242516, 1, 0, 0.543646,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.220575);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.192326, 0, 1, 0.575912,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549309,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.38275,-99) , 
4, 0.00435921, 1, 0, 0.470763,-99) , 
4, 0.00966743, 0, 0, 0.532996,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.224886);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.633492,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49384,-99) , 
0, 0.0836857, 0, 0, 0.573367,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.415667,-99) , 
3, 0.837731, 1, 0, 0.546594,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.247227);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0886229, 1, 1, 0.598504,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436631,-99) , 
0, 0.0761675, 0, 0, 0.547295,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.2043);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.632791,-99) , 
NN(
0, 
0, 
-1, 0.428958, 1, -1, 0.439744,-99) , 
4, 0.00321714, 1, 0, 0.472198,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.233255);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.623984,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550347,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.391653,-99) , 
5, -0.863034, 0, 0, 0.498041,-99) , 
0, 0.103843, 0, 0, 0.528255,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.206576);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.639155,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477307,-99) , 
0, 0.0761166, 0, 0, 0.54725,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500874,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.342328,-99) , 
1, -0.00199977, 0, 0, 0.427416,-99) , 
0, 0.0913017, 1, 0, 0.493643,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.219843);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.608532,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475887,-99) , 
5, 0.388153, 0, 0, 0.525367,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.320136,-99) , 
3, 0.854728, 1, 0, 0.48858,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.234132);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.715587,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546491,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.427025,-99) , 
1, -0.00276799, 0, 0, 0.506575,-99) , 
5, -0.945014, 1, 0, 0.542453,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.232916);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.603684,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493745,-99) , 
4, 0.0201703, 1, 0, 0.553855,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.325932,-99) , 
6, 0.929018, 1, 0, 0.508286,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.246226);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.695115,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486453,-99) , 
1, -0.00554973, 0, 0, 0.56533,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53298,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.350211,-99) , 
5, 0.819827, 0, 0, 0.441338,-99) , 
5, -0.0617346, 1, 0, 0.500996,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.201125);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.00196763, 0, 1, 0.565245,-99) , 
NN(
0, 
0, 
-1, 0.82855, 0, -1, 0.421076,-99) , 
6, 0.423568, 1, 0, 0.501008,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.196295);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.881164, 0, 1, 0.590047,-99) , 
NN(
0, 
0, 
-1, 0.00572557, 1, -1, 0.442447,-99) , 
5, -0.715071, 1, 0, 0.497395,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.210159);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.596033,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.601001,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442655,-99) , 
6, -0.811536, 1, 0, 0.482421,-99) , 
0, 0.0700474, 1, 0, 0.507784,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.191998);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.00438505, 0, 1, 0.568506,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.433872,-99) , 
3, 0.842493, 1, 0, 0.548016,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.177965);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.646917,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477488,-99) , 
5, -0.928018, 0, 0, 0.569256,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509179,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.384843,-99) , 
2, 0.00219352, 0, 0, 0.472303,-99) , 
6, -0.149716, 1, 0, 0.51678,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.248692);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.75397,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49477,-99) , 
0, 0.0871929, 0, 0, 0.608731,-99) , 
NN(
0, 
0, 
-1, 0.293177, 1, -1, 0.42968,-99) , 
3, 0.336148, 0, 0, 0.500765,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.251586);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.756244,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525094,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.392047,-99) , 
0, 0.0796205, 0, 0, 0.472184,-99) , 
4, 0.0040353, 1, 0, 0.516401,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.227908);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.251688, 1, 1, 0.598508,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501868,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.349904,-99) , 
5, 0.729568, 1, 0, 0.443226,-99) , 
0, 0.0909738, 1, 0, 0.528333,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.178204);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.624756,-99) , 
NN(
0, 
0, 
-1, 0.000316563, 1, -1, 0.455443,-99) , 
0, 0.07233, 1, 0, 0.495018,-99)    );
  // itree = 100
  fBoostWeights.push_back(0.276886);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.195702, 0, 1, 0.587951,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.609663,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.398254,-99) , 
6, -0.682022, 1, 0, 0.452217,-99) , 
0, 0.083056, 1, 0, 0.504987,-99)    );
  // itree = 101
  fBoostWeights.push_back(0.245287);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.671992,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550786,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444312,-99) , 
2, -0.00264676, 0, 0, 0.504871,-99) , 
4, 0.00806965, 1, 0, 0.552326,-99)    );
  // itree = 102
  fBoostWeights.push_back(0.262955);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.624278,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45734,-99) , 
3, 0.280039, 0, 0, 0.528882,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.381508,-99) , 
2, 0.00511795, 1, 0, 0.474103,-99)    );
  // itree = 103
  fBoostWeights.push_back(0.262107);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.718875,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465629,-99) , 
6, -0.886303, 0, 0, 0.601012,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56469,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.427722,-99) , 
6, 0.788629, 0, 0, 0.490002,-99) , 
5, -0.654586, 1, 0, 0.531003,-99)    );
  // itree = 104
  fBoostWeights.push_back(0.208188);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.627344,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476686,-99) , 
3, 0.333393, 1, 0, 0.566825,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536614,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417585,-99) , 
0, 0.106767, 0, 0, 0.47581,-99) , 
0, 0.0887755, 1, 0, 0.524976,-99)    );
  // itree = 105
  fBoostWeights.push_back(0.2456);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.669561,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463751,-99) , 
1, 0.00474148, 1, 0, 0.568685,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442375,-99) , 
2, -0.00657441, 0, 0, 0.521534,-99)    );
  // itree = 106
  fBoostWeights.push_back(0.191022);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.000658845, 0, 1, 0.579452,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459524,-99) , 
1, 0.00621027, 1, 0, 0.543606,-99)    );
  // itree = 107
  fBoostWeights.push_back(0.177945);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.656678,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468255,-99) , 
5, -0.934516, 1, 0, 0.505267,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.399321,-99) , 
0, 0.065492, 0, 0, 0.488738,-99)    );
  // itree = 108
  fBoostWeights.push_back(0.265351);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.634171,-99) , 
NN(
0, 
0, 
-1, 0.402928, 0, -1, 0.439577,-99) , 
3, 0.222872, 1, 0, 0.527249,-99)    );
  // itree = 109
  fBoostWeights.push_back(0.218887);
  fForest.push_back( 
NN(
0, 
0, 
-1, -0.00485716, 0, 1, 0.577543,-99)    );
  // itree = 110
  fBoostWeights.push_back(0.172391);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.834121, 1, 1, 0.576083,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520262,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.404241,-99) , 
5, -0.780328, 1, 0, 0.472635,-99) , 
5, 0.327668, 0, 0, 0.51432,-99)    );
  // itree = 111
  fBoostWeights.push_back(0.204136);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.641269,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543589,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.419816,-99) , 
0, 0.0711076, 0, 0, 0.511563,-99) , 
3, 0.651042, 0, 0, 0.539995,-99)    );
  // itree = 112
  fBoostWeights.push_back(0.152019);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55281,-99) , 
NN(
0, 
0, 
-1, 0.1328, 1, -1, 0.445464,-99) , 
4, 0.00808496, 1, 0, 0.473807,-99)    );
  // itree = 113
  fBoostWeights.push_back(0.236203);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.618154,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539679,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.3965,-99) , 
6, -0.581011, 1, 0, 0.477234,-99) , 
6, 0.525608, 0, 0, 0.521906,-99)    );
  // itree = 114
  fBoostWeights.push_back(0.226823);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.596014,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452076,-99) , 
1, 0.00633793, 1, 0, 0.520129,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.402871,-99) , 
1, -0.0051672, 0, 0, 0.477397,-99)    );
  // itree = 115
  fBoostWeights.push_back(0.194893);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.592804,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535896,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.427358,-99) , 
0, 0.0965131, 0, 0, 0.46919,-99) , 
4, 0.00897291, 1, 0, 0.507648,-99)    );
  // itree = 116
  fBoostWeights.push_back(0.178758);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.643742,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489863,-99) , 
0, 0.0751597, 0, 0, 0.552018,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521707,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.411453,-99) , 
3, 0.317899, 0, 0, 0.453912,-99) , 
0, 0.0912866, 1, 0, 0.506188,-99)    );
  // itree = 117
  fBoostWeights.push_back(0.268894);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.627095,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457836,-99) , 
0, 0.0736439, 0, 0, 0.542284,-99) , 
NN(
0, 
0, 
-1, 0.495342, 1, -1, 0.389244,-99) , 
0, 0.0993988, 1, 0, 0.481977,-99)    );
  // itree = 118
  fBoostWeights.push_back(0.226399);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.00279172, 1, 1, 0.588805,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431774,-99) , 
1, -0.0040408, 0, 0, 0.522831,-99)    );
  // itree = 119
  fBoostWeights.push_back(0.20775);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.603016,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.610514,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446539,-99) , 
0, 0.105605, 0, 0, 0.48552,-99) , 
5, 0.916521, 0, 0, 0.507173,-99)    );
  // itree = 120
  fBoostWeights.push_back(0.232888);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.694096,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537791,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.411025,-99) , 
4, 0.0179445, 0, 0, 0.480188,-99) , 
0, 0.0680868, 1, 0, 0.51454,-99)    );
  // itree = 121
  fBoostWeights.push_back(0.114595);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.00294481, 0, 1, 0.549897,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477674,-99) , 
2, 0.00529639, 1, 0, 0.52616,-99)    );
  // itree = 122
  fBoostWeights.push_back(0.185139);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.643642,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491942,-99) , 
6, -0.154799, 1, 0, 0.559587,-99) , 
NN(
0, 
0, 
-1, 0.108082, 0, -1, 0.437318,-99) , 
0, 0.0909449, 1, 0, 0.501358,-99)    );
  // itree = 123
  fBoostWeights.push_back(0.203681);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.617401,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508599,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.369463,-99) , 
2, 0.00466908, 1, 0, 0.453331,-99) , 
0, 0.0724076, 1, 0, 0.494641,-99)    );
  // itree = 124
  fBoostWeights.push_back(0.241302);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0831779, 1, 1, 0.568709,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.569159,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.390958,-99) , 
6, -0.841632, 1, 0, 0.446524,-99) , 
5, 0.254187, 0, 0, 0.495884,-99)    );
  // itree = 125
  fBoostWeights.push_back(0.291437);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.671837,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472221,-99) , 
1, 0.00105114, 1, 0, 0.573858,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.395743,-99) , 
3, 0.137706, 0, 0, 0.48968,-99)    );
  // itree = 126
  fBoostWeights.push_back(0.216484);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.000134253, 0, 1, 0.585422,-99) , 
NN(
0, 
0, 
-1, 0.729343, 1, -1, 0.428144,-99) , 
0, 0.0814883, 1, 0, 0.484369,-99)    );
  // itree = 127
  fBoostWeights.push_back(0.19984);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0970906, 0, 1, 0.589382,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456713,-99) , 
2, -0.00493733, 0, 0, 0.536161,-99)    );
  // itree = 128
  fBoostWeights.push_back(0.166944);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.00140507, 1, 1, 0.565822,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452514,-99) , 
2, -0.00728087, 0, 0, 0.525776,-99)    );
  // itree = 129
  fBoostWeights.push_back(0.175967);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.631251,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464344,-99) , 
2, -0.00684058, 0, 0, 0.539641,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468258,-99) , 
2, 0.00511795, 1, 0, 0.514958,-99)    );
  // itree = 130
  fBoostWeights.push_back(0.182553);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.596024,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554627,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447412,-99) , 
0, 0.0890702, 0, 0, 0.519488,-99) , 
0, 0.0717819, 1, 0, 0.539269,-99)    );
  // itree = 131
  fBoostWeights.push_back(0.166027);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.62858,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536014,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441164,-99) , 
6, 0.0757095, 0, 0, 0.495202,-99) , 
6, -0.881012, 1, 0, 0.516454,-99)    );
  // itree = 132
  fBoostWeights.push_back(0.23646);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.673384,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470198,-99) , 
6, -0.884041, 0, 0, 0.588335,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.569502,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439344,-99) , 
6, 0.838812, 0, 0, 0.487513,-99) , 
5, -0.654086, 1, 0, 0.52781,-99)    );
  // itree = 133
  fBoostWeights.push_back(0.143076);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.578387,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488236,-99) , 
3, 0.192458, 0, 0, 0.527791,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.392536,-99) , 
3, 0.846264, 1, 0, 0.507594,-99)    );
  // itree = 134
  fBoostWeights.push_back(0.201824);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.671137,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455183,-99) , 
6, 0.119234, 0, 0, 0.541747,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454991,-99) , 
4, 0.0210813, 1, 0, 0.500699,-99)    );
  // itree = 135
  fBoostWeights.push_back(0.209987);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.117385, 1, 1, 0.603417,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531791,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.366686,-99) , 
0, 0.0853402, 1, 0, 0.484718,-99) , 
0, 0.0968291, 0, 0, 0.522823,-99)    );
  // itree = 136
  fBoostWeights.push_back(0.205538);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.271913, 1, 1, 0.585983,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547221,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.433659,-99) , 
5, -0.452136, 1, 0, 0.477052,-99) , 
0, 0.0849203, 0, 0, 0.533031,-99)    );
  // itree = 137
  fBoostWeights.push_back(0.224472);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.927707, 0, 1, 0.571848,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535583,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.383583,-99) , 
0, 0.0823965, 1, 0, 0.443564,-99) , 
5, -0.573606, 1, 0, 0.4945,-99)    );
  // itree = 138
  fBoostWeights.push_back(0.282559);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.597417,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.427976,-99) , 
5, 0.736066, 1, 0, 0.541936,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.350727,-99) , 
0, 0.0654617, 0, 0, 0.508685,-99)    );
  // itree = 139
  fBoostWeights.push_back(0.192523);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.601722,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469128,-99) , 
1, 0.00442892, 1, 0, 0.549846,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443517,-99) , 
0, 0.0750756, 0, 0, 0.515406,-99)    );
  // itree = 140
  fBoostWeights.push_back(0.162569);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.648289,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483504,-99) , 
5, 0.276684, 1, 0, 0.529169,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434302,-99) , 
1, -0.00405932, 0, 0, 0.493388,-99)    );
  // itree = 141
  fBoostWeights.push_back(0.202288);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.586277,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507586,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.395485,-99) , 
5, 0.549613, 0, 0, 0.437552,-99) , 
0, 0.0689536, 1, 0, 0.46712,-99)    );
  // itree = 142
  fBoostWeights.push_back(0.221939);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.00175183, 0, 1, 0.569232,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.389975,-99) , 
0, 0.113049, 1, 0, 0.528035,-99)    );
  // itree = 143
  fBoostWeights.push_back(0.221093);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568276,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457654,-99) , 
0, 0.0675042, 0, 0, 0.543211,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.370136,-99) , 
5, -0.932517, 0, 0, 0.502392,-99)    );
  // itree = 144
  fBoostWeights.push_back(0.239053);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.595838,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417704,-99) , 
2, 0.00741716, 1, 0, 0.511739,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423427,-99) , 
1, -0.00405932, 0, 0, 0.478195,-99)    );
  // itree = 145
  fBoostWeights.push_back(0.16898);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.596029,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480983,-99) , 
5, -0.863034, 0, 0, 0.561961,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457976,-99) , 
4, 0.0239281, 1, 0, 0.518084,-99)    );
  // itree = 146
  fBoostWeights.push_back(0.201826);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.587045,-99) , 
NN(
0, 
0, 
-1, 0.0893983, 1, -1, 0.432224,-99) , 
6, -0.843974, 1, 0, 0.462834,-99)    );
  // itree = 147
  fBoostWeights.push_back(0.154285);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.624045,-99) , 
NN(
0, 
0, 
-1, 0.42377, 1, -1, 0.468931,-99) , 
5, 0.833542, 0, 0, 0.508655,-99)    );
  // itree = 148
  fBoostWeights.push_back(0.167118);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.565114,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476213,-99) , 
6, 0.939602, 1, 0, 0.538795,-99) , 
NN(
0, 
0, 
-1, -0.810704, 1, -1, 0.432461,-99) , 
6, -0.40461, 0, 0, 0.491476,-99)    );
  // itree = 149
  fBoostWeights.push_back(0.282344);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0910088, 1, 1, 0.647039,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545621,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.399249,-99) , 
6, -0.515463, 1, 0, 0.502097,-99) , 
5, 0.116721, 0, 0, 0.565986,-99)    );
  // itree = 150
  fBoostWeights.push_back(0.257869);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.633983,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551627,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.384588,-99) , 
3, 0.166123, 1, 0, 0.488285,-99) , 
4, 0.0080687, 1, 0, 0.526493,-99)    );
  // itree = 151
  fBoostWeights.push_back(0.231755);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.619112,-99) , 
NN(
0, 
0, 
-1, 0.00281303, 1, -1, 0.425366,-99) , 
0, 0.118331, 0, 0, 0.457546,-99)    );
  // itree = 152
  fBoostWeights.push_back(0.199591);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.699233,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492818,-99) , 
4, 0.0061826, 0, 0, 0.57649,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544358,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430771,-99) , 
4, 0.0173226, 1, 0, 0.466226,-99) , 
3, 0.29566, 0, 0, 0.509917,-99)    );
  // itree = 153
  fBoostWeights.push_back(0.157128);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.608408,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486662,-99) , 
3, 0.211171, 0, 0, 0.526366,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4146,-99) , 
3, 0.605806, 1, 0, 0.49495,-99)    );
  // itree = 154
  fBoostWeights.push_back(0.215161);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.602906,-99) , 
NN(
0, 
0, 
-1, 0.837782, 1, -1, 0.446406,-99) , 
3, 0.222679, 1, 0, 0.518288,-99)    );
  // itree = 155
  fBoostWeights.push_back(0.170465);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.00535043, 0, 1, 0.566147,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454462,-99) , 
6, 0.82647, 1, 0, 0.535985,-99)    );
  // itree = 156
  fBoostWeights.push_back(0.212804);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.151225, 1, 1, 0.655849,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514773,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445095,-99) , 
3, 0.126679, 1, 0, 0.491602,-99) , 
3, 0.335015, 0, 0, 0.552429,-99)    );
  // itree = 157
  fBoostWeights.push_back(0.220099);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.899527, 0, 1, 0.637279,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533266,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.405293,-99) , 
3, 0.636795, 1, 0, 0.498852,-99) , 
6, 0.623061, 0, 0, 0.543433,-99)    );
  // itree = 158
  fBoostWeights.push_back(0.238975);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.618601,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444824,-99) , 
0, 0.0816943, 0, 0, 0.543821,-99) , 
NN(
0, 
0, 
-1, 0.81245, 0, -1, 0.422043,-99) , 
5, -0.0327418, 1, 0, 0.481988,-99)    );
  // itree = 159
  fBoostWeights.push_back(0.18276);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0133593, 0, 1, 0.558388,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42584,-99) , 
3, 0.113372, 0, 0, 0.503635,-99)    );
  // itree = 160
  fBoostWeights.push_back(0.16461);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.630286,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491674,-99) , 
0, 0.0714149, 1, 0, 0.524197,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.391933,-99) , 
5, -0.887528, 0, 0, 0.484071,-99)    );
  // itree = 161
  fBoostWeights.push_back(0.209834);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.64261,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559336,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436914,-99) , 
6, -0.257433, 1, 0, 0.503806,-99) , 
5, 0.934016, 0, 0, 0.526518,-99)    );
  // itree = 162
  fBoostWeights.push_back(0.195257);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.601027,-99) , 
NN(
0, 
0, 
-1, 0.155203, 0, -1, 0.436937,-99) , 
6, 0.901492, 0, 0, 0.463834,-99)    );
  // itree = 163
  fBoostWeights.push_back(0.140116);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.582954,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483383,-99) , 
5, 0.938018, 1, 0, 0.542594,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501868,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.364723,-99) , 
5, -0.578106, 1, 0, 0.457014,-99) , 
6, 0.352123, 0, 0, 0.49245,-99)    );
  // itree = 164
  fBoostWeights.push_back(0.184295);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.648977,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496725,-99) , 
0, 0.0860487, 0, 0, 0.573187,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524233,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.415709,-99) , 
0, 0.0892173, 1, 0, 0.473474,-99) , 
1, -0.00157613, 0, 0, 0.527697,-99)    );
  // itree = 165
  fBoostWeights.push_back(0.206484);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.628372,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.571017,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463593,-99) , 
4, 0.00897387, 1, 0, 0.502165,-99) , 
5, 0.745064, 0, 0, 0.540849,-99)    );
  // itree = 166
  fBoostWeights.push_back(0.229901);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.745144,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493316,-99) , 
2, 0.00704416, 1, 0, 0.579697,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540383,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.383463,-99) , 
0, 0.0815941, 0, 0, 0.468211,-99) , 
5, 0.076231, 0, 0, 0.519123,-99)    );
  // itree = 167
  fBoostWeights.push_back(0.225212);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.619099,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545911,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.381567,-99) , 
2, -0.00331338, 0, 0, 0.490127,-99) , 
5, -0.947013, 1, 0, 0.514605,-99)    );
  // itree = 168
  fBoostWeights.push_back(0.167912);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.644306,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498931,-99) , 
2, 0.000911179, 1, 0, 0.538006,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.410533,-99) , 
2, -0.00619519, 0, 0, 0.486623,-99)    );
  // itree = 169
  fBoostWeights.push_back(0.155903);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.614652,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524506,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442003,-99) , 
0, 0.0886444, 1, 0, 0.503797,-99) , 
0, 0.102299, 0, 0, 0.534363,-99)    );
  // itree = 170
  fBoostWeights.push_back(0.211964);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.585609,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469775,-99) , 
0, 0.113489, 1, 0, 0.555919,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.408228,-99) , 
0, 0.0655084, 0, 0, 0.528968,-99)    );
  // itree = 171
  fBoostWeights.push_back(0.198268);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.602274,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577297,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44568,-99) , 
6, 0.713582, 0, 0, 0.481064,-99) , 
3, 0.574075, 0, 0, 0.509623,-99)    );
  // itree = 172
  fBoostWeights.push_back(0.226362);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.677597,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457819,-99) , 
2, 0.00474529, 1, 0, 0.538946,-99) , 
NN(
0, 
0, 
-1, 0.413752, 1, -1, 0.436982,-99) , 
5, -0.669583, 0, 0, 0.496897,-99)    );
  // itree = 173
  fBoostWeights.push_back(0.154342);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.605944, 1, 1, 0.573145,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470103,-99) , 
3, 0.102219, 0, 0, 0.529675,-99)    );
  // itree = 174
  fBoostWeights.push_back(0.205601);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0966814, 0, 1, 0.568945,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.412587,-99) , 
0, 0.12053, 1, 0, 0.535415,-99)    );
  // itree = 175
  fBoostWeights.push_back(0.204988);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.640621,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.570406,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462135,-99) , 
3, 0.246421, 0, 0, 0.50662,-99) , 
0, 0.0701608, 1, 0, 0.538786,-99)    );
  // itree = 176
  fBoostWeights.push_back(0.152248);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.700791,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484847,-99) , 
6, 0.0242192, 1, 0, 0.534722,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453638,-99) , 
1, -0.00575852, 0, 0, 0.507841,-99)    );
  // itree = 177
  fBoostWeights.push_back(0.231148);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0747904, 0, 1, 0.600527,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466136,-99) , 
3, 0.553581, 1, 0, 0.562796,-99)    );
  // itree = 178
  fBoostWeights.push_back(0.285321);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.119362, 0, 1, 0.664426,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511237,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.381149,-99) , 
0, 0.0741425, 0, 0, 0.442993,-99) , 
0, 0.0958486, 0, 0, 0.518124,-99)    );
  // itree = 179
  fBoostWeights.push_back(0.237453);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.629041,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472558,-99) , 
1, 0.00579195, 1, 0, 0.545665,-99) , 
NN(
0, 
0, 
-1, -0.912275, 1, -1, 0.405628,-99) , 
6, -0.465096, 0, 0, 0.480245,-99)    );
  // itree = 180
  fBoostWeights.push_back(0.172284);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.608763,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492539,-99) , 
5, 0.362194, 1, 0, 0.537076,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407005,-99) , 
5, -0.887528, 0, 0, 0.495474,-99)    );
  // itree = 181
  fBoostWeights.push_back(0.242505);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.673806,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.565434,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431769,-99) , 
0, 0.0941998, 1, 0, 0.530893,-99) , 
0, 0.116196, 0, 0, 0.556909,-99)    );
  // itree = 182
  fBoostWeights.push_back(0.175901);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.62293,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533211,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428468,-99) , 
2, -0.00278055, 0, 0, 0.482139,-99) , 
0, 0.126205, 0, 0, 0.503143,-99)    );
  // itree = 183
  fBoostWeights.push_back(0.271998);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.658546,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.576109,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42843,-99) , 
5, 0.683579, 0, 0, 0.476542,-99) , 
4, 0.00897291, 1, 0, 0.525268,-99)    );
  // itree = 184
  fBoostWeights.push_back(0.239378);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.593207,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464507,-99) , 
5, -0.747063, 1, 0, 0.516615,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.301093,-99) , 
6, 0.935516, 1, 0, 0.476897,-99)    );
  // itree = 185
  fBoostWeights.push_back(0.242849);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.636973,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568279,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430265,-99) , 
0, 0.0993561, 0, 0, 0.483705,-99) , 
4, 0.00741759, 1, 0, 0.521458,-99)    );
  // itree = 186
  fBoostWeights.push_back(0.241293);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.731654,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491136,-99) , 
4, 0.0164629, 1, 0, 0.56818,-99) , 
NN(
0, 
0, 
-1, 0.00293954, 1, -1, 0.405559,-99) , 
3, 0.455738, 1, 0, 0.50978,-99)    );
  // itree = 187
  fBoostWeights.push_back(0.174238);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0107026, 1, 1, 0.559392,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424261,-99) , 
3, 0.836984, 1, 0, 0.538591,-99)    );
  // itree = 188
  fBoostWeights.push_back(0.193493);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.656614,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486411,-99) , 
6, -0.838973, 0, 0, 0.556736,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538732,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422496,-99) , 
3, 0.413868, 0, 0, 0.457218,-99) , 
5, -0.526618, 1, 0, 0.497627,-99)    );
  // itree = 189
  fBoostWeights.push_back(0.24685);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.69189,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.567791,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453283,-99) , 
4, 0.0135772, 0, 0, 0.516202,-99) , 
6, -0.80553, 1, 0, 0.554289,-99)    );
  // itree = 190
  fBoostWeights.push_back(0.1688);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.648835,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48808,-99) , 
1, -0.00300443, 0, 0, 0.575794,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471118,-99) , 
3, 0.106468, 0, 0, 0.527518,-99)    );
  // itree = 191
  fBoostWeights.push_back(0.250333);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.110722, 1, 1, 0.588611,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509561,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.320521,-99) , 
4, 0.00308883, 1, 0, 0.422136,-99) , 
3, 0.553572, 1, 0, 0.536391,-99)    );
  // itree = 192
  fBoostWeights.push_back(0.159076);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.768089, 0, 1, 0.531979,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536977,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.377795,-99) , 
5, 0.789301, 0, 0, 0.460677,-99) , 
5, -0.366658, 1, 0, 0.493738,-99)    );
  // itree = 193
  fBoostWeights.push_back(0.186401);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.604501,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477276,-99) , 
4, 0.0101275, 0, 0, 0.528068,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.419842,-99) , 
4, 0.0237601, 1, 0, 0.48087,-99)    );
  // itree = 194
  fBoostWeights.push_back(0.199277);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.570893,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482911,-99) , 
6, 0.139777, 0, 0, 0.517782,-99) , 
NN(
0, 
0, 
-1, 0.314468, 1, -1, 0.409125,-99) , 
0, 0.0815417, 1, 0, 0.450924,-99)    );
  // itree = 195
  fBoostWeights.push_back(0.218777);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.605843,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478493,-99) , 
2, -0.00174816, 0, 0, 0.545827,-99) , 
NN(
0, 
0, 
-1, -0.295176, 0, -1, 0.408237,-99) , 
0, 0.0787212, 0, 0, 0.484675,-99)    );
  // itree = 196
  fBoostWeights.push_back(0.222999);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0960706, 0, 1, 0.60884,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491005,-99) , 
2, 0.00657467, 1, 0, 0.573595,-99)    );
  // itree = 197
  fBoostWeights.push_back(0.20168);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.574329,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.567294,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429197,-99) , 
0, 0.0848644, 1, 0, 0.491561,-99) , 
3, 0.152159, 1, 0, 0.52907,-99)    );
  // itree = 198
  fBoostWeights.push_back(0.196056);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.674433,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.594458,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494185,-99) , 
5, -0.416646, 1, 0, 0.541582,-99) , 
3, 0.694779, 0, 0, 0.564491,-99)    );
  // itree = 199
  fBoostWeights.push_back(0.250413);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.621394,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468496,-99) , 
6, -0.880874, 0, 0, 0.545475,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.57966,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.396611,-99) , 
6, 0.895812, 0, 0, 0.448819,-99) , 
6, -0.473574, 1, 0, 0.488384,-99)    );
  // itree = 200
  fBoostWeights.push_back(0.162618);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.680847,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499636,-99) , 
0, 0.0709136, 1, 0, 0.540307,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.375361,-99) , 
5, 0.937516, 1, 0, 0.506938,-99)    );
  // itree = 201
  fBoostWeights.push_back(0.217004);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.878531, 1, 1, 0.600399,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542258,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.408316,-99) , 
3, 0.453727, 1, 0, 0.49082,-99) , 
6, 0.499145, 0, 0, 0.534606,-99)    );
  // itree = 202
  fBoostWeights.push_back(0.225931);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.63359,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448882,-99) , 
5, 0.876531, 1, 0, 0.555459,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455428,-99) , 
1, -0.00511542, 0, 0, 0.520888,-99)    );
  // itree = 203
  fBoostWeights.push_back(0.231369);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.739272,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528906,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.406851,-99) , 
0, 0.0743476, 0, 0, 0.485754,-99) , 
6, -0.907505, 1, 0, 0.526646,-99)    );
  // itree = 204
  fBoostWeights.push_back(0.178931);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.574955,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52146,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.406251,-99) , 
5, 0.0762309, 0, 0, 0.457643,-99) , 
0, 0.116196, 0, 0, 0.475572,-99)    );
  // itree = 205
  fBoostWeights.push_back(0.279767);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.00114445, 0, 1, 0.621832,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535923,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.36481,-99) , 
5, 0.244689, 1, 0, 0.448785,-99) , 
4, 0.0112552, 1, 0, 0.508172,-99)    );
  // itree = 206
  fBoostWeights.push_back(0.23066);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.601894,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.590702,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428081,-99) , 
0, 0.0720913, 1, 0, 0.469732,-99) , 
6, -0.856467, 1, 0, 0.495527,-99)    );
  // itree = 207
  fBoostWeights.push_back(0.193807);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.667785, 0, 1, 0.560129,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.386863,-99) , 
0, 0.0654282, 0, 0, 0.531857,-99)    );
  // itree = 208
  fBoostWeights.push_back(0.180863);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.857536, 1, 1, 0.559354,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426848,-99) , 
2, -0.00733341, 0, 0, 0.512463,-99)    );
  // itree = 209
  fBoostWeights.push_back(0.166627);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.576602,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556175,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444125,-99) , 
6, 0.901265, 0, 0, 0.466901,-99) , 
6, -0.899006, 1, 0, 0.484389,-99)    );
  // itree = 210
  fBoostWeights.push_back(0.193848);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.664005,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524183,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43394,-99) , 
5, 0.483628, 0, 0, 0.468187,-99) , 
3, 0.696528, 0, 0, 0.500224,-99)    );
  // itree = 211
  fBoostWeights.push_back(0.127558);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.574146,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503215,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43526,-99) , 
6, -0.278179, 1, 0, 0.466199,-99) , 
4, 0.00678927, 1, 0, 0.491304,-99)    );
  // itree = 212
  fBoostWeights.push_back(0.199389);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.283687, 1, 1, 0.590705,-99) , 
NN(
0, 
0, 
-1, 0.372157, 1, -1, 0.439877,-99) , 
0, 0.0968483, 0, 0, 0.492202,-99)    );
  // itree = 213
  fBoostWeights.push_back(0.183767);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.910522, 0, 1, 0.604205,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521778,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.410806,-99) , 
0, 0.102719, 1, 0, 0.490291,-99) , 
6, -0.497614, 1, 0, 0.534113,-99)    );
  // itree = 214
  fBoostWeights.push_back(0.145434);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.633865,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499108,-99) , 
6, 0.784555, 0, 0, 0.53367,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.364633,-99) , 
3, 0.782511, 1, 0, 0.505445,-99)    );
  // itree = 215
  fBoostWeights.push_back(0.151931);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.623121,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498551,-99) , 
0, 0.119289, 1, 0, 0.560854,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50481,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.37648,-99) , 
6, 0.46295, 1, 0, 0.455679,-99) , 
0, 0.098203, 0, 0, 0.488781,-99)    );
  // itree = 216
  fBoostWeights.push_back(0.24513);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.608776,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558216,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.410661,-99) , 
0, 0.0778625, 1, 0, 0.457729,-99) , 
3, 0.508588, 0, 0, 0.49503,-99)    );
  // itree = 217
  fBoostWeights.push_back(0.194873);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555127,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44564,-99) , 
6, 0.712574, 1, 0, 0.51829,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.387337,-99) , 
3, 0.664939, 1, 0, 0.485927,-99)    );
  // itree = 218
  fBoostWeights.push_back(0.16527);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.677664,-99) , 
NN(
0, 
0, 
-1, 0.750564, 1, -1, 0.470989,-99) , 
3, 0.575446, 0, 0, 0.512338,-99)    );
  // itree = 219
  fBoostWeights.push_back(0.202468);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.114905, 0, 1, 0.561812,-99) , 
NN(
0, 
0, 
-1, 0.0654349, 0, -1, 0.412255,-99) , 
0, 0.0784864, 0, 0, 0.504154,-99)    );
  // itree = 220
  fBoostWeights.push_back(0.135305);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0220497, 1, 1, 0.550727,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462369,-99) , 
3, 0.717571, 1, 0, 0.533496,-99)    );
  // itree = 221
  fBoostWeights.push_back(0.1709);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.587476,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526972,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.415147,-99) , 
6, 0.209727, 0, 0, 0.475681,-99) , 
6, -0.83647, 1, 0, 0.499433,-99)    );
  // itree = 222
  fBoostWeights.push_back(0.173963);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.176706, 0, 1, 0.581252,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.590729,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464198,-99) , 
5, 0.833542, 0, 0, 0.496982,-99) , 
0, 0.0796205, 1, 0, 0.528776,-99)    );
  // itree = 223
  fBoostWeights.push_back(0.229287);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.566492,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438772,-99) , 
5, -0.728568, 0, 0, 0.501587,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.354531,-99) , 
6, 0.890032, 1, 0, 0.470346,-99)    );
  // itree = 224
  fBoostWeights.push_back(0.196667);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.654462,-99) , 
NN(
0, 
0, 
-1, 0.797007, 1, -1, 0.4486,-99) , 
5, -0.949013, 1, 0, 0.485312,-99)    );
  // itree = 225
  fBoostWeights.push_back(0.296249);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.678458,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424103,-99) , 
6, -0.88113, 0, 0, 0.567272,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516945,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.353718,-99) , 
3, 0.319403, 1, 0, 0.439358,-99) , 
5, -0.250687, 1, 0, 0.499209,-99)    );
  // itree = 226
  fBoostWeights.push_back(0.116926);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.62579,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500308,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.386646,-99) , 
6, -0.653895, 0, 0, 0.474603,-99) , 
6, -0.906502, 1, 0, 0.498494,-99)    );
  // itree = 227
  fBoostWeights.push_back(0.27439);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.680881,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557608,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424924,-99) , 
0, 0.0989847, 0, 0, 0.472572,-99) , 
3, 0.415306, 0, 0, 0.524534,-99)    );
  // itree = 228
  fBoostWeights.push_back(0.150575);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.608705,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480828,-99) , 
3, 0.626616, 1, 0, 0.537752,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449859,-99) , 
3, 0.272123, 0, 0, 0.483778,-99)    );
  // itree = 229
  fBoostWeights.push_back(0.212967);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.121099, 0, 1, 0.5861,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519767,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.400868,-99) , 
2, -0.00356141, 0, 0, 0.463907,-99) , 
3, 0.428869, 1, 0, 0.541417,-99)    );
  // itree = 230
  fBoostWeights.push_back(0.198852);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.57611,-99) , 
NN(
0, 
0, 
-1, 0.0892134, 0, -1, 0.431274,-99) , 
0, 0.0698901, 1, 0, 0.466947,-99)    );
  // itree = 231
  fBoostWeights.push_back(0.177661);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.569228,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513088,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424433,-99) , 
5, 0.951012, 0, 0, 0.445216,-99) , 
6, -0.747494, 1, 0, 0.477933,-99)    );
  // itree = 232
  fBoostWeights.push_back(0.173655);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.592234,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507054,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.400013,-99) , 
6, 0.518667, 0, 0, 0.455997,-99) , 
6, -0.730551, 1, 0, 0.490417,-99)    );
  // itree = 233
  fBoostWeights.push_back(0.228988);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.576413,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436063,-99) , 
1, -0.00618765, 0, 0, 0.50708,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.397268,-99) , 
1, 0.00560355, 1, 0, 0.470534,-99)    );
  // itree = 234
  fBoostWeights.push_back(0.174849);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.617538,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494413,-99) , 
4, 0.0203678, 1, 0, 0.54142,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514907,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.351401,-99) , 
5, -0.163709, 1, 0, 0.429891,-99) , 
0, 0.0780134, 0, 0, 0.498791,-99)    );
  // itree = 235
  fBoostWeights.push_back(0.18102);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.660984,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.636632,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491015,-99) , 
5, 0.893527, 0, 0, 0.528363,-99) , 
6, -0.864989, 1, 0, 0.55346,-99)    );
  // itree = 236
  fBoostWeights.push_back(0.269953);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.599409,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445558,-99) , 
5, -0.913888, 0, 0, 0.554063,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.365965,-99) , 
5, 0.946513, 1, 0, 0.518396,-99)    );
  // itree = 237
  fBoostWeights.push_back(0.224992);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.636906,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498191,-99) , 
3, 0.453788, 1, 0, 0.587744,-99) , 
NN(
0, 
0, 
-1, 0.64947, 0, -1, 0.427985,-99) , 
6, -0.150725, 1, 0, 0.499875,-99)    );
  // itree = 238
  fBoostWeights.push_back(0.258831);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.674125,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480329,-99) , 
3, 0.323646, 1, 0, 0.588283,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.570484,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.409589,-99) , 
5, -0.687078, 1, 0, 0.468194,-99) , 
0, 0.0928596, 0, 0, 0.512103,-99)    );
  // itree = 239
  fBoostWeights.push_back(0.175059);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577196,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.564322,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449611,-99) , 
0, 0.0749822, 1, 0, 0.484329,-99) , 
2, 0.00632515, 0, 0, 0.515536,-99)    );
  // itree = 240
  fBoostWeights.push_back(0.230861);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.00683776, 0, 1, 0.593627,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453811,-99) , 
5, 0.914521, 1, 0, 0.558507,-99)    );
  // itree = 241
  fBoostWeights.push_back(0.175666);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.623317,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483668,-99) , 
3, 0.717595, 1, 0, 0.558831,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444981,-99) , 
4, 0.0135772, 1, 0, 0.489517,-99)    );
  // itree = 242
  fBoostWeights.push_back(0.178647);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.000108508, 1, 1, 0.572005,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450365,-99) , 
0, 0.0752561, 0, 0, 0.525531,-99)    );
  // itree = 243
  fBoostWeights.push_back(0.218826);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.192326, 0, 1, 0.574985,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414817,-99) , 
3, 0.68829, 1, 0, 0.53514,-99)    );
  // itree = 244
  fBoostWeights.push_back(0.178546);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.789552, 0, 1, 0.569202,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514482,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.38573,-99) , 
6, -0.697058, 0, 0, 0.461544,-99) , 
0, 0.0956682, 1, 0, 0.523756,-99)    );
  // itree = 245
  fBoostWeights.push_back(0.213811);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559916,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461275,-99) , 
3, 0.184691, 0, 0, 0.508187,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.364492,-99) , 
6, 0.751988, 1, 0, 0.46349,-99)    );
  // itree = 246
  fBoostWeights.push_back(0.219802);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.19241, 0, 1, 0.579085,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425848,-99) , 
6, 0.87648, 1, 0, 0.541103,-99)    );
  // itree = 247
  fBoostWeights.push_back(0.199992);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.68795,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577559,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48276,-99) , 
0, 0.0927889, 0, 0, 0.522323,-99) , 
5, 0.904024, 0, 0, 0.554792,-99)    );
  // itree = 248
  fBoostWeights.push_back(0.243669);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.656685,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532878,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.420094,-99) , 
5, 0.781055, 0, 0, 0.450242,-99) , 
4, 0.00678892, 1, 0, 0.493729,-99)    );
  // itree = 249
  fBoostWeights.push_back(0.244497);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.636638,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.618841,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.433791,-99) , 
6, -0.892094, 1, 0, 0.469397,-99) , 
6, 0.876968, 0, 0, 0.497427,-99)    );
  // itree = 250
  fBoostWeights.push_back(0.167386);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.839699, 0, 1, 0.57885,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524412,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.389636,-99) , 
5, 0.0862534, 0, 0, 0.488284,-99) , 
6, -0.484096, 1, 0, 0.523027,-99)    );
  // itree = 251
  fBoostWeights.push_back(0.187825);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.627394,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48541,-99) , 
5, -0.591102, 1, 0, 0.525893,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.358691,-99) , 
6, -0.877016, 0, 0, 0.490654,-99)    );
  // itree = 252
  fBoostWeights.push_back(0.20599);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.655657,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534256,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.411743,-99) , 
5, -0.700075, 0, 0, 0.483268,-99) , 
3, 0.68779, 0, 0, 0.511693,-99)    );
  // itree = 253
  fBoostWeights.push_back(0.198832);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532589,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434414,-99) , 
3, 0.228612, 1, 0, 0.484247,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.340643,-99) , 
6, 0.882468, 1, 0, 0.45605,-99)    );
  // itree = 254
  fBoostWeights.push_back(0.152523);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0699531, 1, 1, 0.569553,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463514,-99) , 
4, 0.0237155, 1, 0, 0.520505,-99)    );
  // itree = 255
  fBoostWeights.push_back(0.2253);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.653461,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534254,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.405127,-99) , 
3, 0.137958, 0, 0, 0.472209,-99) , 
5, -0.947013, 1, 0, 0.505199,-99)    );
  // itree = 256
  fBoostWeights.push_back(0.237178);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0940128, 1, 1, 0.613936,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545921,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.372786,-99) , 
6, -0.0146297, 1, 0, 0.495656,-99) , 
6, 0.65209, 0, 0, 0.53396,-99)    );
  // itree = 257
  fBoostWeights.push_back(0.254926);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.638658,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477562,-99) , 
1, -0.00201106, 0, 0, 0.566765,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.406417,-99) , 
3, 0.130208, 0, 0, 0.489801,-99)    );
  // itree = 258
  fBoostWeights.push_back(0.183983);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.660314,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49902,-99) , 
1, -0.00504084, 0, 0, 0.562501,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558545,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425785,-99) , 
5, 0.897667, 0, 0, 0.481568,-99) , 
1, 0.00260933, 1, 0, 0.528761,-99)    );
  // itree = 259
  fBoostWeights.push_back(0.184247);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550462,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457858,-99) , 
0, 0.073612, 0, 0, 0.518513,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.359471,-99) , 
6, 0.920984, 1, 0, 0.487995,-99)    );
  // itree = 260
  fBoostWeights.push_back(0.152319);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.609558,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527886,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445525,-99) , 
6, -0.208157, 1, 0, 0.483212,-99) , 
3, 0.696538, 0, 0, 0.505527,-99)    );
  // itree = 261
  fBoostWeights.push_back(0.208525);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.695542,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482524,-99) , 
6, 0.778964, 1, 0, 0.572154,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504544,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.358012,-99) , 
5, -0.805016, 1, 0, 0.450039,-99) , 
5, -0.228193, 0, 0, 0.510742,-99)    );
  // itree = 262
  fBoostWeights.push_back(0.254962);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.582959,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428841,-99) , 
0, 0.115104, 1, 0, 0.54443,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.393799,-99) , 
2, -0.0071867, 0, 0, 0.486602,-99)    );
  // itree = 263
  fBoostWeights.push_back(0.166833);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.599129,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471039,-99) , 
5, 0.924019, 0, 0, 0.497093,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.356608,-99) , 
3, 0.796744, 1, 0, 0.474553,-99)    );
  // itree = 264
  fBoostWeights.push_back(0.19784);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0875729, 1, 1, 0.575899,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439061,-99) , 
0, 0.0752992, 0, 0, 0.523687,-99)    );
  // itree = 265
  fBoostWeights.push_back(0.227798);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.578398,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545152,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.3963,-99) , 
6, -0.550109, 1, 0, 0.450623,-99) , 
3, 0.133458, 1, 0, 0.505417,-99)    );
  // itree = 266
  fBoostWeights.push_back(0.148227);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0848435, 1, 1, 0.550496,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436433,-99) , 
6, 0.932452, 1, 0, 0.530898,-99)    );
  // itree = 267
  fBoostWeights.push_back(0.20968);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.663895,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527981,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.395637,-99) , 
0, 0.0884778, 1, 0, 0.475152,-99) , 
0, 0.121041, 0, 0, 0.503546,-99)    );
  // itree = 268
  fBoostWeights.push_back(0.144418);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.603127,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517327,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.400079,-99) , 
2, 0.00286826, 1, 0, 0.483508,-99) , 
6, 0.922438, 0, 0, 0.503281,-99)    );
  // itree = 269
  fBoostWeights.push_back(0.23489);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.563452,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.393462,-99) , 
5, 0.950512, 1, 0, 0.522976,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.397041,-99) , 
1, -0.00541739, 0, 0, 0.482503,-99)    );
  // itree = 270
  fBoostWeights.push_back(0.268597);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.564912,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.432549,-99) , 
0, 0.0856952, 1, 0, 0.494463,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.375944,-99) , 
3, 0.118928, 0, 0, 0.436008,-99)    );
  // itree = 271
  fBoostWeights.push_back(0.159531);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.604333,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484309,-99) , 
6, -0.473629, 1, 0, 0.516664,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.376856,-99) , 
5, -0.962509, 0, 0, 0.487981,-99)    );
  // itree = 272
  fBoostWeights.push_back(0.256637);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0853287, 1, 1, 0.584844,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.398808,-99) , 
5, -0.850037, 0, 0, 0.518856,-99)    );
  // itree = 273
  fBoostWeights.push_back(0.278813);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.707247,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45317,-99) , 
3, 0.335525, 1, 0, 0.545706,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.40906,-99) , 
4, 0.018362, 1, 0, 0.479125,-99)    );
  // itree = 274
  fBoostWeights.push_back(0.270903);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.635505,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450826,-99) , 
0, 0.0948956, 1, 0, 0.532713,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.38037,-99) , 
0, 0.0706833, 0, 0, 0.494323,-99)    );
  // itree = 275
  fBoostWeights.push_back(0.226203);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.616756,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534056,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.346515,-99) , 
5, 0.251771, 1, 0, 0.476633,-99) , 
5, 0.888528, 0, 0, 0.505388,-99)    );
  // itree = 276
  fBoostWeights.push_back(0.224543);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.693307,-99) , 
NN(
0, 
0, 
-1, 0.0885051, 1, -1, 0.447321,-99) , 
0, 0.113238, 0, 0, 0.494259,-99)    );
  // itree = 277
  fBoostWeights.push_back(0.211751);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.649698,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.595561,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457456,-99) , 
6, 0.782044, 0, 0, 0.49894,-99) , 
0, 0.0671616, 1, 0, 0.526347,-99)    );
  // itree = 278
  fBoostWeights.push_back(0.236114);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.672447,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475986,-99) , 
5, -0.926518, 0, 0, 0.589136,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466954,-99) , 
1, 0.00513595, 1, 0, 0.547639,-99)    );
  // itree = 279
  fBoostWeights.push_back(0.256303);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.707078,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.581785,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443539,-99) , 
6, 0.0437794, 0, 0, 0.519225,-99) , 
6, -0.870013, 1, 0, 0.546977,-99)    );
  // itree = 280
  fBoostWeights.push_back(0.216791);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.106762, 0, 1, 0.569922,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.403561,-99) , 
6, -0.826026, 0, 0, 0.526695,-99)    );
  // itree = 281
  fBoostWeights.push_back(0.193204);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.162198, 0, 1, 0.588237,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461777,-99) , 
0, 0.0760817, 0, 0, 0.538501,-99)    );
  // itree = 282
  fBoostWeights.push_back(0.170522);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.621204,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521083,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.406848,-99) , 
3, 0.560165, 1, 0, 0.485338,-99) , 
5, -0.946513, 1, 0, 0.515056,-99)    );
  // itree = 283
  fBoostWeights.push_back(0.170508);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0013072, 0, 1, 0.564183,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442554,-99) , 
3, 0.192439, 0, 0, 0.499432,-99)    );
  // itree = 284
  fBoostWeights.push_back(0.252862);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.890015, 0, 1, 0.664508,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522129,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.402288,-99) , 
3, 0.428337, 1, 0, 0.477444,-99) , 
5, -0.766558, 1, 0, 0.541373,-99)    );
  // itree = 285
  fBoostWeights.push_back(0.173378);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544939,-99) , 
NN(
0, 
0, 
-1, 0.100149, 1, -1, 0.431062,-99) , 
6, 0.652076, 0, 0, 0.465853,-99)    );
  // itree = 286
  fBoostWeights.push_back(0.242567);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.605232,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548366,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.405223,-99) , 
5, 0.833543, 0, 0, 0.452869,-99) , 
6, -0.770989, 1, 0, 0.490783,-99)    );
  // itree = 287
  fBoostWeights.push_back(0.204351);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.69054, 0, 1, 0.550713,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.38142,-99) , 
6, 0.818988, 1, 0, 0.496445,-99)    );
  // itree = 288
  fBoostWeights.push_back(0.213932);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562708,-99) , 
NN(
0, 
0, 
-1, -0.872532, 1, -1, 0.420449,-99) , 
3, 0.628059, 0, 0, 0.452001,-99)    );
  // itree = 289
  fBoostWeights.push_back(0.207883);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.00581978, 0, 1, 0.590136,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53515,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417524,-99) , 
6, 0.772285, 0, 0, 0.477262,-99) , 
5, -0.0617346, 1, 0, 0.531616,-99)    );
  // itree = 290
  fBoostWeights.push_back(0.241746);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0134745, 1, 1, 0.575499,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.393811,-99) , 
1, 0.00561008, 1, 0, 0.516353,-99)    );
  // itree = 291
  fBoostWeights.push_back(0.210885);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.608051,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528322,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.420408,-99) , 
6, 0.850506, 0, 0, 0.444997,-99) , 
3, 0.679534, 0, 0, 0.472789,-99)    );
  // itree = 292
  fBoostWeights.push_back(0.219128);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.583293,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558957,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417567,-99) , 
0, 0.0685334, 1, 0, 0.45691,-99) , 
0, 0.106762, 0, 0, 0.486432,-99)    );
  // itree = 293
  fBoostWeights.push_back(0.143866);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.596457,-99) , 
NN(
0, 
0, 
-1, 0.0950696, 1, -1, 0.467162,-99) , 
6, -0.733051, 1, 0, 0.504479,-99)    );
  // itree = 294
  fBoostWeights.push_back(0.225195);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.6008,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526209,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.361188,-99) , 
0, 0.0946808, 1, 0, 0.456841,-99) , 
6, 0.828544, 0, 0, 0.489574,-99)    );
  // itree = 295
  fBoostWeights.push_back(0.227235);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.679601,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451562,-99) , 
5, -0.928448, 0, 0, 0.536528,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5372,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.418794,-99) , 
0, 0.103002, 0, 0, 0.450456,-99) , 
5, -0.700575, 1, 0, 0.484462,-99)    );
  // itree = 296
  fBoostWeights.push_back(0.225473);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.602947,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464819,-99) , 
5, 0.857536, 1, 0, 0.553616,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.418141,-99) , 
6, -0.666516, 0, 0, 0.506123,-99)    );
  // itree = 297
  fBoostWeights.push_back(0.197451);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529814,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.387516,-99) , 
0, 0.11745, 1, 0, 0.491218,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.36195,-99) , 
0, 0.0662819, 0, 0, 0.464378,-99)    );
  // itree = 298
  fBoostWeights.push_back(0.177909);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.600508,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527148,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421849,-99) , 
5, 0.583625, 0, 0, 0.468201,-99) , 
5, -0.946513, 1, 0, 0.490343,-99)    );
  // itree = 299
  fBoostWeights.push_back(0.208548);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.632043,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541359,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.372102,-99) , 
6, 0.852503, 1, 0, 0.504172,-99) , 
0, 0.116107, 0, 0, 0.528371,-99)    );
   return;
};

// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}

inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
