// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.24/06       [399366]
Creator        : vince402
Date           : Thu Oct 21 14:20:10 2021
Host           : Linux kunpl 5.4.0-88-generic #99-Ubuntu SMP Thu Sep 23 17:29:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/vince402/Upsilon3S/BDT
Training events: 80763
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "True" [Create PDFs for classifier outputs (signal and background)]
NTrees: "300" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "15%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "4000" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "7.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
BaggedSampleFraction: "4.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "giniindex" [Separation criterion for node splitting]
PruneMethod: "costcomplexity" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "1.000000e+00" [Pruning strength]
PruningValFraction: "3.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
Shrinkage: "1.000000e+00" [Learning rate for BoostType=Grad algorithm]
UseNvars: "3" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "4.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 7
QQMassErr                     QQMassErr                     QQMassErr                     Dimu Mass error               F                                 'F'    [0,112.100982666]
ctau3D                        ctau3D                        ctau3D                        3 dim ctau of the dimuon      F                                 'F'    [-1000,11.0573558807]
ctau                          ctau                          ctau                          2 dim ctau of the dimuon      F                                 'F'    [-1000,8.86820411682]
QQVtxProb                     QQVtxProb                     QQVtxProb                     Vtx prob                      F                                 'F'    [-1,0.999993562698]
QQdca                         QQdca                         QQdca                         QQdca                         F                                 'F'    [-10,19.3620491028]
cosAlpha                      cosAlpha                      cosAlpha                      cos alpha for trajectory angleF                                 'F'    [-10,1]
cosAlpha3D                    cosAlpha3D                    cosAlpha3D                    cos alpha for trajectory angle 3DF                                 'F'    [-10,1]
NSpec 8
pt1                           pt1                           pt1                           Single muon pt1               F                                 'F'    [3.50009417534,14.5156755447]
pt2                           pt2                           pt2                           Single muon pt2               F                                 'F'    [3.50004005432,14.949461937]
eta1                          eta1                          eta1                          Single muon eta1              F                                 'F'    [-2.39996814728,2.39999604225]
eta2                          eta2                          eta2                          Single muon eta2              F                                 'F'    [-2.39921855927,2.39999341965]
cBin                          cBin                          cBin                          Centrality times 2 bin        F                                 'F'    [1,180]
mass                          mass                          mass                          Dimuon mass                   F                                 'F'    [8.00038719177,11.4995393753]
pt                            pt                            pt                            Dimuon pt                     F                                 'F'    [12.0000400543,14.9999361038]
y                             y                             y                             Dimuon y                      F                                 'F'    [-2.38834452629,2.39673757553]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#include <algorithm>
#include <limits>

#define NN new BDTNode

#ifndef BDTNode__def
#define BDTNode__def

class BDTNode {

public:

   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 

//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 

//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] >= fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}

//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}

#endif

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 7 )
   {
      // the training input variables
      const char* inputVars[] = { "QQMassErr", "ctau3D", "ctau", "QQVtxProb", "QQdca", "cosAlpha", "cosAlpha3D" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[7];
   double fVmax[7];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[7];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
}

void ReadBDT::Initialize()
{
  double inf = std::numeric_limits<double>::infinity();
  double nan = std::numeric_limits<double>::quiet_NaN();
  // itree = 0
  fBoostWeights.push_back(0.686734207002937);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.00476721, 0, 1, 0.696414,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.235176,-99) , 
4, 0.016071, 1, 0, 0.488062,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.651937);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.00503504, 0, 1, 0.685286,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.241567,-99) , 
4, 0.0192843, 1, 0, 0.4908,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.594351);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.731237,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455333,-99) , 
2, -0.00536244, 0, 0, 0.647019,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.261821,-99) , 
3, 0.147961, 0, 0, 0.489753,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.387547);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0737631, 0, 1, 0.611742,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.326303,-99) , 
3, 0.129967, 0, 0, 0.504682,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.476275);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.707556,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.375318,-99) , 
2, 0.00606283, 1, 0, 0.577185,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.361378,-99) , 
2, -0.0065611, 0, 0, 0.510752,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.413724);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.652439,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.406396,-99) , 
1, 0.00482818, 1, 0, 0.580062,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.344025,-99) , 
3, 0.137958, 0, 0, 0.48414,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.34715);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.689727,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.585917,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.377766,-99) , 
5, 0.610097, 0, 0, 0.454116,-99) , 
6, -0.894526, 1, 0, 0.490819,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.266893);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.328665, 1, 1, 0.623552,-99) , 
NN(
0, 
0, 
-1, 0.0632792, 0, -1, 0.419479,-99) , 
0, 0.0982514, 0, 0, 0.484257,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.254109);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0737953, 0, 1, 0.599598,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42523,-99) , 
4, 0.0193573, 1, 0, 0.530574,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.30596);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.742943,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.573518,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.418126,-99) , 
0, 0.0987553, 0, 0, 0.476182,-99) , 
4, 0.00404523, 1, 0, 0.522993,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.169608);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.501125, 1, 1, 0.565432,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444863,-99) , 
4, 0.0130577, 1, 0, 0.505091,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.240585);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.93277, 0, 1, 0.586969,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545163,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.378617,-99) , 
1, 0.00401136, 1, 0, 0.459767,-99) , 
6, -0.616616, 1, 0, 0.499116,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.211371);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.629475,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.567568,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438244,-99) , 
6, -0.679267, 1, 0, 0.485852,-99) , 
5, 0.923019, 0, 0, 0.509999,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.169711);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.586124,-99) , 
NN(
0, 
0, 
-1, 0.0645081, 0, -1, 0.446304,-99) , 
0, 0.112073, 0, 0, 0.474846,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.284446);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.666254,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489891,-99) , 
4, 0.02152, 1, 0, 0.590051,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.393702,-99) , 
0, 0.0637747, 0, 0, 0.552773,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.332165);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.663741,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434192,-99) , 
2, 0.00681147, 1, 0, 0.575367,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.403014,-99) , 
2, -0.00581424, 0, 0, 0.518507,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.219162);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.263685, 1, 1, 0.553554,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.360625,-99) , 
1, -0.00567075, 0, 0, 0.499408,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.273441);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.336654, 0, 1, 0.598673,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.616403,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.413039,-99) , 
6, -0.886445, 1, 0, 0.469113,-99) , 
5, 0.235691, 0, 0, 0.517974,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.192941);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.596756,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.57686,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447493,-99) , 
5, 0.928018, 0, 0, 0.475225,-99) , 
6, -0.726568, 1, 0, 0.508689,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.208144);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.7656,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490765,-99) , 
6, 0.0117648, 1, 0, 0.562164,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431129,-99) , 
1, -0.00512917, 0, 0, 0.52375,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.255922);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.662825,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56926,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444487,-99) , 
1, 0.00207661, 1, 0, 0.515552,-99) , 
4, 0.00642853, 1, 0, 0.555602,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.241623);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.641521,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469368,-99) , 
2, 0.00695465, 1, 0, 0.574302,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439034,-99) , 
2, -0.00566712, 0, 0, 0.527918,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.261127);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0911139, 1, 1, 0.616549,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544146,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.368583,-99) , 
5, -0.520672, 1, 0, 0.470177,-99) , 
5, 0.595601, 0, 0, 0.516501,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.312662);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.689649,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449973,-99) , 
1, -0.00467254, 0, 0, 0.580774,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424772,-99) , 
1, 0.00508973, 1, 0, 0.530667,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.221126);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.621873,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47223,-99) , 
1, 0.00598821, 1, 0, 0.562354,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434035,-99) , 
1, -0.00465049, 0, 0, 0.519851,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.23739);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.641586,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.597554,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448566,-99) , 
6, -0.741702, 1, 0, 0.498822,-99) , 
5, 0.84004, 0, 0, 0.531334,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.178206);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.64663,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489404,-99) , 
2, -0.00449449, 0, 0, 0.562254,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459142,-99) , 
2, 0.00549692, 1, 0, 0.52977,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.253803);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0912892, 1, 1, 0.580237,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572903,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.370692,-99) , 
5, -0.6006, 1, 0, 0.489412,-99) , 
6, 0.337168, 0, 0, 0.526574,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.271551);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.671583,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.596413,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426712,-99) , 
6, -0.666879, 1, 0, 0.484228,-99) , 
6, 0.890027, 0, 0, 0.514589,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.226778);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.645366,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53622,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.380147,-99) , 
0, 0.0903692, 1, 0, 0.478935,-99) , 
0, 0.11616, 0, 0, 0.50731,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.305328);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.661141,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480835,-99) , 
1, 0.00574796, 1, 0, 0.581638,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.380757,-99) , 
1, -0.00334966, 0, 0, 0.496156,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.198552);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.732561, 0, 1, 0.573116,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438016,-99) , 
3, 0.688052, 1, 0, 0.540634,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.183656);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.0817296, 1, 1, 0.549307,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.401978,-99) , 
2, -0.00653886, 0, 0, 0.501189,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.161839);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.607676,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558922,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464426,-99) , 
4, 0.00761432, 1, 0, 0.501054,-99) , 
0, 0.112073, 0, 0, 0.522901,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.192462);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.64758,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528767,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442112,-99) , 
2, 0.00693445, 1, 0, 0.495517,-99) , 
6, -0.723821, 1, 0, 0.53559,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.227787);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.653795,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536101,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.398722,-99) , 
6, -0.146903, 1, 0, 0.469937,-99) , 
5, 0.928018, 0, 0, 0.497953,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.133245);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.621059,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527111,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462525,-99) , 
4, 0.0121355, 1, 0, 0.492403,-99) , 
6, -0.872531, 1, 0, 0.513896,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.252148);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0897868, 1, 1, 0.599851,-99) , 
NN(
0, 
0, 
-1, -0.12022, 0, -1, 0.429345,-99) , 
0, 0.0753177, 0, 0, 0.537017,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.159682);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.591304,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529297,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422527,-99) , 
5, -0.0102369, 1, 0, 0.482688,-99) , 
5, 0.935516, 0, 0, 0.4998,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.156924);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55243,-99) , 
NN(
0, 
0, 
-1, -0.280785, 1, -1, 0.44289,-99) , 
6, 0.730567, 0, 0, 0.473292,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.262316);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.582275,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.605277,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.406127,-99) , 
5, 0.906024, 0, 0, 0.448101,-99) , 
6, -0.67808, 1, 0, 0.483301,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.289905);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.621626,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466358,-99) , 
1, 0.00587479, 1, 0, 0.554359,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.362967,-99) , 
5, -0.861285, 0, 0, 0.487944,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.196218);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.605655,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457836,-99) , 
3, 0.727063, 1, 0, 0.545274,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54833,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430567,-99) , 
0, 0.10435, 0, 0, 0.471784,-99) , 
4, 0.0114088, 1, 0, 0.503285,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.220019);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.641945,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540219,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423175,-99) , 
6, -0.259981, 1, 0, 0.488059,-99) , 
6, 0.780039, 0, 0, 0.526624,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.196738);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.00651319, 1, 1, 0.566368,-99) , 
NN(
0, 
0, 
-1, 0.00275057, 1, -1, 0.427836,-99) , 
0, 0.0844268, 1, 0, 0.484234,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.240093);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.835995, 1, 1, 0.593925,-99) , 
NN(
0, 
0, 
-1, -0.663343, 1, -1, 0.423313,-99) , 
6, -0.149218, 0, 0, 0.504764,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.167403);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.697476,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485494,-99) , 
5, -0.498625, 1, 0, 0.530088,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423998,-99) , 
1, -0.00599561, 0, 0, 0.50008,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.174395);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.87903, 1, 1, 0.57299,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525544,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.404039,-99) , 
5, -0.677081, 1, 0, 0.478148,-99) , 
6, 0.0762309, 0, 0, 0.520645,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.222816);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.630403,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460496,-99) , 
1, -0.00501623, 0, 0, 0.548232,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435009,-99) , 
1, 0.00515981, 1, 0, 0.508487,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.230839);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.678787,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456028,-99) , 
5, 0.900525, 1, 0, 0.569481,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51801,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.351444,-99) , 
5, -0.429643, 1, 0, 0.464779,-99) , 
6, 0.287926, 0, 0, 0.508267,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.13439);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568374,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514182,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.391367,-99) , 
3, 0.343364, 1, 0, 0.477878,-99) , 
3, 0.613591, 0, 0, 0.497678,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.232162);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.660901,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459401,-99) , 
1, 0.00174484, 1, 0, 0.525313,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.413111,-99) , 
1, -0.00556561, 0, 0, 0.489524,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.251878);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.622973,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457344,-99) , 
0, 0.110604, 1, 0, 0.579476,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429934,-99) , 
2, -0.0044104, 0, 0, 0.518923,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.173395);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.622148,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516188,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.387183,-99) , 
2, -0.00130408, 0, 0, 0.479372,-99) , 
5, -0.861285, 1, 0, 0.511881,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.170507);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.63397,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542024,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467744,-99) , 
6, 0.689321, 0, 0, 0.492013,-99) , 
3, 0.521109, 0, 0, 0.528249,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.117173);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577776,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509866,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.418148,-99) , 
0, 0.0910899, 1, 0, 0.482634,-99) , 
0, 0.109412, 0, 0, 0.504122,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.199723);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.72157, 0, 1, 0.555351,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.367658,-99) , 
6, 0.929018, 1, 0, 0.517568,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.19689);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.60832,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460867,-99) , 
2, -0.00524197, 0, 0, 0.515671,-99) , 
NN(
0, 
0, 
-1, 0.820361, 0, -1, 0.423828,-99) , 
2, 0.00204752, 1, 0, 0.475036,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.197494);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553995,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558419,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42077,-99) , 
5, -0.956311, 1, 0, 0.447774,-99) , 
5, 0.84004, 0, 0, 0.473276,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.1792);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.610516,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468295,-99) , 
5, 0.879031, 1, 0, 0.534406,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502476,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.312788,-99) , 
6, -0.262792, 1, 0, 0.442568,-99) , 
6, 0.471133, 0, 0, 0.477161,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.187331);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.643313,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550702,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449259,-99) , 
6, -0.222949, 1, 0, 0.502589,-99) , 
6, 0.882026, 0, 0, 0.526582,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.262957);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0862868, 1, 1, 0.654433,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521795,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.380776,-99) , 
6, -0.356044, 1, 0, 0.472109,-99) , 
5, 0.329168, 0, 0, 0.540175,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.204304);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.693235,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485026,-99) , 
2, 0.00640816, 1, 0, 0.5624,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517676,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.411727,-99) , 
3, 0.453132, 0, 0, 0.444862,-99) , 
6, 0.216446, 0, 0, 0.493818,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.215974);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.58141,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45633,-99) , 
2, -0.00549305, 0, 0, 0.534332,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.385263,-99) , 
0, 0.0635375, 0, 0, 0.505096,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.129355);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.182852, 0, 1, 0.551656,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468362,-99) , 
3, 0.593573, 1, 0, 0.528401,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.140445);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.594149,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486042,-99) , 
0, 0.104414, 0, 0, 0.514061,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.405046,-99) , 
5, 0.887028, 1, 0, 0.486451,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.172461);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.619653,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517778,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.385355,-99) , 
1, -0.00210793, 0, 0, 0.472474,-99) , 
6, -0.889026, 1, 0, 0.494669,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.191481);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.57453,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452012,-99) , 
5, 0.88003, 1, 0, 0.530865,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425782,-99) , 
1, -0.00599561, 0, 0, 0.497636,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.172166);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.453107, 0, 1, 0.54516,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505082,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.34362,-99) , 
0, 0.106238, 0, 0, 0.426563,-99) , 
0, 0.0910172, 1, 0, 0.488445,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.160876);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580586,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47196,-99) , 
6, -0.848364, 0, 0, 0.538767,-99) , 
NN(
0, 
0, 
-1, 0.906591, 0, -1, 0.448171,-99) , 
6, 0.657587, 1, 0, 0.505276,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.13497);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.579353,-99) , 
NN(
0, 
0, 
-1, 0.476289, 1, -1, 0.459471,-99) , 
4, 0.00483942, 1, 0, 0.48271,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.176356);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.660878,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469028,-99) , 
3, 0.419246, 1, 0, 0.525666,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444967,-99) , 
3, 0.178688, 0, 0, 0.488002,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.15403);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.639096,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496384,-99) , 
5, 0.590602, 0, 0, 0.542303,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422939,-99) , 
3, 0.670058, 1, 0, 0.511985,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.169732);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.584775,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46725,-99) , 
5, -0.47813, 1, 0, 0.496218,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.392824,-99) , 
6, -0.88053, 0, 0, 0.471462,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.19186);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.622621,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580767,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463255,-99) , 
5, 0.923019, 0, 0, 0.490871,-99) , 
6, -0.741565, 1, 0, 0.527511,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.20826);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.681747,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473838,-99) , 
6, 0.92899, 1, 0, 0.600555,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50211,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.41175,-99) , 
3, 0.40708, 1, 0, 0.464505,-99) , 
6, 0.106471, 0, 0, 0.52329,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.155588);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0.231683, 0, 1, 0.55534,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.157067);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.666505,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497969,-99) , 
0, 0.0905655, 1, 0, 0.551798,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441266,-99) , 
0, 0.0713853, 0, 0, 0.51738,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.165202);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.00967872, 1, 1, 0.563597,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455683,-99) , 
0, 0.111266, 1, 0, 0.536345,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.15036);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.087446, 1, 1, 0.546506,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.432549,-99) , 
0, 0.0743503, 0, 0, 0.508485,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.182709);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.870532, 0, 1, 0.560822,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428026,-99) , 
2, -0.00672181, 0, 0, 0.512436,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.145358);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.605541,-99) , 
NN(
0, 
0, 
-1, 0.353775, 1, -1, 0.463501,-99) , 
3, 0.586098, 0, 0, 0.494831,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.232315);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.621316,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.565296,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425052,-99) , 
3, 0.353899, 1, 0, 0.498224,-99) , 
0, 0.0703818, 1, 0, 0.527689,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.204752);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.596367,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543824,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.394607,-99) , 
5, -0.0102474, 1, 0, 0.491223,-99) , 
6, 0.789053, 0, 0, 0.515363,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.193703);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.594675,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477228,-99) , 
1, 0.00163648, 1, 0, 0.540729,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422481,-99) , 
3, 0.13821, 0, 0, 0.487879,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.168392);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.00238343, 1, 1, 0.555936,-99) , 
NN(
0, 
0, 
-1, 0.348325, 0, -1, 0.436172,-99) , 
0, 0.0840547, 0, 0, 0.496517,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.172196);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.622253,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498508,-99) , 
4, 0.0128709, 1, 0, 0.55323,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.415907,-99) , 
6, -0.893008, 0, 0, 0.523621,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.126984);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55924,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512221,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426899,-99) , 
5, -0.466633, 0, 0, 0.472589,-99) , 
4, 0.00651319, 1, 0, 0.494452,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.162894);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572886,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537938,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417974,-99) , 
2, -0.00112389, 0, 0, 0.494182,-99) , 
6, -0.836543, 1, 0, 0.510435,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.154371);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.584193,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475508,-99) , 
6, 0.215948, 0, 0, 0.511372,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.397064,-99) , 
6, 0.937498, 1, 0, 0.490516,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.274854);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.609208,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431624,-99) , 
2, 0.00673954, 1, 0, 0.543608,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.39428,-99) , 
5, -0.955511, 0, 0, 0.507604,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.179001);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.937711, 1, 1, 0.57504,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.60329,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456316,-99) , 
6, -0.89312, 1, 0, 0.491469,-99) , 
5, 0.581105, 0, 0, 0.519045,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.139607);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.549112, 0, 1, 0.574657,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48089,-99) , 
4, 0.021308, 1, 0, 0.532519,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.215535);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0851998, 0, 1, 0.611466,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527713,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.41235,-99) , 
3, 0.282919, 1, 0, 0.466683,-99) , 
6, -0.559109, 1, 0, 0.513844,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.124264);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.61744,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499678,-99) , 
4, 0.00967872, 1, 0, 0.541255,-99) , 
NN(
0, 
0, 
-1, 0.0957488, 1, -1, 0.450474,-99) , 
6, 0.748563, 1, 0, 0.511296,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.148531);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.592582,-99) , 
NN(
0, 
0, 
-1, 0.829485, 1, -1, 0.457491,-99) , 
5, -0.911022, 1, 0, 0.485384,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.226727);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.57326,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450691,-99) , 
6, -0.859035, 0, 0, 0.543425,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.369484,-99) , 
3, 0.744537, 1, 0, 0.508013,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.150514);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.639229,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498883,-99) , 
6, 0.915098, 1, 0, 0.575823,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510946,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.41805,-99) , 
5, -0.67697, 1, 0, 0.471565,-99) , 
5, 0.526118, 0, 0, 0.507989,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.139439);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0898889, 0, 1, 0.551244,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52275,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.41599,-99) , 
6, -0.59304, 1, 0, 0.477455,-99) , 
6, 0.485628, 0, 0, 0.503825,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.173468);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.630023,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.610802,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473399,-99) , 
6, 0.890022, 0, 0, 0.503076,-99) , 
0, 0.06817, 1, 0, 0.528173,-99)    );
  // itree = 100
  fBoostWeights.push_back(0.223564);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0041673, 1, 1, 0.625567,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.576273,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455447,-99) , 
5, -0.565609, 1, 0, 0.50098,-99) , 
3, 0.424638, 0, 0, 0.541869,-99)    );
  // itree = 101
  fBoostWeights.push_back(0.207489);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.614909,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458439,-99) , 
1, 0.00575924, 1, 0, 0.543342,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440926,-99) , 
5, -0.855786, 0, 0, 0.50752,-99)    );
  // itree = 102
  fBoostWeights.push_back(0.204157);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.467876, 0, 1, 0.575073,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437489,-99) , 
0, 0.0650101, 0, 0, 0.545807,-99)    );
  // itree = 103
  fBoostWeights.push_back(0.139012);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.57136,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516679,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.383624,-99) , 
5, -0.424572, 0, 0, 0.483326,-99) , 
5, -0.83804, 1, 0, 0.506498,-99)    );
  // itree = 104
  fBoostWeights.push_back(0.186209);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.805549, 1, 1, 0.554718,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544284,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414988,-99) , 
5, -0.935516, 1, 0, 0.452251,-99) , 
6, 0.339664, 0, 0, 0.491791,-99)    );
  // itree = 105
  fBoostWeights.push_back(0.15882);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.584047,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519125,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407954,-99) , 
0, 0.0860732, 1, 0, 0.470697,-99) , 
0, 0.115876, 0, 0, 0.489805,-99)    );
  // itree = 106
  fBoostWeights.push_back(0.220758);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.644712,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577835,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438032,-99) , 
5, 0.781055, 0, 0, 0.469101,-99) , 
0, 0.116207, 0, 0, 0.497257,-99)    );
  // itree = 107
  fBoostWeights.push_back(0.179119);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548251,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544252,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425325,-99) , 
0, 0.0664797, 1, 0, 0.449876,-99) , 
6, 0.785548, 0, 0, 0.473171,-99)    );
  // itree = 108
  fBoostWeights.push_back(0.249566);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.631939,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488617,-99) , 
1, -0.00588002, 0, 0, 0.56988,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.393378,-99) , 
5, 0.805549, 1, 0, 0.514333,-99)    );
  // itree = 109
  fBoostWeights.push_back(0.184042);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.579765,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457915,-99) , 
4, 0.0147739, 0, 0, 0.529656,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.432438,-99) , 
0, 0.0743474, 0, 0, 0.49766,-99)    );
  // itree = 110
  fBoostWeights.push_back(0.126506);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.663986,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502006,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422711,-99) , 
3, 0.403099, 1, 0, 0.480521,-99) , 
3, 0.702756, 0, 0, 0.509878,-99)    );
  // itree = 111
  fBoostWeights.push_back(0.238262);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.00695799, 0, 1, 0.583383,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568036,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.404538,-99) , 
3, 0.363852, 0, 0, 0.464344,-99) , 
2, 0.00154026, 1, 0, 0.531125,-99)    );
  // itree = 112
  fBoostWeights.push_back(0.164185);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.614741,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482068,-99) , 
3, 0.460128, 0, 0, 0.520195,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.392878,-99) , 
0, 0.0637462, 0, 0, 0.494017,-99)    );
  // itree = 113
  fBoostWeights.push_back(0.1693);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.62966,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492238,-99) , 
0, 0.0878002, 1, 0, 0.559685,-99) , 
NN(
0, 
0, 
-1, 0.927518, 0, -1, 0.451432,-99) , 
6, 0.62909, 1, 0, 0.517466,-99)    );
  // itree = 114
  fBoostWeights.push_back(0.150738);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.594977,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580984,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461871,-99) , 
4, 0.00484121, 1, 0, 0.483502,-99) , 
6, 0.879529, 0, 0, 0.501033,-99)    );
  // itree = 115
  fBoostWeights.push_back(0.109795);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533031,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473161,-99) , 
0, 0.112657, 1, 0, 0.519607,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.433763,-99) , 
3, 0.670573, 1, 0, 0.501022,-99)    );
  // itree = 116
  fBoostWeights.push_back(0.165749);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.575765,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479331,-99) , 
2, 0.00456449, 1, 0, 0.538752,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509446,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.380894,-99) , 
0, 0.0642841, 1, 0, 0.442494,-99) , 
0, 0.0757437, 0, 0, 0.504063,-99)    );
  // itree = 117
  fBoostWeights.push_back(0.103953);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568878,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500843,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425587,-99) , 
0, 0.0751171, 0, 0, 0.472617,-99) , 
6, 0.838037, 0, 0, 0.493138,-99)    );
  // itree = 118
  fBoostWeights.push_back(0.16194);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.597492,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487845,-99) , 
6, -0.16471, 1, 0, 0.536756,-99) , 
NN(
0, 
0, 
-1, 0.0646048, 1, -1, 0.430193,-99) , 
0, 0.0761154, 0, 0, 0.496723,-99)    );
  // itree = 119
  fBoostWeights.push_back(0.139214);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539386,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454733,-99) , 
3, 0.669828, 1, 0, 0.52102,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.415325,-99) , 
5, -0.950512, 0, 0, 0.499661,-99)    );
  // itree = 120
  fBoostWeights.push_back(0.184421);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.00431659, 1, 1, 0.569156,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542089,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.427459,-99) , 
3, 0.17826, 0, 0, 0.460579,-99) , 
4, 0.00938665, 1, 0, 0.495555,-99)    );
  // itree = 121
  fBoostWeights.push_back(0.183247);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.0337416, 1, 1, 0.55945,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.565442,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421679,-99) , 
2, -0.000790904, 0, 0, 0.486747,-99) , 
3, 0.34316, 1, 0, 0.528098,-99)    );
  // itree = 122
  fBoostWeights.push_back(0.170614);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.58203,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460738,-99) , 
6, -0.886969, 0, 0, 0.540999,-99) , 
NN(
0, 
0, 
-1, 0.926518, 1, -1, 0.453126,-99) , 
6, 0.719566, 1, 0, 0.511569,-99)    );
  // itree = 123
  fBoostWeights.push_back(0.167328);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.681072,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487135,-99) , 
2, -0.00476721, 0, 0, 0.591167,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467957,-99) , 
4, 0.0121358, 1, 0, 0.51553,-99)    );
  // itree = 124
  fBoostWeights.push_back(0.147791);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551113,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.571367,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453399,-99) , 
3, 0.702581, 0, 0, 0.487691,-99) , 
3, 0.164956, 1, 0, 0.516309,-99)    );
  // itree = 125
  fBoostWeights.push_back(0.201219);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.630998,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547417,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439178,-99) , 
5, 0.928018, 0, 0, 0.461611,-99) , 
6, -0.844538, 1, 0, 0.492558,-99)    );
  // itree = 126
  fBoostWeights.push_back(0.204608);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.567806,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443488,-99) , 
5, 0.817046, 1, 0, 0.530464,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.389997,-99) , 
0, 0.0634007, 0, 0, 0.50537,-99)    );
  // itree = 127
  fBoostWeights.push_back(0.143726);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.529867, 0, 1, 0.56095,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479697,-99) , 
6, 0.868013, 1, 0, 0.541362,-99)    );
  // itree = 128
  fBoostWeights.push_back(0.132512);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562964,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519792,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44294,-99) , 
6, -0.204706, 1, 0, 0.477394,-99) , 
3, 0.453134, 0, 0, 0.503252,-99)    );
  // itree = 129
  fBoostWeights.push_back(0.121427);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.566765,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512092,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447367,-99) , 
4, 0.00995625, 1, 0, 0.474174,-99) , 
0, 0.10835, 0, 0, 0.496381,-99)    );
  // itree = 130
  fBoostWeights.push_back(0.171864);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.162326, 1, 1, 0.551544,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.418996,-99) , 
6, -0.763554, 0, 0, 0.508667,-99)    );
  // itree = 131
  fBoostWeights.push_back(0.121683);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.611674,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518115,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441767,-99) , 
1, -0.00213677, 0, 0, 0.494513,-99) , 
6, -0.913523, 1, 0, 0.513039,-99)    );
  // itree = 132
  fBoostWeights.push_back(0.199683);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.620909,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543325,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435958,-99) , 
0, 0.0675921, 1, 0, 0.462613,-99) , 
0, 0.111721, 0, 0, 0.493086,-99)    );
  // itree = 133
  fBoostWeights.push_back(0.199177);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.571532,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.432886,-99) , 
6, 0.936866, 1, 0, 0.535764,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428759,-99) , 
6, -0.817296, 0, 0, 0.502195,-99)    );
  // itree = 134
  fBoostWeights.push_back(0.138242);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528424,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437449,-99) , 
0, 0.0635094, 0, 0, 0.510725,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.403886,-99) , 
0, 0.116564, 1, 0, 0.485964,-99)    );
  // itree = 135
  fBoostWeights.push_back(0.177172);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.574259,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465267,-99) , 
6, 0.730564, 0, 0, 0.495598,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.391128,-99) , 
3, 0.583832, 1, 0, 0.467127,-99)    );
  // itree = 136
  fBoostWeights.push_back(0.145763);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.616145,-99) , 
NN(
0, 
0, 
-1, 0.282951, 1, -1, 0.464344,-99) , 
3, 0.5866, 0, 0, 0.494925,-99)    );
  // itree = 137
  fBoostWeights.push_back(0.173741);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.650108,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468049,-99) , 
5, -0.927269, 0, 0, 0.557412,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518215,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422188,-99) , 
5, 0.419145, 0, 0, 0.48503,-99) , 
6, -0.264684, 1, 0, 0.517477,-99)    );
  // itree = 138
  fBoostWeights.push_back(0.11976);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.575407,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50571,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424892,-99) , 
5, 0.916521, 1, 0, 0.479592,-99) , 
6, -0.659084, 1, 0, 0.509045,-99)    );
  // itree = 139
  fBoostWeights.push_back(0.187188);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.587892,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521835,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.337645,-99) , 
3, 0.274278, 1, 0, 0.474991,-99) , 
3, 0.432637, 0, 0, 0.508078,-99)    );
  // itree = 140
  fBoostWeights.push_back(0.181326);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515187,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424176,-99) , 
0, 0.105414, 1, 0, 0.479817,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.371956,-99) , 
0, 0.0704276, 0, 0, 0.448836,-99)    );
  // itree = 141
  fBoostWeights.push_back(0.16163);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.613157,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50584,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425351,-99) , 
6, -0.62111, 1, 0, 0.45889,-99) , 
5, 0.906523, 0, 0, 0.48528,-99)    );
  // itree = 142
  fBoostWeights.push_back(0.148229);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562142,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502226,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.405588,-99) , 
0, 0.0803753, 1, 0, 0.452228,-99) , 
0, 0.107225, 0, 0, 0.477598,-99)    );
  // itree = 143
  fBoostWeights.push_back(0.159898);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.31491, 1, 1, 0.563946,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455013,-99) , 
2, -0.00614393, 0, 0, 0.523227,-99)    );
  // itree = 144
  fBoostWeights.push_back(0.212756);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0871402, 1, 1, 0.585023,-99) , 
NN(
0, 
0, 
-1, 0.913246, 1, -1, 0.42892,-99) , 
5, -0.753062, 1, 0, 0.477332,-99)    );
  // itree = 145
  fBoostWeights.push_back(0.183132);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.574204,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482092,-99) , 
4, 0.0193746, 1, 0, 0.520072,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.34901,-99) , 
3, 0.695259, 1, 0, 0.482841,-99)    );
  // itree = 146
  fBoostWeights.push_back(0.224184);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.585474,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461285,-99) , 
2, -0.00210454, 0, 0, 0.523782,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531401,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.382982,-99) , 
5, -0.753062, 1, 0, 0.430773,-99) , 
0, 0.0956256, 0, 0, 0.465172,-99)    );
  // itree = 147
  fBoostWeights.push_back(0.256561);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.674738,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450786,-99) , 
3, 0.688138, 1, 0, 0.576608,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436377,-99) , 
3, 0.168699, 0, 0, 0.503835,-99)    );
  // itree = 148
  fBoostWeights.push_back(0.144576);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.595513,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478406,-99) , 
1, 0.00590371, 1, 0, 0.541476,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466458,-99) , 
2, -0.00674117, 0, 0, 0.514679,-99)    );
  // itree = 149
  fBoostWeights.push_back(0.151049);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.671297,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481059,-99) , 
0, 0.0878592, 1, 0, 0.562299,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514717,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430964,-99) , 
6, 0.490705, 0, 0, 0.488465,-99) , 
6, -0.258185, 1, 0, 0.519539,-99)    );
  // itree = 150
  fBoostWeights.push_back(0.158013);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.104416, 0, 1, 0.556349,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444088,-99) , 
2, 0.00550155, 1, 0, 0.516809,-99)    );
  // itree = 151
  fBoostWeights.push_back(0.17318);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.652086,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476343,-99) , 
4, 0.0172949, 1, 0, 0.52782,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500973,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.378726,-99) , 
1, 0.00094191, 1, 0, 0.438842,-99) , 
3, 0.50012, 1, 0, 0.500127,-99)    );
  // itree = 152
  fBoostWeights.push_back(0.177026);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.262695, 0, 1, 0.551409,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562542,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.420663,-99) , 
4, 0.00809105, 1, 0, 0.471699,-99) , 
0, 0.0884474, 0, 0, 0.509601,-99)    );
  // itree = 153
  fBoostWeights.push_back(0.20638);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.635079,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52102,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.405411,-99) , 
6, -0.249605, 1, 0, 0.472556,-99) , 
5, 0.76006, 0, 0, 0.514188,-99)    );
  // itree = 154
  fBoostWeights.push_back(0.205328);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.609286,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49005,-99) , 
2, -0.00568882, 0, 0, 0.544622,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.39527,-99) , 
1, 0.00619339, 1, 0, 0.491939,-99)    );
  // itree = 155
  fBoostWeights.push_back(0.156891);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.927371, 0, 1, 0.583638,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503435,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.382802,-99) , 
5, -0.52714, 1, 0, 0.466963,-99) , 
5, 0.276931, 0, 0, 0.51273,-99)    );
  // itree = 156
  fBoostWeights.push_back(0.167221);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.128218, 0, 1, 0.568443,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463206,-99) , 
4, 0.00651319, 0, 0, 0.538505,-99)    );
  // itree = 157
  fBoostWeights.push_back(0.146027);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.624096,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495851,-99) , 
6, 0.160811, 0, 0, 0.537528,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.409556,-99) , 
6, 0.936001, 1, 0, 0.513631,-99)    );
  // itree = 158
  fBoostWeights.push_back(0.1061);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549931,-99) , 
NN(
0, 
0, 
-1, 0.335065, 1, -1, 0.464955,-99) , 
4, 0.00483978, 1, 0, 0.480796,-99)    );
  // itree = 159
  fBoostWeights.push_back(0.199612);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.594566,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54178,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422258,-99) , 
0, 0.0880727, 0, 0, 0.476824,-99) , 
5, -0.868033, 1, 0, 0.510425,-99)    );
  // itree = 160
  fBoostWeights.push_back(0.140284);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.602132,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536988,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455627,-99) , 
2, -0.00137428, 0, 0, 0.503564,-99) , 
6, -0.903523, 1, 0, 0.519295,-99)    );
  // itree = 161
  fBoostWeights.push_back(0.177772);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.612211,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47135,-99) , 
1, -0.00516516, 0, 0, 0.52753,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512787,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.404568,-99) , 
5, 0.927519, 0, 0, 0.444853,-99) , 
1, 0.00237674, 1, 0, 0.491451,-99)    );
  // itree = 162
  fBoostWeights.push_back(0.139608);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556778,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479998,-99) , 
5, -0.23994, 1, 0, 0.515552,-99) , 
NN(
0, 
0, 
-1, -0.00974756, 0, -1, 0.432211,-99) , 
3, 0.354157, 1, 0, 0.481238,-99)    );
  // itree = 163
  fBoostWeights.push_back(0.176488);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.897911, 1, 1, 0.58163,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522621,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.379609,-99) , 
5, -0.478252, 1, 0, 0.479604,-99) , 
5, 0.419145, 0, 0, 0.516382,-99)    );
  // itree = 164
  fBoostWeights.push_back(0.164688);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56401,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477535,-99) , 
0, 0.111695, 1, 0, 0.541932,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424904,-99) , 
5, -0.943764, 0, 0, 0.514179,-99)    );
  // itree = 165
  fBoostWeights.push_back(0.167402);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.593666,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55955,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457141,-99) , 
6, -0.679836, 1, 0, 0.489704,-99) , 
3, 0.512111, 0, 0, 0.515608,-99)    );
  // itree = 166
  fBoostWeights.push_back(0.183351);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.150462, 0, 1, 0.569005,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445045,-99) , 
3, 0.558099, 1, 0, 0.53465,-99)    );
  // itree = 167
  fBoostWeights.push_back(0.191887);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.585521,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48986,-99) , 
5, -0.23969, 1, 0, 0.530733,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545642,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.350461,-99) , 
4, 0.0040543, 1, 0, 0.428299,-99) , 
3, 0.405634, 1, 0, 0.49061,-99)    );
  // itree = 168
  fBoostWeights.push_back(0.16599);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5505,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513719,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.351929,-99) , 
3, 0.4263, 0, 0, 0.449239,-99) , 
3, 0.208447, 1, 0, 0.49912,-99)    );
  // itree = 169
  fBoostWeights.push_back(0.176887);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.576928,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47792,-99) , 
5, -0.466633, 0, 0, 0.535151,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518739,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.359226,-99) , 
6, 0.602102, 1, 0, 0.444366,-99) , 
3, 0.361386, 1, 0, 0.497532,-99)    );
  // itree = 170
  fBoostWeights.push_back(0.195054);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.588659,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472824,-99) , 
6, 0.830542, 1, 0, 0.537993,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.419679,-99) , 
2, -0.00581424, 0, 0, 0.490497,-99)    );
  // itree = 171
  fBoostWeights.push_back(0.165386);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.622079,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494679,-99) , 
3, 0.131586, 0, 0, 0.529075,-99) , 
NN(
0, 
0, 
-1, 0.12272, 0, -1, 0.408913,-99) , 
3, 0.403134, 1, 0, 0.480453,-99)    );
  // itree = 172
  fBoostWeights.push_back(0.174513);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.57582,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550365,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439933,-99) , 
3, 0.297174, 0, 0, 0.483746,-99) , 
6, 0.731064, 0, 0, 0.51093,-99)    );
  // itree = 173
  fBoostWeights.push_back(0.152596);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.579586,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54824,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451299,-99) , 
5, -0.825044, 1, 0, 0.478809,-99) , 
3, 0.613593, 0, 0, 0.497374,-99)    );
  // itree = 174
  fBoostWeights.push_back(0.179719);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.499629, 1, 1, 0.547108,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.37818,-99) , 
3, 0.692026, 1, 0, 0.509287,-99)    );
  // itree = 175
  fBoostWeights.push_back(0.125493);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.611716,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514681,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436088,-99) , 
5, -0.941015, 0, 0, 0.490505,-99) , 
6, 0.890027, 0, 0, 0.512522,-99)    );
  // itree = 176
  fBoostWeights.push_back(0.204928);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.595547,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466967,-99) , 
6, 0.918709, 1, 0, 0.527786,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516394,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.390379,-99) , 
0, 0.0968224, 0, 0, 0.434115,-99) , 
5, 0.644589, 0, 0, 0.463464,-99)    );
  // itree = 177
  fBoostWeights.push_back(0.125945);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.573397,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51387,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.408181,-99) , 
5, -0.466536, 0, 0, 0.484328,-99) , 
5, -0.917521, 1, 0, 0.506045,-99)    );
  // itree = 178
  fBoostWeights.push_back(0.189991);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.596018,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487751,-99) , 
1, -0.00599561, 0, 0, 0.549519,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.413323,-99) , 
5, 0.872532, 1, 0, 0.511684,-99)    );
  // itree = 179
  fBoostWeights.push_back(0.189511);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.583475,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560139,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434648,-99) , 
6, 0.932298, 0, 0, 0.457176,-99) , 
6, -0.894276, 1, 0, 0.4761,-99)    );
  // itree = 180
  fBoostWeights.push_back(0.109741);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557372,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507065,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425031,-99) , 
4, 0.0147739, 0, 0, 0.473762,-99) , 
0, 0.0673141, 1, 0, 0.490238,-99)    );
  // itree = 181
  fBoostWeights.push_back(0.143643);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.603335,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477384,-99) , 
3, 0.475898, 1, 0, 0.52448,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450436,-99) , 
3, 0.178949, 0, 0, 0.486099,-99)    );
  // itree = 182
  fBoostWeights.push_back(0.197762);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.659696,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471202,-99) , 
0, 0.0878592, 1, 0, 0.560029,-99) , 
NN(
0, 
0, 
-1, 0.0779775, 0, -1, 0.444611,-99) , 
6, -0.177704, 1, 0, 0.493201,-99)    );
  // itree = 183
  fBoostWeights.push_back(0.198132);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0202265, 1, 1, 0.573934,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448615,-99) , 
0, 0.063379, 0, 0, 0.553699,-99)    );
  // itree = 184
  fBoostWeights.push_back(0.213888);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562299,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539584,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.408812,-99) , 
6, 0.874595, 0, 0, 0.440942,-99) , 
5, -0.957511, 1, 0, 0.461224,-99)    );
  // itree = 185
  fBoostWeights.push_back(0.16163);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.589553,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495217,-99) , 
2, 0.00676485, 1, 0, 0.55151,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436449,-99) , 
5, -0.942514, 0, 0, 0.521947,-99)    );
  // itree = 186
  fBoostWeights.push_back(0.191537);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568901,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466965,-99) , 
0, 0.114019, 1, 0, 0.542123,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417125,-99) , 
5, -0.831042, 0, 0, 0.496691,-99)    );
  // itree = 187
  fBoostWeights.push_back(0.218217);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.690071,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476013,-99) , 
1, 0.00523471, 1, 0, 0.567827,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449848,-99) , 
1, -0.00458777, 0, 0, 0.520934,-99)    );
  // itree = 188
  fBoostWeights.push_back(0.187248);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.690118,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562543,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472396,-99) , 
4, 0.0121355, 1, 0, 0.510138,-99) , 
0, 0.117176, 0, 0, 0.539646,-99)    );
  // itree = 189
  fBoostWeights.push_back(0.131331);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0.0660868, 1, 1, 0.546767,-99)    );
  // itree = 190
  fBoostWeights.push_back(0.102522);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.579069,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499541,-99) , 
6, -0.564383, 1, 0, 0.528701,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505222,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.409319,-99) , 
3, 0.727479, 0, 0, 0.454006,-99) , 
3, 0.449612, 1, 0, 0.503544,-99)    );
  // itree = 191
  fBoostWeights.push_back(0.143945);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546552,-99) , 
NN(
0, 
0, 
-1, -0.251187, 1, -1, 0.443287,-99) , 
4, 0.0128566, 0, 0, 0.499022,-99)    );
  // itree = 192
  fBoostWeights.push_back(0.159511);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.59372,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49174,-99) , 
0, 0.0731851, 0, 0, 0.559064,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519766,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439315,-99) , 
6, -0.921297, 1, 0, 0.470761,-99) , 
6, -0.627095, 0, 0, 0.52392,-99)    );
  // itree = 193
  fBoostWeights.push_back(0.158382);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.777832, 0, 1, 0.543696,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.408894,-99) , 
5, -0.935516, 0, 0, 0.507787,-99)    );
  // itree = 194
  fBoostWeights.push_back(0.158149);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.599989,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479216,-99) , 
6, -0.724515, 1, 0, 0.515023,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.392656,-99) , 
0, 0.0637576, 0, 0, 0.491791,-99)    );
  // itree = 195
  fBoostWeights.push_back(0.176437);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577608,-99) , 
NN(
0, 
0, 
-1, 0.283062, 1, -1, 0.439771,-99) , 
3, 0.710068, 0, 0, 0.459221,-99)    );
  // itree = 196
  fBoostWeights.push_back(0.174631);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.61087,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546702,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453059,-99) , 
5, 0.858916, 0, 0, 0.481427,-99) , 
5, -0.894276, 1, 0, 0.512125,-99)    );
  // itree = 197
  fBoostWeights.push_back(0.135628);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0.020226, 1, 1, 0.548288,-99)    );
  // itree = 198
  fBoostWeights.push_back(0.131496);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.629981,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516171,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441122,-99) , 
5, 0.75856, 1, 0, 0.490685,-99) , 
4, 0.00483942, 1, 0, 0.51334,-99)    );
  // itree = 199
  fBoostWeights.push_back(0.193575);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0927758, 1, 1, 0.575668,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.58138,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43892,-99) , 
3, 0.5686, 0, 0, 0.4694,-99) , 
5, 0.689578, 0, 0, 0.503352,-99)    );
  // itree = 200
  fBoostWeights.push_back(0.117395);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.662602,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498655,-99) , 
3, 0.348408, 1, 0, 0.553081,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471294,-99) , 
4, 0.0193577, 1, 0, 0.512301,-99)    );
  // itree = 201
  fBoostWeights.push_back(0.129883);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.634091, 1, 1, 0.541865,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436902,-99) , 
6, -0.88053, 0, 0, 0.520168,-99)    );
  // itree = 202
  fBoostWeights.push_back(0.112582);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.593405,-99) , 
NN(
0, 
0, 
-1, 0.681074, 1, -1, 0.470991,-99) , 
6, 0.890012, 0, 0, 0.492117,-99)    );
  // itree = 203
  fBoostWeights.push_back(0.19385);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.867327, 0, 1, 0.548756,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.391886,-99) , 
5, 0.805549, 1, 0, 0.495801,-99)    );
  // itree = 204
  fBoostWeights.push_back(0.177345);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.591561,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516388,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422817,-99) , 
6, -0.664553, 1, 0, 0.453497,-99) , 
0, 0.0664198, 1, 0, 0.476638,-99)    );
  // itree = 205
  fBoostWeights.push_back(0.176595);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554887,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480792,-99) , 
3, 0.541836, 1, 0, 0.535218,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518016,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.365491,-99) , 
6, -0.887311, 1, 0, 0.428185,-99) , 
6, -0.558609, 0, 0, 0.490228,-99)    );
  // itree = 206
  fBoostWeights.push_back(0.182885);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.57409,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466682,-99) , 
5, -0.227301, 1, 0, 0.491236,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.393962,-99) , 
5, -0.822794, 0, 0, 0.457008,-99)    );
  // itree = 207
  fBoostWeights.push_back(0.174929);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.933517, 1, 1, 0.588409,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480222,-99) , 
2, -0.00653886, 0, 0, 0.547018,-99)    );
  // itree = 208
  fBoostWeights.push_back(0.171416);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.632976,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497079,-99) , 
6, -0.799754, 0, 0, 0.546752,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513188,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.391125,-99) , 
0, 0.0853669, 1, 0, 0.443011,-99) , 
5, -0.47913, 1, 0, 0.485606,-99)    );
  // itree = 209
  fBoostWeights.push_back(0.190455);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.922507, 1, 1, 0.571935,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542828,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.411133,-99) , 
3, 0.275429, 1, 0, 0.478008,-99) , 
5, 0.52062, 0, 0, 0.508821,-99)    );
  // itree = 210
  fBoostWeights.push_back(0.144271);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558525,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478485,-99) , 
6, -0.557222, 0, 0, 0.507499,-99) , 
NN(
0, 
0, 
-1, 0.931707, 0, -1, 0.42116,-99) , 
6, 0.609598, 1, 0, 0.475226,-99)    );
  // itree = 211
  fBoostWeights.push_back(0.16354);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.595887,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549734,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44898,-99) , 
6, -0.258162, 1, 0, 0.502704,-99) , 
5, 0.908023, 0, 0, 0.518677,-99)    );
  // itree = 212
  fBoostWeights.push_back(0.189603);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0879199, 0, 1, 0.586541,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551602,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436674,-99) , 
3, 0.353609, 1, 0, 0.500685,-99) , 
5, 0.496876, 0, 0, 0.531017,-99)    );
  // itree = 213
  fBoostWeights.push_back(0.205554);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.633512,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.574653,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446555,-99) , 
3, 0.322146, 0, 0, 0.492611,-99) , 
6, -0.905522, 1, 0, 0.515599,-99)    );
  // itree = 214
  fBoostWeights.push_back(0.116205);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.407609, 0, 1, 0.531312,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.411415,-99) , 
3, 0.738311, 1, 0, 0.51018,-99)    );
  // itree = 215
  fBoostWeights.push_back(0.232665);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.596229,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461444,-99) , 
6, -0.848544, 0, 0, 0.53901,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.399133,-99) , 
2, 0.00465442, 1, 0, 0.488134,-99)    );
  // itree = 216
  fBoostWeights.push_back(0.180391);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.621694,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541901,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.403204,-99) , 
5, 0.808048, 1, 0, 0.513518,-99) , 
6, 0.926516, 0, 0, 0.530773,-99)    );
  // itree = 217
  fBoostWeights.push_back(0.128962);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549396,-99) , 
NN(
0, 
0, 
-1, 0.332831, 1, -1, 0.455439,-99) , 
3, 0.488871, 0, 0, 0.481998,-99)    );
  // itree = 218
  fBoostWeights.push_back(0.128197);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.68613,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488038,-99) , 
3, 0.268679, 1, 0, 0.543986,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472487,-99) , 
4, 0.0216948, 1, 0, 0.511051,-99)    );
  // itree = 219
  fBoostWeights.push_back(0.122096);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.611266,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487633,-99) , 
6, -0.700157, 1, 0, 0.511472,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.400266,-99) , 
6, -0.920519, 0, 0, 0.491837,-99)    );
  // itree = 220
  fBoostWeights.push_back(0.130317);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.01096, 1, 1, 0.549787,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464054,-99) , 
3, 0.595592, 1, 0, 0.528857,-99)    );
  // itree = 221
  fBoostWeights.push_back(0.154955);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.636706,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487914,-99) , 
3, 0.690318, 1, 0, 0.576301,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472332,-99) , 
4, 0.0193573, 1, 0, 0.521159,-99)    );
  // itree = 222
  fBoostWeights.push_back(0.167905);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.63591,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.58302,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481302,-99) , 
3, 0.514344, 0, 0, 0.505878,-99) , 
5, -0.88053, 1, 0, 0.538416,-99)    );
  // itree = 223
  fBoostWeights.push_back(0.18559);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.640755,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.563225,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466321,-99) , 
3, 0.137696, 1, 0, 0.519566,-99) , 
3, 0.621841, 0, 0, 0.540889,-99)    );
  // itree = 224
  fBoostWeights.push_back(0.196302);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.599488,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556641,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44178,-99) , 
5, -0.95901, 1, 0, 0.470006,-99) , 
2, 0.0053123, 0, 0, 0.506747,-99)    );
  // itree = 225
  fBoostWeights.push_back(0.232344);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.907694, 1, 1, 0.599396,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.585268,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439773,-99) , 
6, -0.683622, 1, 0, 0.507091,-99) , 
5, 0.529868, 0, 0, 0.541939,-99)    );
  // itree = 226
  fBoostWeights.push_back(0.200141);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556344,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461269,-99) , 
3, 0.486625, 1, 0, 0.526619,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.373791,-99) , 
5, 0.886028, 1, 0, 0.485744,-99)    );
  // itree = 227
  fBoostWeights.push_back(0.159904);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.617493,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.570324,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466783,-99) , 
0, 0.107696, 0, 0, 0.494765,-99) , 
4, 0.00483942, 1, 0, 0.517272,-99)    );
  // itree = 228
  fBoostWeights.push_back(0.132397);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.341127, 0, 1, 0.543835,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44117,-99) , 
0, 0.116207, 1, 0, 0.521181,-99)    );
  // itree = 229
  fBoostWeights.push_back(0.158766);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.623266,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463231,-99) , 
5, -0.855786, 0, 0, 0.566665,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476973,-99) , 
4, 0.0196022, 1, 0, 0.520029,-99)    );
  // itree = 230
  fBoostWeights.push_back(0.157599);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.574072,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491862,-99) , 
5, -0.935016, 0, 0, 0.552386,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447069,-99) , 
0, 0.0633965, 0, 0, 0.534674,-99)    );
  // itree = 231
  fBoostWeights.push_back(0.161732);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.593148,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498136,-99) , 
0, 0.105339, 0, 0, 0.532669,-99) , 
NN(
0, 
0, 
-1, -0.0144964, 1, -1, 0.400546,-99) , 
0, 0.0745843, 0, 0, 0.48659,-99)    );
  // itree = 232
  fBoostWeights.push_back(0.148289);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.581955,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530222,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417055,-99) , 
5, 0.123819, 1, 0, 0.502976,-99) , 
5, 0.767558, 0, 0, 0.522897,-99)    );
  // itree = 233
  fBoostWeights.push_back(0.159528);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.64208,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49007,-99) , 
6, -0.82501, 1, 0, 0.525968,-99) , 
NN(
0, 
0, 
-1, -0.0202681, 0, -1, 0.413502,-99) , 
0, 0.0747564, 0, 0, 0.487311,-99)    );
  // itree = 234
  fBoostWeights.push_back(0.17122);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.672943,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487086,-99) , 
2, 0.00474846, 1, 0, 0.545851,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542414,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425228,-99) , 
6, -0.78115, 1, 0, 0.48528,-99) , 
6, -0.0337416, 0, 0, 0.515511,-99)    );
  // itree = 235
  fBoostWeights.push_back(0.269872);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.093477, 1, 1, 0.634398,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53203,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480503,-99) , 
5, -0.911024, 1, 0, 0.507701,-99) , 
6, -0.661584, 0, 0, 0.588543,-99)    );
  // itree = 236
  fBoostWeights.push_back(0.207861);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.599567,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558745,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.427061,-99) , 
6, -0.227691, 1, 0, 0.506134,-99) , 
5, 0.766308, 0, 0, 0.530799,-99)    );
  // itree = 237
  fBoostWeights.push_back(0.126351);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.602989,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522882,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4182,-99) , 
0, 0.101016, 1, 0, 0.502188,-99) , 
0, 0.11776, 0, 0, 0.517609,-99)    );
  // itree = 238
  fBoostWeights.push_back(0.232384);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.592573,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447132,-99) , 
5, 0.87903, 1, 0, 0.529049,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.408094,-99) , 
2, -0.0056434, 0, 0, 0.478206,-99)    );
  // itree = 239
  fBoostWeights.push_back(0.142584);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.592574,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493008,-99) , 
3, 0.297149, 0, 0, 0.531499,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407667,-99) , 
0, 0.0650101, 0, 0, 0.506213,-99)    );
  // itree = 240
  fBoostWeights.push_back(0.21736);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0991228, 0, 1, 0.577524,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425669,-99) , 
0, 0.125437, 1, 0, 0.553129,-99)    );
  // itree = 241
  fBoostWeights.push_back(0.124808);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.571841,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477967,-99) , 
5, -0.308673, 1, 0, 0.522162,-99) , 
NN(
0, 
0, 
-1, 0.102803, 0, -1, 0.456476,-99) , 
0, 0.0866802, 1, 0, 0.487767,-99)    );
  // itree = 242
  fBoostWeights.push_back(0.170469);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542692,-99) , 
NN(
0, 
0, 
-1, -0.858535, 0, -1, 0.423917,-99) , 
4, 0.0172949, 0, 0, 0.479054,-99)    );
  // itree = 243
  fBoostWeights.push_back(0.178441);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.426263, 1, 1, 0.542151,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.377301,-99) , 
5, -0.941015, 0, 0, 0.49869,-99)    );
  // itree = 244
  fBoostWeights.push_back(0.153148);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.677304,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486037,-99) , 
3, 0.375393, 0, 0, 0.526706,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417211,-99) , 
3, 0.74106, 1, 0, 0.508128,-99)    );
  // itree = 245
  fBoostWeights.push_back(0.112646);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.592175,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496967,-99) , 
0, 0.0680614, 1, 0, 0.521906,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.411864,-99) , 
0, 0.116476, 1, 0, 0.497384,-99)    );
  // itree = 246
  fBoostWeights.push_back(0.138411);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.00113771, 0, 1, 0.596215,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497756,-99) , 
4, 0.0216024, 1, 0, 0.54703,-99)    );
  // itree = 247
  fBoostWeights.push_back(0.204372);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.00874781, 1, 1, 0.616219,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556109,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460014,-99) , 
0, 0.0825501, 1, 0, 0.521561,-99) , 
0, 0.0985947, 0, 0, 0.553393,-99)    );
  // itree = 248
  fBoostWeights.push_back(0.149686);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.10766, 1, 1, 0.565224,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502251,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.410156,-99) , 
0, 0.0719119, 1, 0, 0.463188,-99) , 
0, 0.0826118, 0, 0, 0.517931,-99)    );
  // itree = 249
  fBoostWeights.push_back(0.111666);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568728,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512042,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.420945,-99) , 
0, 0.0925939, 1, 0, 0.481726,-99) , 
0, 0.12066, 0, 0, 0.495525,-99)    );
  // itree = 250
  fBoostWeights.push_back(0.182522);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562439,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462168,-99) , 
0, 0.0745373, 0, 0, 0.528546,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.39417,-99) , 
5, 0.927018, 1, 0, 0.500745,-99)    );
  // itree = 251
  fBoostWeights.push_back(0.153844);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.600923,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493472,-99) , 
6, 0.873933, 1, 0, 0.546945,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544126,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439978,-99) , 
6, -0.908623, 1, 0, 0.46852,-99) , 
6, 0.160712, 0, 0, 0.502682,-99)    );
  // itree = 252
  fBoostWeights.push_back(0.212763);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.579551,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491842,-99) , 
0, 0.101007, 1, 0, 0.546538,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548276,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.394495,-99) , 
3, 0.489117, 0, 0, 0.432944,-99) , 
5, 0.0707323, 0, 0, 0.479509,-99)    );
  // itree = 253
  fBoostWeights.push_back(0.171454);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.627513,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502168,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.398908,-99) , 
3, 0.280926, 1, 0, 0.45301,-99) , 
6, 0.90802, 0, 0, 0.47903,-99)    );
  // itree = 254
  fBoostWeights.push_back(0.168808);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0109502, 0, 1, 0.5604,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440373,-99) , 
3, 0.143458, 0, 0, 0.497958,-99)    );
  // itree = 255
  fBoostWeights.push_back(0.17182);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.617106,-99) , 
NN(
0, 
0, 
-1, 0.456722, 1, -1, 0.453956,-99) , 
6, 0.83804, 0, 0, 0.488425,-99)    );
  // itree = 256
  fBoostWeights.push_back(0.129046);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.446638, 0, 1, 0.533892,-99) , 
NN(
0, 
0, 
-1, 0.555651, 0, -1, 0.435712,-99) , 
3, 0.371652, 1, 0, 0.494919,-99)    );
  // itree = 257
  fBoostWeights.push_back(0.112379);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.455636, 1, 1, 0.541506,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503204,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414237,-99) , 
1, 0.0018806, 1, 0, 0.465892,-99) , 
3, 0.386649, 1, 0, 0.511562,-99)    );
  // itree = 258
  fBoostWeights.push_back(0.206171);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0908466, 1, 1, 0.570863,-99) , 
NN(
0, 
0, 
-1, -0.0602349, 1, -1, 0.423526,-99) , 
0, 0.0772819, 0, 0, 0.511992,-99)    );
  // itree = 259
  fBoostWeights.push_back(0.153086);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.667508,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478637,-99) , 
2, -0.00100255, 1, 0, 0.561969,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468788,-99) , 
3, 0.231677, 0, 0, 0.508434,-99)    );
  // itree = 260
  fBoostWeights.push_back(0.161073);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0806396, 0, 1, 0.595936,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511178,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425361,-99) , 
5, -0.557111, 0, 0, 0.472774,-99) , 
3, 0.389138, 0, 0, 0.511446,-99)    );
  // itree = 261
  fBoostWeights.push_back(0.110591);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580523,-99) , 
NN(
0, 
0, 
-1, 0.386887, 1, -1, 0.470273,-99) , 
3, 0.59583, 0, 0, 0.491299,-99)    );
  // itree = 262
  fBoostWeights.push_back(0.102909);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.583431,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506367,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417905,-99) , 
6, 0.644536, 1, 0, 0.480855,-99) , 
5, 0.946513, 0, 0, 0.496608,-99)    );
  // itree = 263
  fBoostWeights.push_back(0.171627);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.641503,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469872,-99) , 
4, 0.0109393, 0, 0, 0.526679,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444356,-99) , 
3, 0.178683, 0, 0, 0.483144,-99)    );
  // itree = 264
  fBoostWeights.push_back(0.178032);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0517814, 1, 1, 0.592115,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.599356,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479353,-99) , 
6, 0.777554, 0, 0, 0.517448,-99) , 
0, 0.0814878, 1, 0, 0.545734,-99)    );
  // itree = 265
  fBoostWeights.push_back(0.187787);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.630684,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559701,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448905,-99) , 
3, 0.176205, 1, 0, 0.502042,-99) , 
6, -0.893025, 1, 0, 0.521553,-99)    );
  // itree = 266
  fBoostWeights.push_back(0.124268);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568347,-99) , 
NN(
0, 
0, 
-1, -0.453773, 0, -1, 0.465897,-99) , 
5, -0.824544, 1, 0, 0.496299,-99)    );
  // itree = 267
  fBoostWeights.push_back(0.164749);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.646889,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523623,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424396,-99) , 
6, -0.803551, 0, 0, 0.49353,-99) , 
0, 0.112073, 0, 0, 0.520893,-99)    );
  // itree = 268
  fBoostWeights.push_back(0.161566);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.581086,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475705,-99) , 
6, -0.772061, 1, 0, 0.499405,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.387032,-99) , 
3, 0.568354, 1, 0, 0.469231,-99)    );
  // itree = 269
  fBoostWeights.push_back(0.145502);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.299795, 0, 1, 0.554309,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45575,-99) , 
3, 0.612338, 1, 0, 0.529521,-99)    );
  // itree = 270
  fBoostWeights.push_back(0.215672);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.587359,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440882,-99) , 
1, 0.0037954, 1, 0, 0.498126,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.41138,-99) , 
1, -0.00545011, 0, 0, 0.468684,-99)    );
  // itree = 271
  fBoostWeights.push_back(0.163145);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577217,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547132,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447076,-99) , 
5, -0.698075, 1, 0, 0.482125,-99) , 
4, 0.00761432, 1, 0, 0.507807,-99)    );
  // itree = 272
  fBoostWeights.push_back(0.193159);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.218686, 0, 1, 0.569305,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43472,-99) , 
0, 0.0633347, 0, 0, 0.544085,-99)    );
  // itree = 273
  fBoostWeights.push_back(0.158931);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.710766,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491761,-99) , 
5, 0.957191, 1, 0, 0.604502,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548011,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475378,-99) , 
6, -0.116687, 0, 0, 0.495834,-99) , 
5, 0.645339, 0, 0, 0.529668,-99)    );
  // itree = 274
  fBoostWeights.push_back(0.114816);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577362,-99) , 
NN(
0, 
0, 
-1, 0.0951543, 1, -1, 0.46852,-99) , 
0, 0.109613, 0, 0, 0.4909,-99)    );
  // itree = 275
  fBoostWeights.push_back(0.139436);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.60767,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511493,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440793,-99) , 
0, 0.102034, 1, 0, 0.487164,-99) , 
3, 0.451581, 0, 0, 0.519985,-99)    );
  // itree = 276
  fBoostWeights.push_back(0.120884);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.597261,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502985,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.396095,-99) , 
3, 0.348125, 1, 0, 0.4793,-99) , 
4, 0.00738777, 1, 0, 0.508363,-99)    );
  // itree = 277
  fBoostWeights.push_back(0.190523);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.860035, 0, 1, 0.549038,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.378669,-99) , 
6, -0.869536, 0, 0, 0.505229,-99)    );
  // itree = 278
  fBoostWeights.push_back(0.149293);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.693484,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495799,-99) , 
5, -0.634091, 1, 0, 0.567305,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464196,-99) , 
3, 0.149457, 0, 0, 0.512623,-99)    );
  // itree = 279
  fBoostWeights.push_back(0.175964);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.570742,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467775,-99) , 
6, 0.0377224, 1, 0, 0.517291,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512505,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.386488,-99) , 
0, 0.088363, 0, 0, 0.432933,-99) , 
3, 0.314162, 1, 0, 0.478418,-99)    );
  // itree = 280
  fBoostWeights.push_back(0.166349);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.00601203, 1, 1, 0.555343,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434087,-99) , 
5, -0.803549, 0, 0, 0.511873,-99)    );
  // itree = 281
  fBoostWeights.push_back(0.186384);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.633761,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547137,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450346,-99) , 
6, -0.888061, 1, 0, 0.47367,-99) , 
6, 0.820545, 0, 0, 0.506038,-99)    );
  // itree = 282
  fBoostWeights.push_back(0.189343);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.345676, 0, 1, 0.559287,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.563377,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.396502,-99) , 
0, 0.0962401, 1, 0, 0.498144,-99) , 
3, 0.375143, 1, 0, 0.534777,-99)    );
  // itree = 283
  fBoostWeights.push_back(0.132837);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.626367,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498646,-99) , 
5, -0.855036, 0, 0, 0.581455,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482411,-99) , 
3, 0.174449, 0, 0, 0.52781,-99)    );
  // itree = 284
  fBoostWeights.push_back(0.172964);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.429643, 1, 1, 0.561454,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438515,-99) , 
6, 0.906523, 1, 0, 0.536803,-99)    );
  // itree = 285
  fBoostWeights.push_back(0.187349);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.587396,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477034,-99) , 
5, 0.827543, 0, 0, 0.508307,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.378173,-99) , 
0, 0.071001, 0, 0, 0.467475,-99)    );
  // itree = 286
  fBoostWeights.push_back(0.179257);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.00701184, 0, 1, 0.570988,-99) , 
NN(
0, 
0, 
-1, 0.927522, 0, -1, 0.447527,-99) , 
6, 0.657586, 1, 0, 0.522207,-99)    );
  // itree = 287
  fBoostWeights.push_back(0.13733);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.586784,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485071,-99) , 
6, -0.859535, 1, 0, 0.509945,-99) , 
NN(
0, 
0, 
-1, 0.0712248, 1, -1, 0.427186,-99) , 
0, 0.0796258, 0, 0, 0.4763,-99)    );
  // itree = 288
  fBoostWeights.push_back(0.201457);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577617,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53879,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.413962,-99) , 
0, 0.076918, 1, 0, 0.45704,-99) , 
5, 0.851537, 0, 0, 0.483397,-99)    );
  // itree = 289
  fBoostWeights.push_back(0.100243);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.63878,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493733,-99) , 
3, 0.511869, 1, 0, 0.563259,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492125,-99) , 
4, 0.0193573, 1, 0, 0.524142,-99)    );
  // itree = 290
  fBoostWeights.push_back(0.156319);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.645286,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.626558,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491045,-99) , 
0, 0.0669888, 1, 0, 0.522594,-99) , 
0, 0.113574, 0, 0, 0.544287,-99)    );
  // itree = 291
  fBoostWeights.push_back(0.145034);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.589931,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519226,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454072,-99) , 
3, 0.231663, 0, 0, 0.470515,-99) , 
4, 0.00809117, 1, 0, 0.499754,-99)    );
  // itree = 292
  fBoostWeights.push_back(0.191111);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0976131, 0, 1, 0.601343,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483047,-99) , 
2, -0.00674117, 0, 0, 0.55437,-99)    );
  // itree = 293
  fBoostWeights.push_back(0.198867);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.63285,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483304,-99) , 
6, -0.892813, 0, 0, 0.583505,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521944,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436784,-99) , 
6, 0.838102, 0, 0, 0.485731,-99) , 
6, 0.455635, 1, 0, 0.540911,-99)    );
  // itree = 294
  fBoostWeights.push_back(0.118312);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.142214, 1, 1, 0.583897,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50508,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438695,-99) , 
6, -0.729318, 0, 0, 0.482225,-99) , 
0, 0.100224, 0, 0, 0.51252,-99)    );
  // itree = 295
  fBoostWeights.push_back(0.133018);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559123,-99) , 
NN(
0, 
0, 
-1, -0.0871921, 1, -1, 0.456652,-99) , 
6, 0.769558, 0, 0, 0.482737,-99)    );
  // itree = 296
  fBoostWeights.push_back(0.139523);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.444639, 0, 1, 0.552354,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458569,-99) , 
6, 0.857022, 1, 0, 0.529271,-99)    );
  // itree = 297
  fBoostWeights.push_back(0.233966);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0823336, 0, 1, 0.590591,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545647,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.39943,-99) , 
6, 0.788816, 0, 0, 0.461369,-99) , 
5, -0.499625, 1, 0, 0.514721,-99)    );
  // itree = 298
  fBoostWeights.push_back(0.168959);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559351,-99) , 
NN(
0, 
0, 
-1, 0.303891, 1, -1, 0.43969,-99) , 
5, -0.858535, 1, 0, 0.471981,-99)    );
  // itree = 299
  fBoostWeights.push_back(0.0936825);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.570945,-99) , 
NN(
0, 
0, 
-1, 0.511869, 1, -1, 0.47914,-99) , 
6, -0.787053, 1, 0, 0.502141,-99)    );
   return;
};

// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}

inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
