// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.24/06       [399366]
Creator        : vince402
Date           : Thu Oct 21 14:13:24 2021
Host           : Linux kunpl 5.4.0-88-generic #99-Ubuntu SMP Thu Sep 23 17:29:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/vince402/Upsilon3S/BDT
Training events: 19033
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "True" [Create PDFs for classifier outputs (signal and background)]
NTrees: "300" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "15%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "4000" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "7.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
BaggedSampleFraction: "4.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "giniindex" [Separation criterion for node splitting]
PruneMethod: "costcomplexity" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "1.000000e+00" [Pruning strength]
PruningValFraction: "3.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
Shrinkage: "1.000000e+00" [Learning rate for BoostType=Grad algorithm]
UseNvars: "3" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "4.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 7
QQMassErr                     QQMassErr                     QQMassErr                     Dimu Mass error               F                                 'F'    [0.0259039457887,2.67742657661]
ctau3D                        ctau3D                        ctau3D                        3 dim ctau of the dimuon      F                                 'F'    [-17.2683258057,9.17125225067]
ctau                          ctau                          ctau                          2 dim ctau of the dimuon      F                                 'F'    [-19.3310947418,8.17510795593]
QQVtxProb                     QQVtxProb                     QQVtxProb                     Vtx prob                      F                                 'F'    [0,0.999962449074]
QQdca                         QQdca                         QQdca                         QQdca                         F                                 'F'    [4.76837158203e-07,13.8900375366]
cosAlpha                      cosAlpha                      cosAlpha                      cos alpha for trajectory angleF                                 'F'    [-1,1]
cosAlpha3D                    cosAlpha3D                    cosAlpha3D                    cos alpha for trajectory angle 3DF                                 'F'    [-0.999997437,0.99999588728]
NSpec 8
pt1                           pt1                           pt1                           Single muon pt1               F                                 'F'    [3.50048589706,27.5638370514]
pt2                           pt2                           pt2                           Single muon pt2               F                                 'F'    [3.50345635414,26.9713134766]
eta1                          eta1                          eta1                          Single muon eta1              F                                 'F'    [-2.39958119392,2.39822292328]
eta2                          eta2                          eta2                          Single muon eta2              F                                 'F'    [-2.39920163155,2.39965939522]
cBin                          cBin                          cBin                          Centrality times 2 bin        F                                 'F'    [1,180]
mass                          mass                          mass                          Dimuon mass                   F                                 'F'    [8.00220394135,11.4993371964]
pt                            pt                            pt                            Dimuon pt                     F                                 'F'    [15.0006780624,29.9999885559]
y                             y                             y                             Dimuon y                      F                                 'F'    [-2.38801860809,2.39258217812]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#include <algorithm>
#include <limits>

#define NN new BDTNode

#ifndef BDTNode__def
#define BDTNode__def

class BDTNode {

public:

   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 

//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 

//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] >= fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}

//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}

#endif

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 7 )
   {
      // the training input variables
      const char* inputVars[] = { "QQMassErr", "ctau3D", "ctau", "QQVtxProb", "QQdca", "cosAlpha", "cosAlpha3D" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[7];
   double fVmax[7];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[7];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
}

void ReadBDT::Initialize()
{
  double inf = std::numeric_limits<double>::infinity();
  double nan = std::numeric_limits<double>::quiet_NaN();
  // itree = 0
  fBoostWeights.push_back(0.731458994121194);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.00448813, 0, 1, 0.686913,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.17956,-99) , 
4, 0.0208303, 1, 0, 0.485953,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.63694);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.00403315, 1, 1, 0.697464,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.266953,-99) , 
3, 0.169201, 0, 0, 0.509704,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.613345);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.763998,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.39577,-99) , 
2, -0.00411545, 0, 0, 0.64807,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.303345,-99) , 
4, 0.0173614, 1, 0, 0.493075,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.50884);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.742317,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465264,-99) , 
1, 0.00421324, 1, 0, 0.668258,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.345957,-99) , 
3, 0.125702, 0, 0, 0.543398,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.543226);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.746523,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42556,-99) , 
1, -0.0045735, 0, 0, 0.629685,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.313093,-99) , 
1, 0.00493686, 1, 0, 0.530874,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.270178);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0877246, 0, 1, 0.579975,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.383552,-99) , 
4, 0.0173587, 1, 0, 0.497378,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.373231);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.67254,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536242,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.331806,-99) , 
0, 0.0998503, 0, 0, 0.41866,-99) , 
4, 0.00694376, 1, 0, 0.494698,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.318986);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.618237,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.564618,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.36244,-99) , 
6, -0.777634, 1, 0, 0.438478,-99) , 
6, 0.86903, 0, 0, 0.479825,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.491078);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.708191,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.3499,-99) , 
2, 0.00553363, 1, 0, 0.551409,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.361415,-99) , 
2, -0.00443219, 0, 0, 0.49017,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.294681);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.639713,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42787,-99) , 
6, 0.787539, 1, 0, 0.53309,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.401388,-99) , 
2, -0.00562456, 0, 0, 0.496258,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.291531);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.597012,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421783,-99) , 
3, 0.130555, 0, 0, 0.523821,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.331869,-99) , 
3, 0.857753, 1, 0, 0.491062,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.245619);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.370657, 1, 1, 0.611801,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.569779,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444034,-99) , 
4, 0.00506174, 1, 0, 0.489392,-99) , 
0, 0.0888619, 0, 0, 0.551697,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.282137);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.789342,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493489,-99) , 
1, 0.00296628, 1, 0, 0.591437,-99) , 
NN(
0, 
0, 
-1, 0.473535, 1, -1, 0.401305,-99) , 
6, -0.467114, 0, 0, 0.496246,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.308927);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.697092,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56527,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.379826,-99) , 
5, 0.0209717, 0, 0, 0.483755,-99) , 
5, -0.962509, 1, 0, 0.521734,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.278997);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.78247,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421149,-99) , 
3, 0.793965, 1, 0, 0.605227,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529978,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429149,-99) , 
5, 0.740565, 0, 0, 0.466303,-99) , 
4, 0.00783867, 1, 0, 0.512927,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.315011);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.670012,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439857,-99) , 
5, -0.925019, 0, 0, 0.565823,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.408867,-99) , 
1, 0.00475692, 1, 0, 0.513945,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.356677);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.740021,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438509,-99) , 
1, 0.00496783, 1, 0, 0.60061,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426602,-99) , 
1, -0.0035908, 0, 0, 0.532777,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.361265);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.726813,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472694,-99) , 
0, 0.0850622, 0, 0, 0.621536,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577852,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.356359,-99) , 
6, 0.885727, 0, 0, 0.448723,-99) , 
5, -0.605599, 1, 0, 0.510713,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.21388);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.476818, 1, 1, 0.587503,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445382,-99) , 
4, 0.0215555, 1, 0, 0.536911,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.345892);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.720779,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.583711,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424905,-99) , 
0, 0.0973479, 1, 0, 0.512665,-99) , 
6, -0.816544, 1, 0, 0.573543,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.256375);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.822139,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480831,-99) , 
2, -0.000176941, 0, 0, 0.566263,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.419315,-99) , 
2, 0.00529451, 1, 0, 0.520581,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.327238);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.421709, 0, 1, 0.64479,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572487,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407373,-99) , 
3, 0.318658, 1, 0, 0.471783,-99) , 
0, 0.0877757, 0, 0, 0.558309,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.233405);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.0047288, 0, 1, 0.607274,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518502,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431529,-99) , 
0, 0.0913297, 1, 0, 0.470697,-99) , 
2, 0.00252019, 1, 0, 0.552296,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.2348);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.640664,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524513,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.381738,-99) , 
0, 0.0842454, 0, 0, 0.46025,-99) , 
3, 0.626819, 0, 0, 0.500185,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.332096);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.729199,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471521,-99) , 
3, 0.121252, 0, 0, 0.572237,-99) , 
NN(
0, 
0, 
-1, -0.642098, 1, -1, 0.374301,-99) , 
3, 0.440873, 1, 0, 0.472059,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.211436);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.39109, 0, 1, 0.578113,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43103,-99) , 
0, 0.0719516, 0, 0, 0.527129,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.300828);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.742717,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.597077,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445985,-99) , 
3, 0.257645, 0, 0, 0.525898,-99) , 
6, -0.946493, 1, 0, 0.563824,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.307929);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.961801, 1, 1, 0.621523,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556907,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.341899,-99) , 
5, -0.798743, 1, 0, 0.465418,-99) , 
5, 0.393152, 0, 0, 0.525294,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.289547);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.700448,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458192,-99) , 
2, -0.00409082, 0, 0, 0.566651,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.412641,-99) , 
2, 0.00391287, 1, 0, 0.50092,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.261157);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.662851,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.576636,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442259,-99) , 
3, 0.257895, 1, 0, 0.497559,-99) , 
5, -0.858036, 1, 0, 0.542878,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.287787);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.673522,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.591535,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45255,-99) , 
4, 0.0126415, 1, 0, 0.522635,-99) , 
5, 0.859535, 0, 0, 0.568663,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.242655);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.00493022, 0, 1, 0.620755,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473639,-99) , 
2, 0.00424966, 1, 0, 0.566285,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.261447);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.733494,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540115,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.395326,-99) , 
1, -0.00483874, 0, 0, 0.48727,-99) , 
5, 0.964009, 0, 0, 0.528775,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.225539);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.682127,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480068,-99) , 
5, -0.933017, 1, 0, 0.528129,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.342566,-99) , 
0, 0.064423, 0, 0, 0.488083,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.239711);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.66323,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.59586,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449045,-99) , 
6, -0.684767, 1, 0, 0.509204,-99) , 
5, 0.974506, 0, 0, 0.534519,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.207641);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.662877,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513678,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.357038,-99) , 
3, 0.463487, 1, 0, 0.47516,-99) , 
4, 0.0050565, 1, 0, 0.520166,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.318585);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.106935, 0, 1, 0.597338,-99) , 
NN(
0, 
0, 
-1, 0.0887264, 0, -1, 0.369697,-99) , 
5, -0.782054, 0, 0, 0.497085,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.265308);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.116103, 0, 1, 0.596898,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.419476,-99) , 
3, 0.794201, 1, 0, 0.561533,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.171874);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5934,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505229,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.372135,-99) , 
5, -0.0202449, 0, 0, 0.456108,-99) , 
6, -0.848998, 1, 0, 0.48998,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.210383);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0946555, 1, 1, 0.547956,-99) , 
NN(
0, 
0, 
-1, 0.0658469, 1, -1, 0.388971,-99) , 
0, 0.0782232, 0, 0, 0.480855,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.220266);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.655558,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49249,-99) , 
3, 0.513553, 0, 0, 0.55057,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524319,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.358266,-99) , 
6, -0.953673, 1, 0, 0.421107,-99) , 
1, -0.00189062, 0, 0, 0.488444,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.21102);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.0003809, 1, 1, 0.567168,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531102,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.401229,-99) , 
3, 0.566243, 0, 0, 0.437083,-99) , 
0, 0.0852117, 1, 0, 0.490349,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.257209);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.651668,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486461,-99) , 
5, -0.650087, 0, 0, 0.577175,-99) , 
NN(
0, 
0, 
-1, 0.1653, 1, -1, 0.408189,-99) , 
3, 0.331373, 0, 0, 0.475776,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.364002);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.661254,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.392867,-99) , 
2, -0.00540117, 0, 0, 0.533118,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.388071,-99) , 
1, 0.0041097, 1, 0, 0.482066,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.232001);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.631286,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516248,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.406832,-99) , 
0, 0.107784, 0, 0, 0.439234,-99) , 
5, -0.949013, 1, 0, 0.476189,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.1946);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.675273,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510451,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.384355,-99) , 
3, 0.465725, 1, 0, 0.481199,-99) , 
4, 0.0050565, 1, 0, 0.52847,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.241605);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.644855,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462527,-99) , 
2, -0.00492691, 0, 0, 0.5481,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.418825,-99) , 
2, 0.00424966, 1, 0, 0.50119,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.209393);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.684886,-99) , 
NN(
0, 
0, 
-1, 0.802386, 1, -1, 0.453375,-99) , 
5, -0.945514, 1, 0, 0.4996,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.24944);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.672737,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526875,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414983,-99) , 
0, 0.0690756, 1, 0, 0.442013,-99) , 
5, 0.944014, 0, 0, 0.480971,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.182342);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.726069, 1, 1, 0.545819,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527277,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.311271,-99) , 
3, 0.660476, 0, 0, 0.434813,-99) , 
3, 0.505355, 1, 0, 0.504248,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.258957);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.495126, 0, 1, 0.598287,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555862,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.395518,-99) , 
0, 0.068124, 1, 0, 0.459607,-99) , 
0, 0.0876978, 0, 0, 0.526601,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.197611);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.521642, 1, 1, 0.56412,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.406913,-99) , 
6, -0.956504, 0, 0, 0.531607,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.122787);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.648994,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496401,-99) , 
6, -0.659825, 1, 0, 0.529612,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417669,-99) , 
6, -0.958991, 0, 0, 0.50941,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.334218);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.646933,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557532,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.34493,-99) , 
6, 0.656013, 0, 0, 0.449157,-99) , 
6, -0.842537, 1, 0, 0.498471,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.217785);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.61021,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481607,-99) , 
0, 0.109891, 0, 0, 0.527819,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503868,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.310984,-99) , 
4, 0.00525416, 1, 0, 0.403945,-99) , 
4, 0.0101168, 0, 0, 0.461854,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.221258);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.417146, 0, 1, 0.548606,-99) , 
NN(
0, 
0, 
-1, 0.740537, 1, -1, 0.408626,-99) , 
0, 0.104075, 0, 0, 0.451191,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.242453);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0845003, 1, 1, 0.587492,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421969,-99) , 
0, 0.0645083, 0, 0, 0.556752,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.33004);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.628976,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478267,-99) , 
0, 0.0649226, 0, 0, 0.582357,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55243,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.309985,-99) , 
6, 0.222687, 1, 0, 0.40843,-99) , 
0, 0.0928382, 1, 0, 0.491946,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.21303);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.576085,-99) , 
NN(
0, 
0, 
-1, -0.39815, 1, -1, 0.424723,-99) , 
4, 0.00694567, 1, 0, 0.466486,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.31241);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.589766,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.41145,-99) , 
1, 0.00317408, 1, 0, 0.484885,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.355911,-99) , 
1, -0.00398983, 0, 0, 0.436358,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.224916);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.619785,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555378,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429909,-99) , 
6, -0.816605, 1, 0, 0.478621,-99) , 
6, 0.881526, 0, 0, 0.517511,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.235753);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.665497,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488336,-99) , 
4, 0.0169385, 1, 0, 0.565958,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.403238,-99) , 
3, 0.70971, 1, 0, 0.525998,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.316715);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.00110273, 1, 1, 0.639215,-99) , 
NN(
0, 
0, 
-1, 0.123757, 1, -1, 0.40857,-99) , 
0, 0.0865875, 1, 0, 0.504098,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.299351);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.00439682, 0, 1, 0.604301,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.391245,-99) , 
0, 0.0651064, 0, 0, 0.555986,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.241873);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.687996,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.623958,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493224,-99) , 
0, 0.102864, 0, 0, 0.5446,-99) , 
4, 0.00587912, 1, 0, 0.579298,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.242242);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.128603, 0, 1, 0.584991,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545868,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.339082,-99) , 
0, 0.109609, 1, 0, 0.472935,-99) , 
3, 0.384608, 1, 0, 0.533304,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.219488);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.62864,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525774,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.35953,-99) , 
6, 0.451973, 1, 0, 0.479782,-99) , 
5, 0.868533, 0, 0, 0.522152,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.230922);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.593494,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456532,-99) , 
0, 0.10543, 0, 0, 0.495595,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.335439,-99) , 
3, 0.741452, 1, 0, 0.459619,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.197867);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.653246,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494524,-99) , 
5, 0.870032, 0, 0, 0.540369,-99) , 
NN(
0, 
0, 
-1, -0.782554, 1, -1, 0.406107,-99) , 
0, 0.0946342, 1, 0, 0.47566,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.332255);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.556037, 0, 1, 0.626753,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.416415,-99) , 
0, 0.12382, 1, 0, 0.576716,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.280406);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572429,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.39192,-99) , 
6, -0.938575, 0, 0, 0.513427,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.355656,-99) , 
5, 0.957511, 1, 0, 0.474824,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.232748);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.588381,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.367045,-99) , 
3, 0.362602, 0, 0, 0.423916,-99) , 
0, 0.110987, 0, 0, 0.467391,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.237054);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.653838,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470603,-99) , 
6, -0.95891, 0, 0, 0.570785,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515713,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.374395,-99) , 
5, 0.890246, 0, 0, 0.439046,-99) , 
5, -0.614596, 1, 0, 0.489894,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.26412);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553339,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426593,-99) , 
3, 0.291392, 0, 0, 0.478291,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.309526,-99) , 
6, 0.955503, 1, 0, 0.440558,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.296444);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.654301,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442702,-99) , 
5, 0.823044, 0, 0, 0.497497,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.309411,-99) , 
3, 0.793772, 1, 0, 0.459417,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.29897);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.60375,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548711,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.368834,-99) , 
6, 0.800538, 0, 0, 0.423117,-99) , 
3, 0.257176, 1, 0, 0.501698,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.16127);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.641879,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48379,-99) , 
3, 0.339295, 0, 0, 0.524491,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.413532,-99) , 
3, 0.715294, 1, 0, 0.498793,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.200872);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.645643,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524973,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425098,-99) , 
2, 0.00204032, 1, 0, 0.46891,-99) , 
5, -0.947013, 1, 0, 0.503729,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.238686);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.674876,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.59088,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446246,-99) , 
6, -0.919513, 1, 0, 0.476495,-99) , 
0, 0.069293, 1, 0, 0.516588,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.287725);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.647495,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.649282,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463252,-99) , 
0, 0.0760448, 1, 0, 0.514557,-99) , 
3, 0.207673, 1, 0, 0.570514,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.229345);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.741802,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456295,-99) , 
3, 0.47721, 1, 0, 0.544851,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440961,-99) , 
4, 0.0140756, 1, 0, 0.490856,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.286857);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0876266, 0, 1, 0.710258,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540208,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440948,-99) , 
6, 0.675019, 1, 0, 0.502467,-99) , 
3, 0.402884, 0, 0, 0.570928,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.309605);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.710688,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.610053,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450648,-99) , 
6, -0.721034, 0, 0, 0.549496,-99) , 
0, 0.126637, 0, 0, 0.577921,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.206047);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.61954,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48864,-99) , 
0, 0.0980157, 1, 0, 0.539816,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.385009,-99) , 
0, 0.0719516, 0, 0, 0.490833,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.230395);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.629606,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478378,-99) , 
2, -0.00406536, 0, 0, 0.560004,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.410243,-99) , 
5, 0.979505, 1, 0, 0.535037,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.258655);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.677156,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499656,-99) , 
3, 0.12472, 0, 0, 0.582741,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.376874,-99) , 
3, 0.808767, 1, 0, 0.540388,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.245519);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.628712,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527477,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.344617,-99) , 
3, 0.318484, 1, 0, 0.459936,-99) , 
3, 0.626819, 0, 0, 0.49769,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.307138);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.639012,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.402296,-99) , 
1, 0.00448022, 1, 0, 0.555009,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.412912,-99) , 
3, 0.13095, 0, 0, 0.492521,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.160867);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.627503,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52205,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.40397,-99) , 
1, -0.00236196, 0, 0, 0.487201,-99) , 
6, -0.956993, 1, 0, 0.509546,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.186203);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.609155,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488789,-99) , 
6, -0.816066, 0, 0, 0.554922,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430416,-99) , 
6, 0.946949, 1, 0, 0.525239,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.171924);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.588615,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489827,-99) , 
3, 0.291368, 0, 0, 0.531722,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.398569,-99) , 
0, 0.0701862, 0, 0, 0.491184,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.313042);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.624237,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.583831,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.377534,-99) , 
4, 0.0117476, 0, 0, 0.474404,-99) , 
5, -0.815046, 1, 0, 0.516917,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.25307);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.021712, 0, 1, 0.597086,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.566908,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407808,-99) , 
2, -0.001174, 1, 0, 0.471215,-99) , 
0, 0.0871689, 0, 0, 0.532551,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.283658);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.724403,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54884,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.408001,-99) , 
2, -0.00161524, 0, 0, 0.459435,-99) , 
5, 0.952512, 0, 0, 0.501828,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.254099);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.639843,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470632,-99) , 
5, -0.972007, 0, 0, 0.565367,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548861,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.385459,-99) , 
4, 0.0107253, 1, 0, 0.4505,-99) , 
6, 0.243185, 1, 0, 0.506226,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.256758);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.631959,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55724,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.395502,-99) , 
5, -0.214696, 1, 0, 0.490697,-99) , 
6, 0.889013, 0, 0, 0.52648,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.279678);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.616333,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445018,-99) , 
0, 0.0884023, 0, 0, 0.513,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.354116,-99) , 
6, 0.915518, 1, 0, 0.467046,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.356433);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.679141,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425989,-99) , 
4, 0.0133633, 1, 0, 0.512029,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.327402,-99) , 
3, 0.757941, 1, 0, 0.468339,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.172928);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.611056,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527052,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.412974,-99) , 
0, 0.0872372, 0, 0, 0.493271,-99) , 
0, 0.0709482, 1, 0, 0.522851,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.248544);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.661529,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48902,-99) , 
3, 0.221436, 1, 0, 0.563752,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.393371,-99) , 
1, -0.00398983, 0, 0, 0.498544,-99)    );
  // itree = 100
  fBoostWeights.push_back(0.24031);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0.232183, 0, 1, 0.584992,-99)    );
  // itree = 101
  fBoostWeights.push_back(0.309626);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.686837,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.607175,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425494,-99) , 
5, -0.789053, 1, 0, 0.501662,-99) , 
6, 0.929957, 0, 0, 0.540355,-99)    );
  // itree = 102
  fBoostWeights.push_back(0.240439);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.674882,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544629,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438024,-99) , 
0, 0.0860781, 1, 0, 0.477726,-99) , 
3, 0.514102, 0, 0, 0.526485,-99)    );
  // itree = 103
  fBoostWeights.push_back(0.220301);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.687876,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534589,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.409575,-99) , 
6, 0.94707, 1, 0, 0.496656,-99) , 
5, -0.950512, 1, 0, 0.533828,-99)    );
  // itree = 104
  fBoostWeights.push_back(0.288442);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.630906,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572497,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.376441,-99) , 
6, 0.215144, 0, 0, 0.493501,-99) , 
5, -0.926518, 1, 0, 0.524408,-99)    );
  // itree = 105
  fBoostWeights.push_back(0.20661);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.600951,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470902,-99) , 
1, 0.0021602, 1, 0, 0.53021,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.392612,-99) , 
5, -0.972007, 0, 0, 0.495776,-99)    );
  // itree = 106
  fBoostWeights.push_back(0.267243);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.633581,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556572,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.36216,-99) , 
6, -0.176677, 0, 0, 0.507653,-99) , 
6, -0.795538, 1, 0, 0.546125,-99)    );
  // itree = 107
  fBoostWeights.push_back(0.263825);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.59129,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.362045,-99) , 
0, 0.109574, 1, 0, 0.519091,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424432,-99) , 
4, 0.0215583, 1, 0, 0.479061,-99)    );
  // itree = 108
  fBoostWeights.push_back(0.181087);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.610158,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496015,-99) , 
2, 0.00536342, 1, 0, 0.543017,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510227,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.332206,-99) , 
6, -0.840933, 1, 0, 0.431278,-99) , 
6, -0.165699, 0, 0, 0.485733,-99)    );
  // itree = 109
  fBoostWeights.push_back(0.219105);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.637216,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511204,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.377109,-99) , 
1, -0.00509945, 0, 0, 0.449044,-99) , 
6, 0.93001, 0, 0, 0.486157,-99)    );
  // itree = 110
  fBoostWeights.push_back(0.190345);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.59593,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502739,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.395771,-99) , 
4, 0.0137192, 1, 0, 0.446531,-99) , 
6, 0.800548, 0, 0, 0.489619,-99)    );
  // itree = 111
  fBoostWeights.push_back(0.335839);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0865073, 0, 1, 0.717541,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540221,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.432577,-99) , 
5, -0.882609, 1, 0, 0.48595,-99) , 
5, 0.377656, 0, 0, 0.576203,-99)    );
  // itree = 112
  fBoostWeights.push_back(0.216483);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.598125,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472377,-99) , 
5, -0.939015, 1, 0, 0.502872,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.332441,-99) , 
0, 0.123178, 1, 0, 0.458495,-99)    );
  // itree = 113
  fBoostWeights.push_back(0.228993);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.202831, 1, 1, 0.602435,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470577,-99) , 
5, -0.91802, 0, 0, 0.563835,-99)    );
  // itree = 114
  fBoostWeights.push_back(0.293793);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.645493,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478821,-99) , 
2, 0.00406957, 1, 0, 0.584955,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.391545,-99) , 
0, 0.111649, 1, 0, 0.511736,-99)    );
  // itree = 115
  fBoostWeights.push_back(0.196551);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.719399,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48114,-99) , 
6, 0.779131, 1, 0, 0.553425,-99) , 
NN(
0, 
0, 
-1, -0.945849, 0, -1, 0.440124,-99) , 
2, -0.00170805, 0, 0, 0.496492,-99)    );
  // itree = 116
  fBoostWeights.push_back(0.21959);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.63724,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467986,-99) , 
5, -0.926019, 0, 0, 0.551953,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431232,-99) , 
1, 0.00341608, 1, 0, 0.501719,-99)    );
  // itree = 117
  fBoostWeights.push_back(0.203273);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.667361,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528753,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.372718,-99) , 
0, 0.123856, 1, 0, 0.48816,-99) , 
5, 0.968508, 0, 0, 0.516245,-99)    );
  // itree = 118
  fBoostWeights.push_back(0.359759);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.975571, 0, 1, 0.697622,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.679186,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440976,-99) , 
0, 0.109649, 0, 0, 0.503204,-99) , 
5, -0.726068, 1, 0, 0.567248,-99)    );
  // itree = 119
  fBoostWeights.push_back(0.381619);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.722271,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561653,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.341029,-99) , 
0, 0.0877039, 0, 0, 0.438662,-99) , 
5, 0.95851, 0, 0, 0.484282,-99)    );
  // itree = 120
  fBoostWeights.push_back(0.263603);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.690098,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445006,-99) , 
1, 0.0034968, 1, 0, 0.578922,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43596,-99) , 
4, 0.0173596, 1, 0, 0.499982,-99)    );
  // itree = 121
  fBoostWeights.push_back(0.267858);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.00197703, 1, 1, 0.610184,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.433227,-99) , 
1, -0.00422991, 0, 0, 0.546304,-99)    );
  // itree = 122
  fBoostWeights.push_back(0.273577);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0195962, 1, 1, 0.612174,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540481,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.390203,-99) , 
0, 0.0861687, 1, 0, 0.474611,-99) , 
4, 0.00980096, 0, 0, 0.559917,-99)    );
  // itree = 123
  fBoostWeights.push_back(0.349337);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.642291,-99) , 
NN(
0, 
0, 
-1, 0.00996977, 0, -1, 0.385801,-99) , 
6, -0.648587, 1, 0, 0.459186,-99)    );
  // itree = 124
  fBoostWeights.push_back(0.238474);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.61575,-99) , 
NN(
0, 
0, 
-1, 0.0781833, 0, -1, 0.426656,-99) , 
5, 0.859535, 0, 0, 0.475757,-99)    );
  // itree = 125
  fBoostWeights.push_back(0.28322);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.00134972, 1, 1, 0.641544,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449123,-99) , 
4, 0.0215555, 1, 0, 0.552936,-99)    );
  // itree = 126
  fBoostWeights.push_back(0.212007);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.124016, 0, 1, 0.571025,-99) , 
NN(
0, 
0, 
-1, 0.0652322, 1, -1, 0.418078,-99) , 
0, 0.0763247, 0, 0, 0.513225,-99)    );
  // itree = 127
  fBoostWeights.push_back(0.270761);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.71728,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54819,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.334026,-99) , 
5, 0.822605, 1, 0, 0.501857,-99) , 
5, 0.969508, 0, 0, 0.53462,-99)    );
  // itree = 128
  fBoostWeights.push_back(0.25827);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.606189,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451789,-99) , 
6, 0.559125, 0, 0, 0.514413,-99) , 
NN(
0, 
0, 
-1, 0.41558, 1, -1, 0.396044,-99) , 
0, 0.0850046, 1, 0, 0.442868,-99)    );
  // itree = 129
  fBoostWeights.push_back(0.254127);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0172669, 1, 1, 0.587184,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550853,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.368051,-99) , 
2, 0.00203529, 1, 0, 0.453599,-99) , 
3, 0.41563, 1, 0, 0.536375,-99)    );
  // itree = 130
  fBoostWeights.push_back(0.244253);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.629132,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534774,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.336379,-99) , 
3, 0.322866, 1, 0, 0.470522,-99) , 
3, 0.635317, 0, 0, 0.500227,-99)    );
  // itree = 131
  fBoostWeights.push_back(0.245133);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.618293,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476181,-99) , 
6, 0.958583, 1, 0, 0.577509,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423435,-99) , 
5, -0.925019, 0, 0, 0.529895,-99)    );
  // itree = 132
  fBoostWeights.push_back(0.270441);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.656807,-99) , 
NN(
0, 
0, 
-1, 0.820947, 1, -1, 0.415722,-99) , 
5, 0.95851, 0, 0, 0.452701,-99)    );
  // itree = 133
  fBoostWeights.push_back(0.100432);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552136,-99) , 
NN(
0, 
0, 
-1, -0.752517, 0, -1, 0.469614,-99) , 
5, -0.950512, 1, 0, 0.490183,-99)    );
  // itree = 134
  fBoostWeights.push_back(0.2484);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.0019561, 0, 1, 0.591178,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.418522,-99) , 
2, 0.00577186, 1, 0, 0.530961,-99)    );
  // itree = 135
  fBoostWeights.push_back(0.237121);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.65819, 0, 1, 0.583525,-99) , 
NN(
0, 
0, 
-1, 0.091388, 0, -1, 0.415895,-99) , 
3, 0.293641, 0, 0, 0.479353,-99)    );
  // itree = 136
  fBoostWeights.push_back(0.229427);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0980571, 0, 1, 0.621916,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534009,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.370176,-99) , 
6, 0.162635, 1, 0, 0.491488,-99) , 
6, 0.800536, 0, 0, 0.5377,-99)    );
  // itree = 137
  fBoostWeights.push_back(0.286177);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.676333,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466058,-99) , 
3, 0.124725, 0, 0, 0.554324,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.375118,-99) , 
3, 0.746035, 1, 0, 0.513542,-99)    );
  // itree = 138
  fBoostWeights.push_back(0.383352);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.69802,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.597464,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.390408,-99) , 
0, 0.0806545, 0, 0, 0.49765,-99) , 
5, 0.79955, 0, 0, 0.561709,-99)    );
  // itree = 139
  fBoostWeights.push_back(0.342376);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.740627,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.66788,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434111,-99) , 
0, 0.109571, 0, 0, 0.493808,-99) , 
5, -0.945514, 1, 0, 0.540223,-99)    );
  // itree = 140
  fBoostWeights.push_back(0.237756);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.658612,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54828,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414386,-99) , 
5, 0.570107, 0, 0, 0.466551,-99) , 
0, 0.0658838, 1, 0, 0.495153,-99)    );
  // itree = 141
  fBoostWeights.push_back(0.216106);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.618125,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477596,-99) , 
5, -0.803549, 0, 0, 0.562391,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52358,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.351739,-99) , 
4, 0.0125084, 0, 0, 0.456718,-99) , 
0, 0.0973467, 1, 0, 0.515405,-99)    );
  // itree = 142
  fBoostWeights.push_back(0.353731);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.167208, 0, 1, 0.594107,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.619631,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.325597,-99) , 
0, 0.0850442, 1, 0, 0.425593,-99) , 
3, 0.322907, 1, 0, 0.513212,-99)    );
  // itree = 143
  fBoostWeights.push_back(0.200468);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.613847,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482115,-99) , 
4, 0.0142891, 1, 0, 0.540634,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.403757,-99) , 
6, -0.896519, 0, 0, 0.500041,-99)    );
  // itree = 144
  fBoostWeights.push_back(0.222055);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.571685,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.418717,-99) , 
0, 0.0658554, 0, 0, 0.514941,-99) , 
NN(
0, 
0, 
-1, 0.109723, 0, -1, 0.414358,-99) , 
0, 0.110532, 1, 0, 0.482029,-99)    );
  // itree = 145
  fBoostWeights.push_back(0.360818);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.687418,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443432,-99) , 
5, -0.962335, 0, 0, 0.592032,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546614,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.322126,-99) , 
0, 0.0876389, 0, 0, 0.433917,-99) , 
5, 0.773057, 1, 0, 0.524281,-99)    );
  // itree = 146
  fBoostWeights.push_back(0.350049);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.671181,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455057,-99) , 
5, -0.0142464, 1, 0, 0.568404,-99) , 
NN(
0, 
0, 
-1, 0.0156769, 0, -1, 0.370708,-99) , 
0, 0.0865073, 1, 0, 0.444978,-99)    );
  // itree = 147
  fBoostWeights.push_back(0.198713);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.636002,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518714,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.343195,-99) , 
3, 0.376732, 1, 0, 0.476013,-99) , 
4, 0.00692918, 1, 0, 0.510779,-99)    );
  // itree = 148
  fBoostWeights.push_back(0.264935);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.690409,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477275,-99) , 
3, 0.745964, 1, 0, 0.583159,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414357,-99) , 
3, 0.291392, 0, 0, 0.479461,-99)    );
  // itree = 149
  fBoostWeights.push_back(0.200803);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551882,-99) , 
NN(
0, 
0, 
-1, 0.00835, 1, -1, 0.41213,-99) , 
4, 0.0137183, 0, 0, 0.476757,-99)    );
  // itree = 150
  fBoostWeights.push_back(0.21012);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.583698,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.608013,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440808,-99) , 
5, 0.895026, 0, 0, 0.480508,-99) , 
0, 0.107167, 0, 0, 0.510076,-99)    );
  // itree = 151
  fBoostWeights.push_back(0.325862);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.704567, 0, 1, 0.607577,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.361537,-99) , 
0, 0.0651015, 0, 0, 0.553845,-99)    );
  // itree = 152
  fBoostWeights.push_back(0.237661);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.747862,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53111,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.381074,-99) , 
3, 0.62557, 1, 0, 0.492146,-99) , 
6, -0.935497, 1, 0, 0.531907,-99)    );
  // itree = 153
  fBoostWeights.push_back(0.29359);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.670057,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492701,-99) , 
1, -0.00219184, 0, 0, 0.586045,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.388163,-99) , 
3, 0.216937, 0, 0, 0.4772,-99)    );
  // itree = 154
  fBoostWeights.push_back(0.250899);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.671994, 0, 1, 0.608348,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425587,-99) , 
3, 0.261143, 0, 0, 0.502312,-99)    );
  // itree = 155
  fBoostWeights.push_back(0.225363);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.665725,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472263,-99) , 
3, 0.291388, 1, 0, 0.56797,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513746,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.375576,-99) , 
5, -0.683579, 0, 0, 0.454801,-99) , 
0, 0.095489, 1, 0, 0.51564,-99)    );
  // itree = 156
  fBoostWeights.push_back(0.235284);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.697519,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556723,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436752,-99) , 
2, 0.0020948, 1, 0, 0.524158,-99) , 
6, 0.925511, 0, 0, 0.555026,-99)    );
  // itree = 157
  fBoostWeights.push_back(0.25111);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.00415582, 0, 1, 0.578436,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.38143,-99) , 
6, 0.919012, 1, 0, 0.527892,-99)    );
  // itree = 158
  fBoostWeights.push_back(0.232462);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.690935,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.565469,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441194,-99) , 
5, 0.890527, 0, 0, 0.473664,-99) , 
3, 0.672057, 0, 0, 0.509858,-99)    );
  // itree = 159
  fBoostWeights.push_back(0.297338);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.684289,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.590819,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414887,-99) , 
0, 0.072936, 1, 0, 0.451056,-99) , 
3, 0.587775, 0, 0, 0.494697,-99)    );
  // itree = 160
  fBoostWeights.push_back(0.17425);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.72313,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489815,-99) , 
3, 0.225016, 1, 0, 0.560895,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451155,-99) , 
4, 0.0227526, 1, 0, 0.505858,-99)    );
  // itree = 161
  fBoostWeights.push_back(0.190275);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.595075,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539051,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.433105,-99) , 
0, 0.0733113, 1, 0, 0.462742,-99) , 
5, -0.91852, 1, 0, 0.493773,-99)    );
  // itree = 162
  fBoostWeights.push_back(0.191716);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.101194, 1, 1, 0.616375,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463984,-99) , 
3, 0.20994, 0, 0, 0.524724,-99)    );
  // itree = 163
  fBoostWeights.push_back(0.260228);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.660869,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.588511,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450595,-99) , 
6, 0.610617, 0, 0, 0.525211,-99) , 
5, -0.933517, 1, 0, 0.557239,-99)    );
  // itree = 164
  fBoostWeights.push_back(0.318636);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.59894,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449777,-99) , 
5, 0.977006, 1, 0, 0.569379,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.323635,-99) , 
6, -0.962003, 0, 0, 0.505635,-99)    );
  // itree = 165
  fBoostWeights.push_back(0.23495);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.782554, 1, 1, 0.603504,-99) , 
NN(
0, 
0, 
-1, 0.384639, 1, -1, 0.435337,-99) , 
0, 0.0876781, 0, 0, 0.515301,-99)    );
  // itree = 166
  fBoostWeights.push_back(0.246417);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.00489411, 1, 1, 0.591764,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.574815,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.412376,-99) , 
3, 0.295637, 0, 0, 0.470327,-99) , 
6, 0.0217376, 0, 0, 0.526852,-99)    );
  // itree = 167
  fBoostWeights.push_back(0.257891);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.58533,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550415,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.382432,-99) , 
6, -0.869972, 1, 0, 0.443777,-99) , 
5, 0.823044, 0, 0, 0.479901,-99)    );
  // itree = 168
  fBoostWeights.push_back(0.287069);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5879,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542129,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.384229,-99) , 
3, 0.635317, 0, 0, 0.410122,-99) , 
0, 0.125383, 0, 0, 0.439201,-99)    );
  // itree = 169
  fBoostWeights.push_back(0.227037);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.648991,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464875,-99) , 
1, -0.00468278, 0, 0, 0.54828,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42822,-99) , 
1, 0.00308884, 1, 0, 0.497407,-99)    );
  // itree = 170
  fBoostWeights.push_back(0.30832);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.642084,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.433597,-99) , 
6, -0.792009, 0, 0, 0.563561,-99) , 
NN(
0, 
0, 
-1, -0.370657, 1, -1, 0.397795,-99) , 
0, 0.0973492, 1, 0, 0.487608,-99)    );
  // itree = 171
  fBoostWeights.push_back(0.340295);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.00523099, 0, 1, 0.63605,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438335,-99) , 
6, 0.955507, 1, 0, 0.591251,-99)    );
  // itree = 172
  fBoostWeights.push_back(0.258664);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.584925,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.404249,-99) , 
5, -0.969508, 0, 0, 0.510548,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.404729,-99) , 
2, 0.00529451, 1, 0, 0.475311,-99)    );
  // itree = 173
  fBoostWeights.push_back(0.243619);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0900762, 1, 1, 0.604114,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490465,-99) , 
0, 0.0644332, 0, 0, 0.582515,-99)    );
  // itree = 174
  fBoostWeights.push_back(0.235808);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.956903, 1, 1, 0.630346,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514946,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.378649,-99) , 
0, 0.0787378, 0, 0, 0.455482,-99) , 
5, -0.79855, 1, 0, 0.51141,-99)    );
  // itree = 175
  fBoostWeights.push_back(0.226938);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0958118, 0, 1, 0.600467,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453716,-99) , 
2, 0.00487716, 1, 0, 0.545973,-99)    );
  // itree = 176
  fBoostWeights.push_back(0.213763);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.636848,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510922,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.394564,-99) , 
6, 0.51661, 0, 0, 0.450302,-99) , 
0, 0.0698764, 1, 0, 0.488236,-99)    );
  // itree = 177
  fBoostWeights.push_back(0.230604);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.683603,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442735,-99) , 
3, 0.746036, 1, 0, 0.600696,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48373,-99) , 
4, 0.0208303, 1, 0, 0.54545,-99)    );
  // itree = 178
  fBoostWeights.push_back(0.266449);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.684079, 1, 1, 0.595585,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.412408,-99) , 
6, 0.963001, 1, 0, 0.559897,-99)    );
  // itree = 179
  fBoostWeights.push_back(0.368821);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.705213,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.39822,-99) , 
0, 0.104228, 1, 0, 0.594367,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.404822,-99) , 
3, 0.124714, 0, 0, 0.492383,-99)    );
  // itree = 180
  fBoostWeights.push_back(0.217777);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.717709,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481808,-99) , 
4, 0.0154787, 1, 0, 0.545297,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.409076,-99) , 
3, 0.553046, 1, 0, 0.5076,-99)    );
  // itree = 181
  fBoostWeights.push_back(0.279774);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.655975,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491525,-99) , 
6, 0.953232, 1, 0, 0.572438,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539344,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.316317,-99) , 
6, -0.840887, 1, 0, 0.427968,-99) , 
6, 0.0957306, 0, 0, 0.488915,-99)    );
  // itree = 182
  fBoostWeights.push_back(0.335478);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.697216,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55354,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.375264,-99) , 
1, -0.00168104, 0, 0, 0.464086,-99) , 
0, 0.112113, 0, 0, 0.525218,-99)    );
  // itree = 183
  fBoostWeights.push_back(0.275497);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.570107, 0, 1, 0.574979,-99) , 
NN(
0, 
0, 
-1, 0.0725042, 0, -1, 0.363837,-99) , 
4, 0.00841893, 0, 0, 0.4985,-99)    );
  // itree = 184
  fBoostWeights.push_back(0.172879);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.591867,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557775,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444786,-99) , 
6, 0.932014, 0, 0, 0.471443,-99) , 
3, 0.766652, 0, 0, 0.490191,-99)    );
  // itree = 185
  fBoostWeights.push_back(0.313351);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.500634, 0, 1, 0.61955,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407949,-99) , 
0, 0.116822, 1, 0, 0.546669,-99)    );
  // itree = 186
  fBoostWeights.push_back(0.358794);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.807711,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.621436,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.433678,-99) , 
0, 0.07747, 1, 0, 0.508642,-99) , 
0, 0.123842, 0, 0, 0.55919,-99)    );
  // itree = 187
  fBoostWeights.push_back(0.168374);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.924, 1, 1, 0.55276,-99) , 
NN(
0, 
0, 
-1, 0.0650488, 1, -1, 0.425196,-99) , 
0, 0.0763213, 0, 0, 0.511761,-99)    );
  // itree = 188
  fBoostWeights.push_back(0.312827);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.602802,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450217,-99) , 
3, 0.388638, 1, 0, 0.545945,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.318449,-99) , 
0, 0.0663296, 0, 0, 0.483924,-99)    );
  // itree = 189
  fBoostWeights.push_back(0.282057);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.752556,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539697,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.397984,-99) , 
0, 0.0745981, 0, 0, 0.484194,-99) , 
6, 0.925455, 0, 0, 0.534446,-99)    );
  // itree = 190
  fBoostWeights.push_back(0.283497);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.597753,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491138,-99) , 
5, -0.974206, 1, 0, 0.541181,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525181,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.249587,-99) , 
5, 0.569997, 0, 0, 0.401955,-99) , 
5, -0.714071, 1, 0, 0.450029,-99)    );
  // itree = 191
  fBoostWeights.push_back(0.210083);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.565735,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450754,-99) , 
1, 0.0044437, 1, 0, 0.503634,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.378019,-99) , 
6, -0.902522, 0, 0, 0.469618,-99)    );
  // itree = 192
  fBoostWeights.push_back(0.345259);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.708837,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.616648,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414421,-99) , 
3, 0.51356, 0, 0, 0.462259,-99) , 
0, 0.109214, 0, 0, 0.521693,-99)    );
  // itree = 193
  fBoostWeights.push_back(0.201636);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580478,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529296,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.415554,-99) , 
5, -0.810547, 1, 0, 0.447468,-99) , 
0, 0.0700696, 1, 0, 0.476915,-99)    );
  // itree = 194
  fBoostWeights.push_back(0.273119);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.730369,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434078,-99) , 
3, 0.257176, 1, 0, 0.525603,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425587,-99) , 
4, 0.0214182, 1, 0, 0.477384,-99)    );
  // itree = 195
  fBoostWeights.push_back(0.177419);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548018,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536734,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.404325,-99) , 
1, -0.0026074, 1, 0, 0.448394,-99) , 
3, 0.12445, 1, 0, 0.494692,-99)    );
  // itree = 196
  fBoostWeights.push_back(0.262075);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.610654,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.571461,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.416586,-99) , 
4, 0.00485217, 1, 0, 0.465643,-99) , 
3, 0.147695, 1, 0, 0.525899,-99)    );
  // itree = 197
  fBoostWeights.push_back(0.320098);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.647677,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.564474,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.348421,-99) , 
5, 0.377488, 0, 0, 0.479275,-99) , 
5, -0.875531, 1, 0, 0.52597,-99)    );
  // itree = 198
  fBoostWeights.push_back(0.219998);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.686144,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496494,-99) , 
4, 0.00896966, 0, 0, 0.561662,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.409981,-99) , 
3, 0.13921, 0, 0, 0.487172,-99)    );
  // itree = 199
  fBoostWeights.push_back(0.263978);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.657711,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.591602,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428842,-99) , 
5, 0.727568, 0, 0, 0.499543,-99) , 
6, -0.925516, 1, 0, 0.526296,-99)    );
  // itree = 200
  fBoostWeights.push_back(0.385492);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.639281,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.382389,-99) , 
3, 0.803885, 1, 0, 0.575513,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.365135,-99) , 
1, -0.00449625, 0, 0, 0.488863,-99)    );
  // itree = 201
  fBoostWeights.push_back(0.225366);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.593102, 0, 1, 0.582068,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423284,-99) , 
1, 0.00289654, 1, 0, 0.514772,-99)    );
  // itree = 202
  fBoostWeights.push_back(0.286059);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.691709,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562892,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.374188,-99) , 
1, -0.00187656, 0, 0, 0.500991,-99) , 
5, -0.973507, 1, 0, 0.531375,-99)    );
  // itree = 203
  fBoostWeights.push_back(0.327374);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.653387,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46592,-99) , 
3, 0.587331, 1, 0, 0.566391,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.368542,-99) , 
4, 0.0207866, 1, 0, 0.46691,-99)    );
  // itree = 204
  fBoostWeights.push_back(0.299404);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.690584,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547361,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.361995,-99) , 
5, -0.631092, 1, 0, 0.46316,-99) , 
6, 0.947456, 0, 0, 0.500586,-99)    );
  // itree = 205
  fBoostWeights.push_back(0.266371);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540854,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.372523,-99) , 
6, -0.906021, 0, 0, 0.501432,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.330797,-99) , 
0, 0.12035, 1, 0, 0.449545,-99)    );
  // itree = 206
  fBoostWeights.push_back(0.25306);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.668198,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532155,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.384873,-99) , 
0, 0.0858889, 1, 0, 0.464624,-99) , 
0, 0.119913, 0, 0, 0.504524,-99)    );
  // itree = 207
  fBoostWeights.push_back(0.272081);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.713753,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.57142,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426236,-99) , 
0, 0.095489, 1, 0, 0.492864,-99) , 
3, 0.658311, 0, 0, 0.529315,-99)    );
  // itree = 208
  fBoostWeights.push_back(0.338887);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.00180945, 1, 1, 0.621722,-99) , 
NN(
0, 
0, 
-1, 0.402851, 0, -1, 0.38456,-99) , 
0, 0.0812143, 0, 0, 0.508428,-99)    );
  // itree = 209
  fBoostWeights.push_back(0.256342);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.660726,-99) , 
NN(
0, 
0, 
-1, -0.0252237, 1, -1, 0.424246,-99) , 
3, 0.746214, 0, 0, 0.465398,-99)    );
  // itree = 210
  fBoostWeights.push_back(0.218852);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.564521,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.419965,-99) , 
0, 0.11838, 1, 0, 0.521842,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.381158,-99) , 
3, 0.808518, 1, 0, 0.498001,-99)    );
  // itree = 211
  fBoostWeights.push_back(0.316772);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.678211,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450353,-99) , 
2, 0.00486403, 1, 0, 0.571177,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.403237,-99) , 
5, -0.925019, 0, 0, 0.51871,-99)    );
  // itree = 212
  fBoostWeights.push_back(0.243236);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.662323,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525672,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.389269,-99) , 
3, 0.172436, 0, 0, 0.450937,-99) , 
6, -0.946495, 1, 0, 0.483168,-99)    );
  // itree = 213
  fBoostWeights.push_back(0.268172);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.0777306, 0, 1, 0.651532,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.633886,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471588,-99) , 
5, -0.882529, 1, 0, 0.517529,-99) , 
0, 0.0974509, 0, 0, 0.569762,-99)    );
  // itree = 214
  fBoostWeights.push_back(0.314096);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.616411,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.622883,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.398504,-99) , 
0, 0.068713, 1, 0, 0.467776,-99) , 
0, 0.109656, 0, 0, 0.507711,-99)    );
  // itree = 215
  fBoostWeights.push_back(0.272704);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.662273,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43964,-99) , 
1, -0.00495996, 0, 0, 0.55863,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440027,-99) , 
6, 0.858032, 1, 0, 0.518311,-99)    );
  // itree = 216
  fBoostWeights.push_back(0.338474);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.075505, 0, 1, 0.623921,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523219,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.314746,-99) , 
4, 0.00371694, 1, 0, 0.412497,-99) , 
3, 0.477112, 1, 0, 0.546834,-99)    );
  // itree = 217
  fBoostWeights.push_back(0.17853);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.664274,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486303,-99) , 
0, 0.0823981, 1, 0, 0.528854,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.378938,-99) , 
0, 0.0648377, 0, 0, 0.500035,-99)    );
  // itree = 218
  fBoostWeights.push_back(0.264567);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0949629, 1, 1, 0.607415,-99) , 
NN(
0, 
0, 
-1, 0.064848, 0, -1, 0.42947,-99) , 
0, 0.0779999, 0, 0, 0.539703,-99)    );
  // itree = 219
  fBoostWeights.push_back(0.202863);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.665352,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496506,-99) , 
6, 0.704447, 0, 0, 0.528961,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.313042,-99) , 
6, 0.957956, 1, 0, 0.476038,-99)    );
  // itree = 220
  fBoostWeights.push_back(0.168831);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.630372,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.628132,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493084,-99) , 
6, 0.938009, 0, 0, 0.526895,-99) , 
5, -0.949013, 1, 0, 0.55217,-99)    );
  // itree = 221
  fBoostWeights.push_back(0.186454);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.775978, 1, 1, 0.573076,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4639,-99) , 
5, -0.976006, 0, 0, 0.552773,-99)    );
  // itree = 222
  fBoostWeights.push_back(0.235576);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.00424704, 1, 1, 0.606548,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468165,-99) , 
5, -0.91902, 0, 0, 0.563579,-99)    );
  // itree = 223
  fBoostWeights.push_back(0.314927);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.713266,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.616798,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421676,-99) , 
5, -0.726332, 1, 0, 0.493213,-99) , 
5, 0.969508, 0, 0, 0.526329,-99)    );
  // itree = 224
  fBoostWeights.push_back(0.243734);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0990654, 1, 1, 0.631316,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535315,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.356404,-99) , 
5, -0.0202431, 0, 0, 0.482737,-99) , 
6, -0.777555, 1, 0, 0.526821,-99)    );
  // itree = 225
  fBoostWeights.push_back(0.313381);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.00980096, 0, 1, 0.649774,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451908,-99) , 
1, 0.0044437, 1, 0, 0.57255,-99)    );
  // itree = 226
  fBoostWeights.push_back(0.237746);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.686376,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47768,-99) , 
6, -0.950876, 0, 0, 0.583108,-99) , 
NN(
0, 
0, 
-1, 0.162209, 0, -1, 0.427344,-99) , 
6, -0.670064, 1, 0, 0.482132,-99)    );
  // itree = 227
  fBoostWeights.push_back(0.222754);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0168426, 1, 1, 0.580507,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502226,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.355835,-99) , 
4, 0.00251441, 1, 0, 0.426494,-99) , 
4, 0.00673619, 0, 0, 0.529187,-99)    );
  // itree = 228
  fBoostWeights.push_back(0.242863);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.601572,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448868,-99) , 
5, -0.915521, 0, 0, 0.539981,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.404479,-99) , 
6, 0.919012, 1, 0, 0.495905,-99)    );
  // itree = 229
  fBoostWeights.push_back(0.219137);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.640209,-99) , 
NN(
0, 
0, 
-1, 0.116268, 1, -1, 0.441461,-99) , 
6, 0.875977, 0, 0, 0.48792,-99)    );
  // itree = 230
  fBoostWeights.push_back(0.298397);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.010114, 1, 1, 0.636123,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5697,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422709,-99) , 
6, 0.962866, 0, 0, 0.470828,-99) , 
6, 0.0337383, 1, 0, 0.552184,-99)    );
  // itree = 231
  fBoostWeights.push_back(0.283125);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.506043, 0, 1, 0.595755,-99) , 
NN(
0, 
0, 
-1, 0.552624, 1, -1, 0.394976,-99) , 
0, 0.101232, 1, 0, 0.509014,-99)    );
  // itree = 232
  fBoostWeights.push_back(0.210064);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.592135,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540378,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42062,-99) , 
6, 0.836527, 0, 0, 0.451718,-99) , 
3, 0.538119, 0, 0, 0.483703,-99)    );
  // itree = 233
  fBoostWeights.push_back(0.149029);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.641481,-99) , 
NN(
0, 
0, 
-1, 0.782025, 1, -1, 0.46281,-99) , 
0, 0.130836, 0, 0, 0.489938,-99)    );
  // itree = 234
  fBoostWeights.push_back(0.217637);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.61178,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47388,-99) , 
4, 0.0138913, 1, 0, 0.524436,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.350589,-99) , 
5, -0.973007, 0, 0, 0.487385,-99)    );
  // itree = 235
  fBoostWeights.push_back(0.261587);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.728086,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551332,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.386867,-99) , 
3, 0.806921, 1, 0, 0.518777,-99) , 
6, -0.935514, 1, 0, 0.555401,-99)    );
  // itree = 236
  fBoostWeights.push_back(0.181083);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.00158345, 0, 1, 0.579533,-99) , 
NN(
0, 
0, 
-1, 0.121426, 1, -1, 0.444865,-99) , 
3, 0.293665, 0, 0, 0.495531,-99)    );
  // itree = 237
  fBoostWeights.push_back(0.229772);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.576721,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516155,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.328038,-99) , 
1, 0.00376542, 1, 0, 0.430942,-99) , 
3, 0.221436, 1, 0, 0.50957,-99)    );
  // itree = 238
  fBoostWeights.push_back(0.278204);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.493358, 0, 1, 0.594736,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.388937,-99) , 
0, 0.0648636, 0, 0, 0.552706,-99)    );
  // itree = 239
  fBoostWeights.push_back(0.210182);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.698671,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49709,-99) , 
6, 0.606089, 0, 0, 0.578882,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518144,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.401286,-99) , 
0, 0.0658234, 1, 0, 0.444398,-99) , 
0, 0.0916131, 0, 0, 0.499966,-99)    );
  // itree = 240
  fBoostWeights.push_back(0.287235);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.755759,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451518,-99) , 
2, 0.00472631, 1, 0, 0.566864,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439558,-99) , 
1, -0.00422991, 0, 0, 0.517378,-99)    );
  // itree = 241
  fBoostWeights.push_back(0.274887);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.96761, 1, 1, 0.620151,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.60332,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.427219,-99) , 
6, -0.906607, 1, 0, 0.490316,-99) , 
5, 0.727568, 0, 0, 0.537393,-99)    );
  // itree = 242
  fBoostWeights.push_back(0.268687);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.621536,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456021,-99) , 
2, 0.00542716, 1, 0, 0.529204,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524619,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.263935,-99) , 
5, -0.950149, 1, 0, 0.409018,-99) , 
6, -0.768063, 0, 0, 0.479685,-99)    );
  // itree = 243
  fBoostWeights.push_back(0.288981);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.59892,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.401588,-99) , 
5, 0.91852, 1, 0, 0.538853,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.387355,-99) , 
0, 0.064599, 0, 0, 0.506096,-99)    );
  // itree = 244
  fBoostWeights.push_back(0.207025);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.00550903, 1, 1, 0.580199,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436163,-99) , 
2, -0.00431874, 0, 0, 0.520377,-99)    );
  // itree = 245
  fBoostWeights.push_back(0.28365);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.627208,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547954,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.369807,-99) , 
0, 0.0998227, 0, 0, 0.449674,-99) , 
0, 0.067265, 1, 0, 0.484342,-99)    );
  // itree = 246
  fBoostWeights.push_back(0.244784);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.88053, 1, 1, 0.638893,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490035,-99) , 
2, -0.00391753, 0, 0, 0.57845,-99)    );
  // itree = 247
  fBoostWeights.push_back(0.312157);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.655286,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.410141,-99) , 
0, 0.0770874, 0, 0, 0.543282,-99) , 
NN(
0, 
0, 
-1, 0.0841022, 1, -1, 0.402531,-99) , 
6, -0.0482359, 1, 0, 0.464045,-99)    );
  // itree = 248
  fBoostWeights.push_back(0.286138);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.725693,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.617625,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431506,-99) , 
3, 0.600577, 0, 0, 0.469139,-99) , 
5, 0.967008, 0, 0, 0.508101,-99)    );
  // itree = 249
  fBoostWeights.push_back(0.392462);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.665192,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455936,-99) , 
3, 0.740537, 1, 0, 0.619877,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.371441,-99) , 
0, 0.125895, 1, 0, 0.563604,-99)    );
  // itree = 250
  fBoostWeights.push_back(0.294063);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.805233,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449807,-99) , 
1, -0.00468278, 0, 0, 0.584891,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452965,-99) , 
1, 0.00308884, 1, 0, 0.527397,-99)    );
  // itree = 251
  fBoostWeights.push_back(0.240197);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.675966,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.615185,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473852,-99) , 
6, 0.869226, 0, 0, 0.525731,-99) , 
6, -0.909516, 1, 0, 0.559235,-99)    );
  // itree = 252
  fBoostWeights.push_back(0.2659);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.63638,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494894,-99) , 
3, 0.58751, 1, 0, 0.589865,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.404843,-99) , 
0, 0.114028, 1, 0, 0.53088,-99)    );
  // itree = 253
  fBoostWeights.push_back(0.176444);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.67043,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509089,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428436,-99) , 
0, 0.0733295, 0, 0, 0.486374,-99) , 
3, 0.513602, 0, 0, 0.532469,-99)    );
  // itree = 254
  fBoostWeights.push_back(0.315011);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.706179,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475405,-99) , 
5, 0.961668, 1, 0, 0.590775,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.592635,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.384848,-99) , 
5, -0.943494, 1, 0, 0.457259,-99) , 
5, 0.497626, 0, 0, 0.512494,-99)    );
  // itree = 255
  fBoostWeights.push_back(0.250009);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.771463,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489432,-99) , 
5, -0.421873, 1, 0, 0.564323,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.384296,-99) , 
5, -0.972007, 0, 0, 0.521621,-99)    );
  // itree = 256
  fBoostWeights.push_back(0.372315);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.384639, 1, 1, 0.670611,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.639468,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461089,-99) , 
3, 0.506043, 0, 0, 0.526175,-99) , 
5, 0.773057, 1, 0, 0.608753,-99)    );
  // itree = 257
  fBoostWeights.push_back(0.283768);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.74294, 0, 1, 0.619466,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541507,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.353354,-99) , 
3, 0.328351, 1, 0, 0.469646,-99) , 
0, 0.0934329, 1, 0, 0.542241,-99)    );
  // itree = 258
  fBoostWeights.push_back(0.237614);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.385639, 0, 1, 0.604139,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517093,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.365402,-99) , 
0, 0.0949568, 1, 0, 0.454207,-99) , 
6, 0.0217437, 0, 0, 0.525589,-99)    );
  // itree = 259
  fBoostWeights.push_back(0.215875);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.677091,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487258,-99) , 
4, 0.0142934, 1, 0, 0.569476,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43599,-99) , 
5, -0.886028, 0, 0, 0.519666,-99)    );
  // itree = 260
  fBoostWeights.push_back(0.211223);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.799039, 1, 1, 0.581616,-99) , 
NN(
0, 
0, 
-1, -0.0347272, 1, -1, 0.434139,-99) , 
0, 0.0787221, 0, 0, 0.518463,-99)    );
  // itree = 261
  fBoostWeights.push_back(0.214503);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.618692,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530051,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.367806,-99) , 
2, -0.000414734, 0, 0, 0.480257,-99) , 
5, -0.904524, 1, 0, 0.51557,-99)    );
  // itree = 262
  fBoostWeights.push_back(0.174576);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.596857,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519139,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.365243,-99) , 
0, 0.094358, 1, 0, 0.477989,-99) , 
0, 0.11763, 0, 0, 0.5084,-99)    );
  // itree = 263
  fBoostWeights.push_back(0.259007);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.585756,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421581,-99) , 
6, -0.919028, 0, 0, 0.501142,-99) , 
NN(
0, 
0, 
-1, 0.84954, 0, -1, 0.398704,-99) , 
6, 0.255201, 1, 0, 0.450845,-99)    );
  // itree = 264
  fBoostWeights.push_back(0.304395);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.685647,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47458,-99) , 
4, 0.00714529, 0, 0, 0.614936,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463062,-99) , 
6, 0.919505, 1, 0, 0.575083,-99)    );
  // itree = 265
  fBoostWeights.push_back(0.304537);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.963188, 0, 1, 0.605205,-99) , 
NN(
0, 
0, 
-1, -0.928585, 1, -1, 0.390685,-99) , 
5, -0.79805, 0, 0, 0.507364,-99)    );
  // itree = 266
  fBoostWeights.push_back(0.204003);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.648901,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544096,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423034,-99) , 
2, 0.0017042, 1, 0, 0.499279,-99) , 
6, 0.962994, 0, 0, 0.525254,-99)    );
  // itree = 267
  fBoostWeights.push_back(0.277627);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.694362,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550381,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.400841,-99) , 
4, 0.0121257, 1, 0, 0.468091,-99) , 
0, 0.120799, 0, 0, 0.507979,-99)    );
  // itree = 268
  fBoostWeights.push_back(0.156887);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.647433,-99) , 
NN(
0, 
0, 
-1, 0.493005, 1, -1, 0.463452,-99) , 
3, 0.658257, 0, 0, 0.49539,-99)    );
  // itree = 269
  fBoostWeights.push_back(0.228568);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.625213,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536605,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.403049,-99) , 
0, 0.081876, 1, 0, 0.458425,-99) , 
6, -0.95401, 1, 0, 0.486546,-99)    );
  // itree = 270
  fBoostWeights.push_back(0.236127);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558116,-99) , 
NN(
0, 
0, 
-1, 0.0986291, 1, -1, 0.408524,-99) , 
6, 0.889024, 0, 0, 0.444108,-99)    );
  // itree = 271
  fBoostWeights.push_back(0.221298);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0947893, 0, 1, 0.593415,-99) , 
NN(
0, 
0, 
-1, 0.0104249, 0, -1, 0.435623,-99) , 
6, 0.225199, 1, 0, 0.511734,-99)    );
  // itree = 272
  fBoostWeights.push_back(0.256108);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.738485,-99) , 
NN(
0, 
0, 
-1, 0.794196, 1, -1, 0.439206,-99) , 
0, 0.122866, 0, 0, 0.489172,-99)    );
  // itree = 273
  fBoostWeights.push_back(0.344073);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.668667,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562056,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.390498,-99) , 
6, -0.562596, 0, 0, 0.477961,-99) , 
4, 0.02163, 0, 0, 0.55839,-99)    );
  // itree = 274
  fBoostWeights.push_back(0.23447);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.70971,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540781,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.389352,-99) , 
3, 0.794021, 1, 0, 0.509968,-99) , 
6, -0.954004, 1, 0, 0.546075,-99)    );
  // itree = 275
  fBoostWeights.push_back(0.213804);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.003004, 1, 1, 0.58813,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56054,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42557,-99) , 
5, 0.667583, 0, 0, 0.473489,-99) , 
3, 0.3911, 0, 0, 0.512082,-99)    );
  // itree = 276
  fBoostWeights.push_back(0.293436);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.709583,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.587265,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.420131,-99) , 
0, 0.0885259, 0, 0, 0.491143,-99) , 
5, 0.962009, 0, 0, 0.526141,-99)    );
  // itree = 277
  fBoostWeights.push_back(0.226372);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541485,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.411856,-99) , 
3, 0.473575, 1, 0, 0.493205,-99) , 
NN(
0, 
0, 
-1, 0.96372, 0, -1, 0.404034,-99) , 
5, -0.458635, 1, 0, 0.442045,-99)    );
  // itree = 278
  fBoostWeights.push_back(0.31938);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.00215952, 1, 1, 0.699455,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553341,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.433492,-99) , 
6, -0.229209, 1, 0, 0.487282,-99) , 
3, 0.332404, 0, 0, 0.566016,-99)    );
  // itree = 279
  fBoostWeights.push_back(0.287956);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.644127,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472506,-99) , 
3, 0.366023, 1, 0, 0.571887,-99) , 
NN(
0, 
0, 
-1, 0.0932992, 0, -1, 0.387098,-99) , 
6, -0.79202, 0, 0, 0.505887,-99)    );
  // itree = 280
  fBoostWeights.push_back(0.186336);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.503553, 0, 1, 0.541085,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.36886,-99) , 
6, 0.947009, 1, 0, 0.493133,-99)    );
  // itree = 281
  fBoostWeights.push_back(0.418597);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.941212, 0, 1, 0.721878,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55263,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.276651,-99) , 
5, -0.458636, 1, 0, 0.464043,-99) , 
6, 0.701561, 0, 0, 0.549129,-99)    );
  // itree = 282
  fBoostWeights.push_back(0.262265);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.00276781, 0, 1, 0.600081,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505514,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.36104,-99) , 
0, 0.124978, 0, 0, 0.427504,-99) , 
0, 0.105694, 1, 0, 0.542618,-99)    );
  // itree = 283
  fBoostWeights.push_back(0.269819);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.590644,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544326,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.390869,-99) , 
5, -0.977506, 1, 0, 0.4214,-99) , 
6, 0.939, 0, 0, 0.453152,-99)    );
  // itree = 284
  fBoostWeights.push_back(0.212988);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.000845428, 1, 1, 0.629713,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456168,-99) , 
4, 0.013887, 1, 0, 0.520133,-99)    );
  // itree = 285
  fBoostWeights.push_back(0.175432);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.595452,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482832,-99) , 
3, 0.164203, 0, 0, 0.53436,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.408971,-99) , 
6, -0.938513, 0, 0, 0.503569,-99)    );
  // itree = 286
  fBoostWeights.push_back(0.278592);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.659194,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460048,-99) , 
1, 0.00456412, 1, 0, 0.557784,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.402585,-99) , 
6, -0.925974, 0, 0, 0.518437,-99)    );
  // itree = 287
  fBoostWeights.push_back(0.222124);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.601165,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538195,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.399016,-99) , 
4, 0.0160756, 1, 0, 0.461566,-99) , 
6, 0.937958, 0, 0, 0.490596,-99)    );
  // itree = 288
  fBoostWeights.push_back(0.198149);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.661931,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508834,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.409177,-99) , 
6, -0.492938, 0, 0, 0.452879,-99) , 
5, 0.974506, 0, 0, 0.483007,-99)    );
  // itree = 289
  fBoostWeights.push_back(0.204296);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.627373,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487972,-99) , 
0, 0.0888254, 0, 0, 0.55492,-99) , 
NN(
0, 
0, 
-1, 0.0826046, 0, -1, 0.421019,-99) , 
3, 0.38389, 1, 0, 0.496691,-99)    );
  // itree = 290
  fBoostWeights.push_back(0.323686);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.693213,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454845,-99) , 
2, -0.00516548, 0, 0, 0.57729,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.409146,-99) , 
5, 0.96151, 1, 0, 0.535061,-99)    );
  // itree = 291
  fBoostWeights.push_back(0.409313);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.706297,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.589512,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.357094,-99) , 
5, -0.919437, 1, 0, 0.429456,-99) , 
5, 0.885029, 0, 0, 0.484378,-99)    );
  // itree = 292
  fBoostWeights.push_back(0.315401);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0126405, 1, 1, 0.627674,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562192,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.393765,-99) , 
5, 0.936017, 0, 0, 0.471197,-99) , 
6, 0.742561, 1, 0, 0.564245,-99)    );
  // itree = 293
  fBoostWeights.push_back(0.245523);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.598743,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443786,-99) , 
5, 0.937373, 1, 0, 0.543445,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.401553,-99) , 
5, -0.973007, 0, 0, 0.512621,-99)    );
  // itree = 294
  fBoostWeights.push_back(0.225866);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.175185, 0, 1, 0.573355,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.400565,-99) , 
6, 0.937507, 1, 0, 0.529501,-99)    );
  // itree = 295
  fBoostWeights.push_back(0.251341);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.569467,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451421,-99) , 
5, 0.86779, 1, 0, 0.525142,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.333965,-99) , 
5, -0.966508, 0, 0, 0.47536,-99)    );
  // itree = 296
  fBoostWeights.push_back(0.295094);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.656981,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473377,-99) , 
6, 0.915363, 1, 0, 0.557635,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529282,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.344608,-99) , 
6, -0.94658, 1, 0, 0.404423,-99) , 
5, 0.540615, 0, 0, 0.462701,-99)    );
  // itree = 297
  fBoostWeights.push_back(0.241659);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0660454, 0, 1, 0.592501,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557577,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.406581,-99) , 
5, 0.777556, 0, 0, 0.460184,-99) , 
0, 0.0854206, 1, 0, 0.513583,-99)    );
  // itree = 298
  fBoostWeights.push_back(0.324563);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.780762,-99) , 
NN(
0, 
0, 
-1, 0.12861, 0, -1, 0.433912,-99) , 
3, 0.493358, 0, 0, 0.511134,-99)    );
  // itree = 299
  fBoostWeights.push_back(0.313168);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.704702,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.585401,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.3905,-99) , 
5, 0.772574, 1, 0, 0.531504,-99) , 
5, 0.963509, 0, 0, 0.559108,-99)    );
   return;
};

// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}

inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
