// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.24/06       [399366]
Creator        : vince402
Date           : Thu Oct 21 14:13:03 2021
Host           : Linux kunpl 5.4.0-88-generic #99-Ubuntu SMP Thu Sep 23 17:29:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/vince402/Upsilon3S/BDT
Training events: 1764
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "True" [Create PDFs for classifier outputs (signal and background)]
NTrees: "300" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "15%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "4000" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "7.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
BaggedSampleFraction: "4.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "giniindex" [Separation criterion for node splitting]
PruneMethod: "costcomplexity" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "1.000000e+00" [Pruning strength]
PruningValFraction: "3.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
Shrinkage: "1.000000e+00" [Learning rate for BoostType=Grad algorithm]
UseNvars: "3" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "4.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 7
QQMassErr                     QQMassErr                     QQMassErr                     Dimu Mass error               F                                 'F'    [0.0200235452503,0.32656750083]
ctau3D                        ctau3D                        ctau3D                        3 dim ctau of the dimuon      F                                 'F'    [-0.047249533236,5.59233951569]
ctau                          ctau                          ctau                          2 dim ctau of the dimuon      F                                 'F'    [-0.0458894148469,5.1308131218]
QQVtxProb                     QQVtxProb                     QQVtxProb                     Vtx prob                      F                                 'F'    [0,0.997750341892]
QQdca                         QQdca                         QQdca                         QQdca                         F                                 'F'    [4.29153442383e-06,4.20825767517]
cosAlpha                      cosAlpha                      cosAlpha                      cos alpha for trajectory angleF                                 'F'    [-1,1]
cosAlpha3D                    cosAlpha3D                    cosAlpha3D                    cos alpha for trajectory angle 3DF                                 'F'    [-0.999993622303,0.999999701977]
NSpec 8
pt1                           pt1                           pt1                           Single muon pt1               F                                 'F'    [3.51839590073,45.770778656]
pt2                           pt2                           pt2                           Single muon pt2               F                                 'F'    [3.50104117393,46.6831512451]
eta1                          eta1                          eta1                          Single muon eta1              F                                 'F'    [-2.39532995224,2.38736891747]
eta2                          eta2                          eta2                          Single muon eta2              F                                 'F'    [-2.38802242279,2.38807201385]
cBin                          cBin                          cBin                          Centrality times 2 bin        F                                 'F'    [1,180]
mass                          mass                          mass                          Dimuon mass                   F                                 'F'    [8.08626651764,11.4089021683]
pt                            pt                            pt                            Dimuon pt                     F                                 'F'    [30.0039539337,49.9150238037]
y                             y                             y                             Dimuon y                      F                                 'F'    [-2.31608867645,2.36590957642]


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#include <algorithm>
#include <limits>

#define NN new BDTNode

#ifndef BDTNode__def
#define BDTNode__def

class BDTNode {

public:

   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 

//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 

//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] >= fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}

//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}

#endif

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 7 )
   {
      // the training input variables
      const char* inputVars[] = { "QQMassErr", "ctau3D", "ctau", "QQVtxProb", "QQdca", "cosAlpha", "cosAlpha3D" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[7];
   double fVmax[7];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[7];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
}

void ReadBDT::Initialize()
{
  double inf = std::numeric_limits<double>::infinity();
  double nan = std::numeric_limits<double>::quiet_NaN();
  // itree = 0
  fBoostWeights.push_back(0.947366510168108);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.113207, 1, 1, 0.821161,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.242694,-99) , 
4, 0.0153127, 1, 0, 0.581285,-99)    );
  // itree = 1
  fBoostWeights.push_back(1.61079);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.14513,-99) , 
4, 0.0220921, 1, 0, 0.463802,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.883415);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.184013, 0, 1, 0.9084,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485261,-99) , 
2, 0.00419422, 1, 0, 0.769712,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.867266);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.722944,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.260767,-99) , 
0, 0.126602, 0, 0, 0.343108,-99) , 
0, 0.0788132, 1, 0, 0.440396,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.70154);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.711488,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.368031,-99) , 
0, 0.0889795, 0, 0, 0.502767,-99) , 
4, 0.00530877, 1, 0, 0.60363,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.719448);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0.183928, 0, 1, 0.736486,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.873646);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470909,-99) , 
0, 0.113158, 1, 0, 0.740433,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.216416,-99) , 
3, 0.184143, 0, 0, 0.453862,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.917538);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.8736,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.730222,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.260786,-99) , 
0, 0.0735303, 1, 0, 0.473975,-99) , 
0, 0.0887305, 0, 0, 0.625524,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.704526);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.983003, 0, 1, 0.717129,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.209972,-99) , 
3, 0.865058, 1, 0, 0.61139,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.665183);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.596735,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.245753,-99) , 
0, 0.0743169, 0, 0, 0.464214,-99) , 
5, -0.848038, 1, 0, 0.565452,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.96939);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.00334359, 1, 1, 0.859108,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.233987,-99) , 
4, 0.016859, 1, 0, 0.460644,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.918032);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.979978,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459255,-99) , 
6, 0.976997, 1, 0, 0.788211,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.263237,-99) , 
5, -0.984004, 0, 0, 0.591895,-99)    );
  // itree = 12
  fBoostWeights.push_back(1.27591);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445209,-99) , 
0, 0.113547, 0, 0, 0.663588,-99) , 
0, 0.0866036, 1, 0, 0.826654,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.732759);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.786674,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.416868,-99) , 
0, 0.110367, 1, 0, 0.648853,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.225574,-99) , 
1, 0.00357415, 1, 0, 0.453594,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.672068);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424567,-99) , 
4, 0.0242232, 1, 0, 0.624762,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.890535);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.076216, 0, 1, 0.813595,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.315939,-99) , 
0, 0.129135, 1, 0, 0.688822,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.761348);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490622,-99) , 
0, 0.125116, 1, 0, 0.772501,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.32,-99) , 
1, 0.00356773, 1, 0, 0.624739,-99)    );
  // itree = 17
  fBoostWeights.push_back(1.39336);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.103395, 0, 1, 0.947032,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.183745,-99) , 
0, 0.0762377, 0, 0, 0.554618,-99)    );
  // itree = 18
  fBoostWeights.push_back(1.70716);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0.100269, 0, 1, 0.919739,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.9359);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.721378,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.288841,-99) , 
3, 0.251919, 0, 0, 0.422544,-99) , 
0, 0.0865773, 1, 0, 0.579557,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.869431);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.126005, 1, 1, 0.793434,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.623,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.174849,-99) , 
0, 0.0791401, 1, 0, 0.323619,-99) , 
0, 0.100236, 0, 0, 0.560924,-99)    );
  // itree = 21
  fBoostWeights.push_back(1.04237);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.931851,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.257111,-99) , 
1, 0.00360312, 1, 0, 0.517969,-99)    );
  // itree = 22
  fBoostWeights.push_back(1.26458);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0866023, 1, 1, 0.800421,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.121735,-99) , 
4, 0.00527618, 1, 0, 0.413461,-99) , 
3, 0.432167, 1, 0, 0.608963,-99)    );
  // itree = 23
  fBoostWeights.push_back(1.0116);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.993302, 1, 1, 0.945218,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.60516,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.181493,-99) , 
3, 0.563009, 1, 0, 0.39401,-99) , 
5, 0.941515, 0, 0, 0.624562,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.701398);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.952322,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.389445,-99) , 
5, -0.993502, 0, 0, 0.695351,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.331108,-99) , 
2, 0.00457082, 1, 0, 0.509964,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.718511);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.11037, 1, 1, 0.837004,-99) , 
NN(
0, 
0, 
-1, 0.664086, 1, -1, 0.339217,-99) , 
0, 0.0890303, 0, 0, 0.552327,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.789803);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.725178,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.330939,-99) , 
5, 0.941514, 0, 0, 0.445665,-99) , 
0, 0.0706823, 1, 0, 0.569236,-99)    );
  // itree = 27
  fBoostWeights.push_back(1.24301);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.917513, 0, 1, 0.979735,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.315486,-99) , 
4, 0.0153906, 1, 0, 0.699462,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.926513);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.73982,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.335768,-99) , 
4, 0.0105676, 0, 0, 0.599432,-99) , 
4, 0.00670172, 1, 0, 0.706021,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.90654);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.113474, 1, 1, 0.888166,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.286892,-99) , 
4, 0.0168571, 1, 0, 0.533825,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.728822);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.123734, 1, 1, 0.84072,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.388197,-99) , 
6, 0.978474, 1, 0, 0.639791,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.543477);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.950417,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465491,-99) , 
4, 0.0168839, 1, 0, 0.640842,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.701602);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.183928, 0, 1, 0.896901,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469886,-99) , 
0, 0.126481, 1, 0, 0.70435,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.948966);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.896205,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.670804,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.224278,-99) , 
0, 0.0743357, 0, 0, 0.493218,-99) , 
4, 0.018183, 0, 0, 0.674278,-99)    );
  // itree = 34
  fBoostWeights.push_back(1.45625);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.922336,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.271041,-99) , 
2, -0.00102489, 1, 0, 0.580138,-99) , 
5, 0.906523, 0, 0, 0.739978,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.633062);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.00447295, 1, 1, 0.742907,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.371097,-99) , 
5, -0.984004, 0, 0, 0.641611,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.717943);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.974133, 0, 1, 0.821418,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484938,-99) , 
6, 0.989486, 1, 0, 0.727676,-99)    );
  // itree = 37
  fBoostWeights.push_back(1.21177);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.145228, 0, 1, 0.906553,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.734363,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.227104,-99) , 
6, 0.897526, 1, 0, 0.48376,-99) , 
3, 0.529256, 1, 0, 0.749201,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.708578);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56918,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.225442,-99) , 
6, -0.951909, 0, 0, 0.400144,-99) , 
4, 0.00595365, 1, 0, 0.515242,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.937359);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.989984, 1, 1, 0.873501,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.383258,-99) , 
1, -0.00269699, 0, 0, 0.718535,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.54619);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.00453632, 1, 1, 0.93624,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44407,-99) , 
4, 0.0163026, 1, 0, 0.612059,-99)    );
  // itree = 41
  fBoostWeights.push_back(1.09445);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.129124, 1, 1, 0.88635,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.838674,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.265784,-99) , 
0, 0.0706307, 1, 0, 0.474259,-99) , 
0, 0.099773, 0, 0, 0.671517,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.910755);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.989517, 0, 1, 0.834567,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.622399,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.209797,-99) , 
4, 0.00729834, 1, 0, 0.261163,-99) , 
1, 0.00109048, 1, 0, 0.407942,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.740493);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.376841,-99) , 
5, -0.0757311, 1, 0, 0.620444,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.649851,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.252384,-99) , 
0, 0.0712442, 1, 0, 0.356407,-99) , 
0, 0.100266, 0, 0, 0.466776,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.96239);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.432574, 0, 1, 0.72644,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.145741,-99) , 
3, 0.126184, 0, 0, 0.400599,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.903473);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.542813, 1, 1, 0.864647,-99) , 
NN(
0, 
0, 
-1, -0.00341372, 1, -1, 0.306059,-99) , 
6, -0.915013, 0, 0, 0.601608,-99)    );
  // itree = 46
  fBoostWeights.push_back(1.14757);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.955829,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.822029,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.366835,-99) , 
6, 0.974975, 1, 0, 0.640233,-99) , 
3, 0.147609, 1, 0, 0.77727,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.778955);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.825659,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440904,-99) , 
6, 0.979496, 0, 0, 0.606126,-99) , 
2, -0.00100618, 1, 0, 0.70155,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.768496);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.845558,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421298,-99) , 
3, 0.191493, 0, 0, 0.69956,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.254756,-99) , 
5, 0.981005, 1, 0, 0.496677,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.809909);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.148359, 0, 1, 0.847051,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498233,-99) , 
4, 0.00736689, 0, 0, 0.759907,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.415611);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.564642, 1, 1, 0.839411,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474112,-99) , 
4, 0.0221652, 1, 0, 0.611987,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.862615);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0.996501, 1, 1, 0.774222,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.790906);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.829716,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.590475,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.194908,-99) , 
5, 0.736059, 0, 0, 0.32803,-99) , 
3, 0.545134, 0, 0, 0.446902,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.866218);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.975757,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437629,-99) , 
3, 0.148272, 0, 0, 0.679029,-99) , 
NN(
0, 
0, 
-1, -0.00129535, 0, -1, 0.201935,-99) , 
3, 0.528925, 1, 0, 0.419769,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.953827);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0.0063483, 0, 1, 0.796183,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.535104);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0753092, 0, 1, 0.848015,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440993,-99) , 
0, 0.125826, 1, 0, 0.614655,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.776544);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.617765,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.389015,-99) , 
2, -0.002249, 1, 0, 0.461296,-99) , 
0, 0.126617, 0, 0, 0.654681,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.752585);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.167842, 0, 1, 0.867293,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.408519,-99) , 
0, 0.126571, 1, 0, 0.664823,-99)    );
  // itree = 58
  fBoostWeights.push_back(1.08114);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.910551,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.652104,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.131221,-99) , 
4, 0.00925382, 1, 0, 0.365893,-99) , 
4, 0.0178896, 0, 0, 0.572813,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.949992);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.721024, 0, 1, 0.94075,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.381595,-99) , 
0, 0.0890051, 0, 0, 0.688433,-99)    );
  // itree = 60
  fBoostWeights.push_back(1.06629);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.929833,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.778667,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.268795,-99) , 
0, 0.086482, 1, 0, 0.495149,-99) , 
0, 0.129495, 0, 0, 0.663445,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.622166);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.984004, 0, 1, 0.785392,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.351745,-99) , 
1, 0.00286201, 1, 0, 0.542703,-99)    );
  // itree = 62
  fBoostWeights.push_back(1.20273);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0673645, 0, 1, 0.838207,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.841212,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.138564,-99) , 
0, 0.129505, 0, 0, 0.37587,-99) , 
0, 0.110367, 1, 0, 0.565095,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.991791);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.125997, 1, 1, 0.811859,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.208888,-99) , 
0, 0.0743229, 0, 0, 0.607956,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.859922);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.752881,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.817009,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.230811,-99) , 
3, 0.186052, 1, 0, 0.388141,-99) , 
6, 0.986473, 0, 0, 0.494207,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.744248);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.120159, 1, 1, 0.836448,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.31928,-99) , 
3, 0.249972, 0, 0, 0.527118,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.95523);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.181685, 1, 1, 0.79272,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.195728,-99) , 
0, 0.076237, 0, 0, 0.596935,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.801747);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.545216, 0, 1, 0.762811,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.253815,-99) , 
3, 0.764975, 1, 0, 0.635754,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.961064);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468361,-99) , 
2, -0.00455057, 0, 0, 0.772372,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.204824,-99) , 
6, 0.985987, 1, 0, 0.559485,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.840743);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.834876, 1, 1, 0.915102,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.389339,-99) , 
3, 0.249972, 0, 0, 0.662293,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.784915);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.935371,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407089,-99) , 
4, 0.00313238, 1, 0, 0.531758,-99) , 
3, 0.144118, 1, 0, 0.650744,-99)    );
  // itree = 71
  fBoostWeights.push_back(1.03794);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.891523, 0, 1, 0.871707,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555321,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.100351,-99) , 
0, 0.111566, 1, 0, 0.262623,-99) , 
3, 0.52885, 1, 0, 0.507564,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.554316);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0727179, 0, 1, 0.815989,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.392855,-99) , 
4, 0.0155957, 1, 0, 0.55715,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.829622);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0.00349585, 1, 1, 0.765877,-99)    );
  // itree = 74
  fBoostWeights.push_back(1.09562);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.999119,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.767378,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.322345,-99) , 
6, 0.308684, 0, 0, 0.506724,-99) , 
0, 0.100233, 0, 0, 0.701169,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.96281);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.130315, 1, 1, 0.98805,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.369395,-99) , 
1, 0.00348214, 1, 0, 0.659564,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.695582);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.991002, 0, 1, 0.909374,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.349654,-99) , 
1, 0.00349526, 1, 0, 0.521377,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.557963);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.00269919, 0, 1, 0.751355,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.398888,-99) , 
5, 0.992502, 1, 0, 0.605897,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.834592);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.891328, 0, 1, 0.768883,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.237989,-99) , 
5, -0.994501, 0, 0, 0.634789,-99)    );
  // itree = 79
  fBoostWeights.push_back(1.0761);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.302227,-99) , 
3, 0.249874, 0, 0, 0.591508,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.45053);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.721839,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529745,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.257596,-99) , 
0, 0.0712681, 0, 0, 0.405382,-99) , 
6, 0.979488, 0, 0, 0.500892,-99)    );
  // itree = 81
  fBoostWeights.push_back(1.48408);
  fForest.push_back( 
NN(
0, 
0, 
-1, -0.983004, 0, 1, 0.892843,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.721015);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.249936, 0, 1, 0.79484,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.323551,-99) , 
6, 0.977475, 1, 0, 0.564273,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.644204);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.991284,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.611812,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.383843,-99) , 
3, 0.17047, 0, 0, 0.513193,-99) , 
0, 0.129498, 0, 0, 0.641593,-99)    );
  // itree = 84
  fBoostWeights.push_back(1.40437);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.544353, 1, 1, 0.839834,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.87096,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0792827,-99) , 
5, -0.984599, 1, 0, 0.272434,-99) , 
5, 0.621594, 0, 0, 0.496336,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.646336);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.873379,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485408,-99) , 
3, 0.764956, 1, 0, 0.686592,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.277475,-99) , 
4, 0.0162954, 1, 0, 0.404673,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.594968);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.415602, 1, 1, 0.757683,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504952,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.162413,-99) , 
0, 0.0743379, 0, 0, 0.335927,-99) , 
5, 0.891527, 0, 0, 0.485731,-99)    );
  // itree = 87
  fBoostWeights.push_back(1.10723);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.990413, 0, 1, 0.955618,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.725854,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.339515,-99) , 
0, 0.100206, 1, 0, 0.504129,-99) , 
5, 0.891527, 0, 0, 0.742502,-99)    );
  // itree = 88
  fBoostWeights.push_back(1.12912);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.841478,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.264153,-99) , 
3, 0.147671, 0, 0, 0.536442,-99) , 
0, 0.131699, 0, 0, 0.640614,-99)    );
  // itree = 89
  fBoostWeights.push_back(1.08859);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.889836,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.255233,-99) , 
3, 0.564992, 0, 0, 0.392588,-99) , 
0, 0.0706971, 1, 0, 0.526881,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.860023);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.830407,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.747113,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.284493,-99) , 
0, 0.110073, 1, 0, 0.479338,-99) , 
3, 0.183291, 1, 0, 0.634004,-99)    );
  // itree = 91
  fBoostWeights.push_back(1.41798);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.182707, 1, 1, 0.897119,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.166754,-99) , 
3, 0.70984, 1, 0, 0.741026,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.993441);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.879112,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.74592,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.227837,-99) , 
6, -0.97501, 1, 0, 0.361149,-99) , 
5, 0.989503, 0, 0, 0.542469,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.561464);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.864991, 1, 1, 0.951582,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.413045,-99) , 
4, 0.0168719, 1, 0, 0.56586,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.839833);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.726572, 0, 1, 0.831115,-99) , 
NN(
0, 
0, 
-1, 0.079529, 0, -1, 0.254527,-99) , 
0, 0.100262, 0, 0, 0.40944,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.817016);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47831,-99) , 
1, 0.00439488, 1, 0, 0.741104,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.966863);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.086578, 1, 1, 0.839617,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.278109,-99) , 
1, -0.0027526, 0, 0, 0.64679,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.975404);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.913402,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431056,-99) , 
0, 0.100263, 0, 0, 0.671762,-99) , 
0, 0.0741845, 1, 0, 0.748135,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.731068);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0668779, 0, 1, 0.851936,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538865,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.38336,-99) , 
0, 0.13614, 1, 0, 0.472246,-99) , 
0, 0.113483, 1, 0, 0.699598,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.839746);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.978672, 1, 1, 0.842038,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.837788,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.336813,-99) , 
5, -0.984537, 1, 0, 0.479437,-99) , 
6, 0.662091, 0, 0, 0.635451,-99)    );
  // itree = 100
  fBoostWeights.push_back(0.870523);
  fForest.push_back( 
NN(
0, 
0, 
-1, -0.985497, 0, 1, 0.776191,-99)    );
  // itree = 101
  fBoostWeights.push_back(0.69409);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.019956, 1, 1, 0.779778,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555043,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.352615,-99) , 
0, 0.0954256, 0, 0, 0.451799,-99) , 
3, 0.524362, 1, 0, 0.686755,-99)    );
  // itree = 102
  fBoostWeights.push_back(0.590091);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.916604,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.630021,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.323807,-99) , 
4, 0.0153768, 1, 0, 0.443201,-99) , 
6, -0.975469, 1, 0, 0.518135,-99)    );
  // itree = 103
  fBoostWeights.push_back(0.771125);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.602889,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.262963,-99) , 
0, 0.109879, 1, 0, 0.405183,-99) , 
4, 0.00526329, 1, 0, 0.535018,-99)    );
  // itree = 104
  fBoostWeights.push_back(0.634885);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.00270164, 0, 1, 0.807876,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.409381,-99) , 
6, 0.978474, 1, 0, 0.632719,-99)    );
  // itree = 105
  fBoostWeights.push_back(1.23189);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.00403447, 0, 1, 0.993579,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446344,-99) , 
3, 0.648611, 1, 0, 0.818944,-99)    );
  // itree = 106
  fBoostWeights.push_back(0.926876);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.777617,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.682997,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.142687,-99) , 
5, 0.941854, 0, 0, 0.338509,-99) , 
5, -0.940015, 1, 0, 0.452064,-99)    );
  // itree = 107
  fBoostWeights.push_back(1.11832);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.711385, 0, 1, 0.908109,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.369632,-99) , 
5, 0.996001, 1, 0, 0.759936,-99)    );
  // itree = 108
  fBoostWeights.push_back(0.675241);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.753812,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.660821,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.280863,-99) , 
3, 0.545144, 1, 0, 0.369488,-99) , 
4, 0.0178849, 0, 0, 0.516867,-99)    );
  // itree = 109
  fBoostWeights.push_back(1.1619);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0.00320168, 1, 1, 0.840219,-99)    );
  // itree = 110
  fBoostWeights.push_back(0.804541);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.99102, 0, 1, 0.863627,-99) , 
NN(
0, 
0, 
-1, -0.992718, 0, -1, 0.328049,-99) , 
5, 0.941514, 0, 0, 0.572373,-99)    );
  // itree = 111
  fBoostWeights.push_back(0.753813);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.823332,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.766562,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.314242,-99) , 
4, 0.00526806, 1, 0, 0.456752,-99) , 
0, 0.129509, 0, 0, 0.570164,-99)    );
  // itree = 112
  fBoostWeights.push_back(0.591813);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.903369,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.59028,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.27803,-99) , 
6, 0.934252, 0, 0, 0.447429,-99) , 
5, -0.939515, 1, 0, 0.535941,-99)    );
  // itree = 113
  fBoostWeights.push_back(0.980893);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.92459,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.415723,-99) , 
5, -0.994001, 0, 0, 0.745105,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.200349,-99) , 
6, 0.97799, 1, 0, 0.5041,-99)    );
  // itree = 114
  fBoostWeights.push_back(0.706116);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.00349199, 1, 1, 0.879594,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.574769,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.32703,-99) , 
2, -0.0042768, 0, 0, 0.480113,-99) , 
6, 0.934, 0, 0, 0.660173,-99)    );
  // itree = 115
  fBoostWeights.push_back(0.833912);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.908986, 1, 1, 0.945531,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.35346,-99) , 
4, 0.0155115, 1, 0, 0.591947,-99)    );
  // itree = 116
  fBoostWeights.push_back(0.756155);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.621594, 0, 1, 0.75272,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.267834,-99) , 
0, 0.0712798, 0, 0, 0.606831,-99)    );
  // itree = 117
  fBoostWeights.push_back(0.778198);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.748733,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.665181,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.230002,-99) , 
3, 0.545134, 0, 0, 0.29665,-99) , 
0, 0.126288, 0, 0, 0.426501,-99)    );
  // itree = 118
  fBoostWeights.push_back(1.08632);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.890538,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.777376,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.211906,-99) , 
5, 0.941672, 0, 0, 0.428278,-99) , 
2, -0.00100824, 1, 0, 0.606996,-99)    );
  // itree = 119
  fBoostWeights.push_back(0.908774);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.959021,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.292474,-99) , 
3, 0.191499, 0, 0, 0.499239,-99)    );
  // itree = 120
  fBoostWeights.push_back(0.833678);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.99778,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.650807,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.313401,-99) , 
4, 0.00670172, 0, 0, 0.527859,-99) , 
6, 0.979488, 0, 0, 0.672896,-99)    );
  // itree = 121
  fBoostWeights.push_back(0.957094);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.986498, 0, 1, 0.927817,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430835,-99) , 
2, 0.00382264, 1, 0, 0.746461,-99)    );
  // itree = 122
  fBoostWeights.push_back(0.765095);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.100265, 0, 1, 0.846533,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.354422,-99) , 
6, 0.978489, 1, 0, 0.607553,-99)    );
  // itree = 123
  fBoostWeights.push_back(0.875479);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.883129,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.751483,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.257848,-99) , 
5, 0.982004, 0, 0, 0.433594,-99) , 
0, 0.113567, 0, 0, 0.537914,-99)    );
  // itree = 124
  fBoostWeights.push_back(1.14684);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.909016,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.330757,-99) , 
0, 0.0712634, 0, 0, 0.635643,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0923069,-99) , 
0, 0.130838, 1, 0, 0.433662,-99)    );
  // itree = 125
  fBoostWeights.push_back(0.8995);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.920589,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.726949,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.289806,-99) , 
3, 0.181685, 1, 0, 0.422809,-99) , 
0, 0.0706697, 1, 0, 0.587706,-99)    );
  // itree = 126
  fBoostWeights.push_back(0.947156);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.712453,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.239751,-99) , 
3, 0.191654, 0, 0, 0.419037,-99) , 
0, 0.0708951, 1, 0, 0.537338,-99)    );
  // itree = 127
  fBoostWeights.push_back(0.82665);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0757633, 1, 1, 0.942778,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.368233,-99) , 
4, 0.0210643, 1, 0, 0.614572,-99)    );
  // itree = 128
  fBoostWeights.push_back(1.29996);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.01438, 1, 1, 0.921347,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.234914,-99) , 
6, -0.974496, 0, 0, 0.673634,-99)    );
  // itree = 129
  fBoostWeights.push_back(0.593522);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.984004, 0, 1, 0.876462,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487303,-99) , 
3, 0.148357, 0, 0, 0.687814,-99)    );
  // itree = 130
  fBoostWeights.push_back(0.673571);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.000733881, 1, 1, 0.907915,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.419463,-99) , 
3, 0.127845, 0, 0, 0.632871,-99)    );
  // itree = 131
  fBoostWeights.push_back(0.946303);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0.110508, 0, 1, 0.794434,-99)    );
  // itree = 132
  fBoostWeights.push_back(0.509283);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.85338,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.623886,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.394268,-99) , 
3, 0.246098, 1, 0, 0.50434,-99) , 
0, 0.126284, 0, 0, 0.59174,-99)    );
  // itree = 133
  fBoostWeights.push_back(0.964881);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.943886,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.761117,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.296087,-99) , 
3, 0.647037, 1, 0, 0.63913,-99) , 
6, 0.986487, 0, 0, 0.720217,-99)    );
  // itree = 134
  fBoostWeights.push_back(0.914537);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.545646, 0, 1, 0.833196,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534448,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.157907,-99) , 
6, 0.942977, 1, 0, 0.316468,-99) , 
0, 0.100271, 0, 0, 0.635021,-99)    );
  // itree = 135
  fBoostWeights.push_back(1.1509);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.747309,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.150429,-99) , 
5, 0.621594, 0, 0, 0.470503,-99) , 
1, -0.00318163, 1, 0, 0.582363,-99)    );
  // itree = 136
  fBoostWeights.push_back(0.490035);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.41591,-99) , 
4, 0.0153768, 1, 0, 0.53403,-99)    );
  // itree = 137
  fBoostWeights.push_back(0.75573);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.854546,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.654379,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.266202,-99) , 
3, 0.430876, 1, 0, 0.413961,-99) , 
2, -0.00271723, 1, 0, 0.539016,-99)    );
  // itree = 138
  fBoostWeights.push_back(0.706967);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.974498, 0, 1, 0.769823,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.303603,-99) , 
2, 0.00352875, 1, 0, 0.536084,-99)    );
  // itree = 139
  fBoostWeights.push_back(1.19683);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.741087,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.177212,-99) , 
2, 0.00204763, 1, 0, 0.437069,-99) , 
0, 0.0865211, 1, 0, 0.598636,-99)    );
  // itree = 140
  fBoostWeights.push_back(0.842478);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.529362, 0, 1, 0.803003,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.271382,-99) , 
1, -0.0026904, 0, 0, 0.561086,-99)    );
  // itree = 141
  fBoostWeights.push_back(0.657934);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0061588, 0, 1, 0.874472,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.393478,-99) , 
3, 0.249972, 0, 0, 0.595531,-99)    );
  // itree = 142
  fBoostWeights.push_back(0.96657);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.125174, 1, 1, 0.699467,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.720162,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0494435,-99) , 
0, 0.0670943, 1, 0, 0.230727,-99) , 
0, 0.0795601, 0, 0, 0.452075,-99)    );
  // itree = 143
  fBoostWeights.push_back(0.683363);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.944462,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.590881,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426652,-99) , 
5, 0.988953, 0, 0, 0.511681,-99) , 
6, 0.632579, 1, 0, 0.683741,-99)    );
  // itree = 144
  fBoostWeights.push_back(0.750167);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.67836,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434879,-99) , 
2, 0.00410636, 1, 0, 0.534515,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.118547,-99) , 
6, -0.974493, 0, 0, 0.328908,-99)    );
  // itree = 145
  fBoostWeights.push_back(0.622841);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.938062,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539375,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.204022,-99) , 
0, 0.0889795, 0, 0, 0.359511,-99) , 
3, 0.648874, 0, 0, 0.430077,-99)    );
  // itree = 146
  fBoostWeights.push_back(0.659554);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.982004, 0, 1, 0.700236,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.245484,-99) , 
0, 0.125678, 1, 0, 0.538447,-99)    );
  // itree = 147
  fBoostWeights.push_back(1.05461);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.656639,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.116228,-99) , 
3, 0.52803, 1, 0, 0.476466,-99) , 
3, 0.648782, 0, 0, 0.645064,-99)    );
  // itree = 148
  fBoostWeights.push_back(0.740703);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0.187604, 1, -1, 0.38275,-99) , 
3, 0.545303, 0, 0, 0.584474,-99)    );
  // itree = 149
  fBoostWeights.push_back(0.58606);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.419561, 1, 1, 0.940793,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431736,-99) , 
4, 0.0210643, 1, 0, 0.608857,-99)    );
  // itree = 150
  fBoostWeights.push_back(0.435991);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.883603,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478335,-99) , 
4, 0.0201013, 1, 0, 0.623002,-99)    );
  // itree = 151
  fBoostWeights.push_back(1.17788);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.912408,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.831369,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.206459,-99) , 
0, 0.110489, 0, 0, 0.491546,-99) , 
0, 0.0865505, 1, 0, 0.626001,-99)    );
  // itree = 152
  fBoostWeights.push_back(0.827176);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.926018, 0, 1, 0.802615,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.269412,-99) , 
0, 0.125448, 1, 0, 0.526009,-99)    );
  // itree = 153
  fBoostWeights.push_back(0.747125);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.946963, 1, 1, 0.775814,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523743,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.190528,-99) , 
3, 0.765912, 0, 0, 0.340714,-99) , 
3, 0.564503, 1, 0, 0.630696,-99)    );
  // itree = 154
  fBoostWeights.push_back(0.66719);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.655688,-99) , 
NN(
0, 
0, 
-1, 0.00202763, 1, -1, 0.235306,-99) , 
0, 0.0890553, 0, 0, 0.400942,-99)    );
  // itree = 155
  fBoostWeights.push_back(1.12863);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.798315,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.229449,-99) , 
1, 0.00313271, 1, 0, 0.453187,-99) , 
0, 0.11046, 0, 0, 0.583961,-99)    );
  // itree = 156
  fBoostWeights.push_back(0.745364);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.910263,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479073,-99) , 
2, -0.000991496, 0, 0, 0.758679,-99) , 
NN(
0, 
0, 
-1, 0.92602, 0, -1, 0.295205,-99) , 
0, 0.0887578, 0, 0, 0.557437,-99)    );
  // itree = 157
  fBoostWeights.push_back(0.727323);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.370685,-99) , 
3, 0.191493, 0, 0, 0.556326,-99)    );
  // itree = 158
  fBoostWeights.push_back(0.538404);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.7141,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.409377,-99) , 
5, 0.736009, 0, 0, 0.490674,-99) , 
3, 0.545633, 0, 0, 0.571546,-99)    );
  // itree = 159
  fBoostWeights.push_back(0.729279);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.545303, 0, 1, 0.727514,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.573902,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.104742,-99) , 
0, 0.130534, 0, 0, 0.314679,-99) , 
0, 0.110254, 1, 0, 0.525998,-99)    );
  // itree = 160
  fBoostWeights.push_back(0.585878);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.981618,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548733,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.144632,-99) , 
0, 0.110438, 1, 0, 0.419671,-99) , 
0, 0.12948, 0, 0, 0.505502,-99)    );
  // itree = 161
  fBoostWeights.push_back(0.38022);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.81747,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499389,-99) , 
4, 0.0198829, 1, 0, 0.631837,-99)    );
  // itree = 162
  fBoostWeights.push_back(1.03187);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.366835,-99) , 
1, -0.00305733, 0, 0, 0.697996,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.210155,-99) , 
1, 0.00330327, 1, 0, 0.540628,-99)    );
  // itree = 163
  fBoostWeights.push_back(0.984705);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.983487, 1, 1, 0.814737,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.232557,-99) , 
0, 0.0643081, 0, 0, 0.673311,-99)    );
  // itree = 164
  fBoostWeights.push_back(1.12321);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.977891,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.84482,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.34459,-99) , 
0, 0.110489, 0, 0, 0.659878,-99) , 
0, 0.086619, 1, 0, 0.750484,-99)    );
  // itree = 165
  fBoostWeights.push_back(0.952699);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.949496, 1, 1, 0.884592,-99) , 
NN(
0, 
0, 
-1, 0.134788, 0, -1, 0.320882,-99) , 
0, 0.107728, 1, 0, 0.641329,-99)    );
  // itree = 166
  fBoostWeights.push_back(0.687984);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0889883, 0, 1, 0.778378,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.369199,-99) , 
0, 0.113113, 1, 0, 0.637784,-99)    );
  // itree = 167
  fBoostWeights.push_back(0.765458);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.731443,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.594322,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.139208,-99) , 
0, 0.100191, 1, 0, 0.300176,-99) , 
4, 0.0174467, 0, 0, 0.515217,-99)    );
  // itree = 168
  fBoostWeights.push_back(0.812448);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.729183,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.61776,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.144146,-99) , 
0, 0.0865534, 1, 0, 0.289544,-99) , 
0, 0.113554, 0, 0, 0.464416,-99)    );
  // itree = 169
  fBoostWeights.push_back(0.705722);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.764415,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580347,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.225204,-99) , 
6, -0.975494, 1, 0, 0.34695,-99) , 
2, 0.003339, 0, 0, 0.528877,-99)    );
  // itree = 170
  fBoostWeights.push_back(0.900486);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0.910522, 1, 1, 0.783539,-99)    );
  // itree = 171
  fBoostWeights.push_back(0.781554);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468188,-99) , 
1, 0.0036732, 1, 0, 0.71982,-99)    );
  // itree = 172
  fBoostWeights.push_back(0.821079);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0887089, 1, 1, 0.729024,-99) , 
NN(
0, 
0, 
-1, -0.377074, 1, -1, 0.215477,-99) , 
5, 0.906523, 0, 0, 0.408327,-99)    );
  // itree = 173
  fBoostWeights.push_back(1.13579);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.653613, 1, 1, 0.868294,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.257236,-99) , 
6, 0.982988, 1, 0, 0.706943,-99)    );
  // itree = 174
  fBoostWeights.push_back(0.793989);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.922261,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.685979,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.119444,-99) , 
6, 0.662194, 0, 0, 0.570243,-99) , 
5, -0.939515, 1, 0, 0.625584,-99)    );
  // itree = 175
  fBoostWeights.push_back(0.997509);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.984996, 0, 1, 0.819336,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.199584,-99) , 
1, 0.00349585, 1, 0, 0.386527,-99)    );
  // itree = 176
  fBoostWeights.push_back(0.775372);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.696475,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.311798,-99) , 
6, 0.524952, 0, 0, 0.605691,-99) , 
5, -0.851537, 1, 0, 0.679489,-99)    );
  // itree = 177
  fBoostWeights.push_back(1.20146);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.942077,-99) , 
NN(
0, 
0, 
-1, 0.109262, 1, -1, 0.169736,-99) , 
6, 0.907523, 1, 0, 0.289901,-99)    );
  // itree = 178
  fBoostWeights.push_back(0.852324);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.114806, 1, 1, 0.815744,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.318249,-99) , 
3, 0.544206, 1, 0, 0.652001,-99)    );
  // itree = 179
  fBoostWeights.push_back(1.24449);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.825807,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.746228,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0715099,-99) , 
0, 0.0712235, 1, 0, 0.294936,-99) , 
0, 0.0890202, 0, 0, 0.45429,-99)    );
  // itree = 180
  fBoostWeights.push_back(0.801887);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.977975, 1, 1, 0.745483,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.195451,-99) , 
0, 0.0654229, 0, 0, 0.622428,-99)    );
  // itree = 181
  fBoostWeights.push_back(0.959117);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.809214,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.674826,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.165524,-99) , 
5, -0.849342, 1, 0, 0.302156,-99) , 
5, 0.989495, 0, 0, 0.468432,-99)    );
  // itree = 182
  fBoostWeights.push_back(0.769755);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.419048,-99) , 
4, 0.0181956, 1, 0, 0.644601,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.244562,-99) , 
5, 0.994501, 1, 0, 0.422453,-99)    );
  // itree = 183
  fBoostWeights.push_back(1.30688);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.987939,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.392244,-99) , 
0, 0.0741892, 1, 0, 0.65996,-99) , 
0, 0.0997817, 0, 0, 0.795275,-99)    );
  // itree = 184
  fBoostWeights.push_back(1.06372);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.963851,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.294724,-99) , 
0, 0.0743388, 0, 0, 0.792499,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.243728,-99) , 
3, 0.148357, 0, 0, 0.492982,-99)    );
  // itree = 185
  fBoostWeights.push_back(0.987993);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0.0239284, 1, 1, 0.80399,-99)    );
  // itree = 186
  fBoostWeights.push_back(0.942203);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.00104453, 0, 1, 0.788389,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.617713,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.111316,-99) , 
0, 0.113547, 0, 0, 0.285023,-99) , 
0, 0.0865505, 1, 0, 0.439795,-99)    );
  // itree = 187
  fBoostWeights.push_back(0.984908);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.989622, 1, 1, 0.823326,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.238553,-99) , 
6, -0.974493, 0, 0, 0.63402,-99)    );
  // itree = 188
  fBoostWeights.push_back(0.579908);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.736065, 0, 1, 0.740639,-99) , 
NN(
0, 
0, 
-1, 0.00167475, 1, -1, 0.336103,-99) , 
0, 0.0933987, 1, 0, 0.505461,-99)    );
  // itree = 189
  fBoostWeights.push_back(1.08087);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0.246881, 1, 1, 0.824061,-99)    );
  // itree = 190
  fBoostWeights.push_back(0.538626);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.924483,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532423,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.236987,-99) , 
0, 0.0866274, 0, 0, 0.402559,-99) , 
5, -0.849038, 1, 0, 0.491652,-99)    );
  // itree = 191
  fBoostWeights.push_back(0.82859);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.741186,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.584586,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0998128,-99) , 
4, 0.00716979, 1, 0, 0.282118,-99) , 
3, 0.182783, 1, 0, 0.463044,-99)    );
  // itree = 192
  fBoostWeights.push_back(1.12988);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.358858,-99) , 
0, 0.100206, 1, 0, 0.694714,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.162483,-99) , 
3, 0.0975057, 0, 0, 0.38668,-99)    );
  // itree = 193
  fBoostWeights.push_back(0.391024);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.104695, 1, 1, 0.806274,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483341,-99) , 
3, 0.112498, 0, 0, 0.616556,-99)    );
  // itree = 194
  fBoostWeights.push_back(1.54154);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.944612,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.807654,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0790729,-99) , 
2, -0.00101423, 1, 0, 0.347766,-99) , 
5, 0.736066, 0, 0, 0.54192,-99)    );
  // itree = 195
  fBoostWeights.push_back(0.982615);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.974561, 1, 1, 0.9707,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.346507,-99) , 
6, -0.958498, 0, 0, 0.640264,-99)    );
  // itree = 196
  fBoostWeights.push_back(1.18332);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0.113481, 1, 1, 0.844284,-99)    );
  // itree = 197
  fBoostWeights.push_back(0.892385);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.818429,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495867,-99) , 
0, 0.0935085, 0, 0, 0.701899,-99) , 
4, 0.00534294, 1, 0, 0.779359,-99)    );
  // itree = 198
  fBoostWeights.push_back(0.55492);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0.0795482, 0, 1, 0.68842,-99)    );
  // itree = 199
  fBoostWeights.push_back(0.704626);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.107814, 0, 1, 0.935575,-99) , 
NN(
0, 
0, 
-1, -0.854002, 0, -1, 0.408173,-99) , 
0, 0.0890051, 0, 0, 0.623782,-99)    );
  // itree = 200
  fBoostWeights.push_back(1.09642);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.982004, 0, 1, 0.771668,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.108489,-99) , 
0, 0.125827, 1, 0, 0.464049,-99)    );
  // itree = 201
  fBoostWeights.push_back(0.918937);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.33556,-99) , 
1, -0.0043311, 0, 0, 0.679054,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502184,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0815707,-99) , 
5, 0.941646, 0, 0, 0.234438,-99) , 
5, -0.257685, 1, 0, 0.36529,-99)    );
  // itree = 202
  fBoostWeights.push_back(0.973448);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.646869,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.313189,-99) , 
5, -0.984004, 0, 0, 0.53842,-99) , 
0, 0.0742181, 1, 0, 0.729544,-99)    );
  // itree = 203
  fBoostWeights.push_back(0.847144);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0999608, 1, 1, 0.711391,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.183556,-99) , 
1, 0.00392861, 1, 0, 0.415228,-99)    );
  // itree = 204
  fBoostWeights.push_back(0.800546);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.978043,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423179,-99) , 
6, 0.990876, 1, 0, 0.720793,-99) , 
NN(
0, 
0, 
-1, -0.989841, 1, -1, 0.280476,-99) , 
6, -0.914986, 0, 0, 0.516254,-99)    );
  // itree = 205
  fBoostWeights.push_back(0.689555);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.714077,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.737372,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.264129,-99) , 
0, 0.110455, 0, 0, 0.458595,-99) , 
0, 0.086575, 1, 0, 0.55405,-99)    );
  // itree = 206
  fBoostWeights.push_back(1.20007);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.110278, 1, 1, 0.917464,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554738,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.119668,-99) , 
2, 0.000703029, 1, 0, 0.254238,-99) , 
3, 0.43092, 1, 0, 0.580368,-99)    );
  // itree = 207
  fBoostWeights.push_back(0.965027);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.713913,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.406483,-99) , 
5, -0.994282, 0, 0, 0.572982,-99) , 
5, 0.906523, 0, 0, 0.748212,-99)    );
  // itree = 208
  fBoostWeights.push_back(0.686808);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.000899507, 1, 1, 0.849424,-99) , 
NN(
0, 
0, 
-1, 0.00737426, 0, -1, 0.383842,-99) , 
0, 0.100257, 0, 0, 0.605747,-99)    );
  // itree = 209
  fBoostWeights.push_back(0.703737);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.63746,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.30461,-99) , 
5, -0.851037, 1, 0, 0.445108,-99) , 
0, 0.0741963, 1, 0, 0.548257,-99)    );
  // itree = 210
  fBoostWeights.push_back(0.949236);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.00420784, 1, 1, 0.848054,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52273,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0677924,-99) , 
0, 0.114216, 1, 0, 0.309843,-99) , 
2, -7.68241e-05, 0, 0, 0.634972,-99)    );
  // itree = 211
  fBoostWeights.push_back(1.3599);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.941015, 1, 1, 0.954226,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.717098,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.132253,-99) , 
5, 0.989688, 0, 0, 0.416082,-99) , 
6, 0.93302, 1, 0, 0.685892,-99)    );
  // itree = 212
  fBoostWeights.push_back(0.685355);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.107762, 1, 1, 0.705837,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.236368,-99) , 
0, 0.0795386, 0, 0, 0.534534,-99)    );
  // itree = 213
  fBoostWeights.push_back(0.875638);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.694454,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.203967,-99) , 
4, 0.0147683, 1, 0, 0.293661,-99)    );
  // itree = 214
  fBoostWeights.push_back(0.763937);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.813104,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.326809,-99) , 
4, 0.00899943, 0, 0, 0.657226,-99) , 
NN(
0, 
0, 
-1, -0.872981, 0, -1, 0.27043,-99) , 
0, 0.0890051, 0, 0, 0.461035,-99)    );
  // itree = 215
  fBoostWeights.push_back(1.02199);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.127852, 0, 1, 0.850299,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.254855,-99) , 
5, -0.994501, 0, 0, 0.630764,-99)    );
  // itree = 216
  fBoostWeights.push_back(0.838355);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.00166228, 1, 1, 0.895611,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.291848,-99) , 
1, 0.00382333, 1, 0, 0.484947,-99)    );
  // itree = 217
  fBoostWeights.push_back(0.991896);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.106089, 1, 1, 0.864935,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.629771,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.169332,-99) , 
3, 0.246687, 1, 0, 0.354485,-99) , 
6, 0.934016, 0, 0, 0.598431,-99)    );
  // itree = 218
  fBoostWeights.push_back(0.881195);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.285309,-99) , 
4, 0.022036, 1, 0, 0.445971,-99)    );
  // itree = 219
  fBoostWeights.push_back(0.638261);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.810159,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.614082,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.237571,-99) , 
3, 0.183763, 1, 0, 0.434044,-99) , 
5, 0.990002, 0, 0, 0.519254,-99)    );
  // itree = 220
  fBoostWeights.push_back(0.686636);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.105216, 1, 1, 0.741163,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.280811,-99) , 
3, 0.130903, 0, 0, 0.45049,-99)    );
  // itree = 221
  fBoostWeights.push_back(0.906966);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0712377, 1, 1, 0.844626,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511773,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.152764,-99) , 
3, 0.542922, 1, 0, 0.318187,-99) , 
0, 0.107166, 1, 0, 0.638429,-99)    );
  // itree = 222
  fBoostWeights.push_back(0.681086);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.785127,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.391625,-99) , 
4, 0.0162687, 1, 0, 0.591978,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.213845,-99) , 
3, 0.765831, 1, 0, 0.474194,-99)    );
  // itree = 223
  fBoostWeights.push_back(0.943863);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0931408, 1, 1, 0.870507,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.70091,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.153584,-99) , 
5, 0.185887, 1, 0, 0.488635,-99) , 
5, 0.941514, 0, 0, 0.611874,-99)    );
  // itree = 224
  fBoostWeights.push_back(1.11443);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.943583,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.39806,-99) , 
0, 0.134787, 0, 0, 0.642543,-99) , 
0, 0.0865773, 1, 0, 0.753234,-99)    );
  // itree = 225
  fBoostWeights.push_back(0.844008);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0701688, 0, 1, 0.862253,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.353827,-99) , 
0, 0.12599, 1, 0, 0.644109,-99)    );
  // itree = 226
  fBoostWeights.push_back(0.903771);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.718686,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.22539,-99) , 
4, 0.0178302, 0, 0, 0.506084,-99) , 
3, 0.565084, 0, 0, 0.585862,-99)    );
  // itree = 227
  fBoostWeights.push_back(0.877695);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.828337,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.191942,-99) , 
6, -0.941979, 0, 0, 0.592224,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.286327,-99) , 
0, 0.1101, 1, 0, 0.469889,-99)    );
  // itree = 228
  fBoostWeights.push_back(0.703665);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.864508,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470846,-99) , 
6, 0.988485, 1, 0, 0.73643,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.334085,-99) , 
0, 0.0708771, 0, 0, 0.631606,-99)    );
  // itree = 229
  fBoostWeights.push_back(0.791806);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.715031,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.372451,-99) , 
4, 0.00425444, 0, 0, 0.636685,-99) , 
0, 0.129519, 0, 0, 0.709386,-99)    );
  // itree = 230
  fBoostWeights.push_back(0.736556);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.678234,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.350394,-99) , 
4, 0.0154471, 1, 0, 0.437015,-99) , 
3, 0.565035, 0, 0, 0.575009,-99)    );
  // itree = 231
  fBoostWeights.push_back(0.78031);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.697952,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.41798,-99) , 
5, -0.847039, 0, 0, 0.61841,-99) , 
3, 0.711468, 0, 0, 0.718647,-99)    );
  // itree = 232
  fBoostWeights.push_back(0.770733);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.319466,-99) , 
4, 0.0155957, 1, 0, 0.468417,-99)    );
  // itree = 233
  fBoostWeights.push_back(0.752305);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.5274, 1, 1, 0.815008,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.710697,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.307016,-99) , 
0, 0.113542, 0, 0, 0.405483,-99) , 
6, 0.934, 0, 0, 0.573148,-99)    );
  // itree = 234
  fBoostWeights.push_back(1.13224);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.737313,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.411197,-99) , 
1, -0.00357926, 1, 0, 0.612295,-99) , 
2, -0.00189844, 0, 0, 0.799182,-99)    );
  // itree = 235
  fBoostWeights.push_back(0.713376);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0.00430223, 1, 1, 0.734799,-99)    );
  // itree = 236
  fBoostWeights.push_back(0.770109);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.8986,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481102,-99) , 
4, 0.0073599, 0, 0, 0.720837,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.234773,-99) , 
6, 0.983505, 1, 0, 0.491359,-99)    );
  // itree = 237
  fBoostWeights.push_back(0.683205);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.822132,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.714685,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.291535,-99) , 
0, 0.131682, 0, 0, 0.360257,-99) , 
0, 0.0707388, 1, 0, 0.429298,-99)    );
  // itree = 238
  fBoostWeights.push_back(0.65657);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.854627,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.371192,-99) , 
3, 0.249874, 0, 0, 0.656536,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.368616,-99) , 
0, 0.0762103, 0, 0, 0.560919,-99)    );
  // itree = 239
  fBoostWeights.push_back(0.603823);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.110473, 0, 1, 0.925035,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470673,-99) , 
1, 0.00347642, 1, 0, 0.670323,-99)    );
  // itree = 240
  fBoostWeights.push_back(0.754768);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0641196, 0, 1, 0.807912,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.379927,-99) , 
0, 0.125505, 1, 0, 0.667214,-99)    );
  // itree = 241
  fBoostWeights.push_back(0.450815);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.988751,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448601,-99) , 
4, 0.0168648, 1, 0, 0.577371,-99)    );
  // itree = 242
  fBoostWeights.push_back(0.802751);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.567734, 1, 1, 0.883518,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.384141,-99) , 
1, 0.00414651, 1, 0, 0.651059,-99)    );
  // itree = 243
  fBoostWeights.push_back(0.379468);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.926018, 0, 1, 0.601672,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.235291,-99) , 
3, 0.765831, 1, 0, 0.532843,-99)    );
  // itree = 244
  fBoostWeights.push_back(0.755661);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.831198,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.61471,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.258429,-99) , 
5, -0.848038, 1, 0, 0.377927,-99) , 
6, 0.983973, 0, 0, 0.54041,-99)    );
  // itree = 245
  fBoostWeights.push_back(1.03854);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.841911,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.387919,-99) , 
3, 0.52294, 1, 0, 0.653539,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.110603,-99) , 
6, -0.985495, 0, 0, 0.392915,-99)    );
  // itree = 246
  fBoostWeights.push_back(1.07338);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.850685,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487539,-99) , 
3, 0.347193, 1, 0, 0.711656,-99) , 
4, 0.00734258, 1, 0, 0.816429,-99)    );
  // itree = 247
  fBoostWeights.push_back(0.710117);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.63729,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.318725,-99) , 
4, 0.0189414, 1, 0, 0.394959,-99) , 
6, -0.990465, 1, 0, 0.51099,-99)    );
  // itree = 248
  fBoostWeights.push_back(0.777821);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.961715,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426133,-99) , 
3, 0.711237, 1, 0, 0.765896,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.395669,-99) , 
3, 0.131341, 0, 0, 0.649867,-99)    );
  // itree = 249
  fBoostWeights.push_back(0.446578);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480792,-99) , 
4, 0.0085324, 0, 0, 0.760275,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430594,-99) , 
3, 0.191493, 0, 0, 0.564751,-99)    );
  // itree = 250
  fBoostWeights.push_back(0.688425);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.527429, 1, 1, 0.78165,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.687805,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.368443,-99) , 
0, 0.114799, 0, 0, 0.539265,-99) , 
0, 0.0996273, 1, 0, 0.672876,-99)    );
  // itree = 251
  fBoostWeights.push_back(0.625286);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.994002, 1, 1, 0.71497,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.297101,-99) , 
6, -0.9585, 0, 0, 0.527813,-99)    );
  // itree = 252
  fBoostWeights.push_back(0.929577);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.526914, 1, 1, 0.860947,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.360214,-99) , 
0, 0.0712544, 0, 0, 0.701456,-99)    );
  // itree = 253
  fBoostWeights.push_back(1.15039);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.879494,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.794567,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.26106,-99) , 
5, 0.987003, 1, 0, 0.559953,-99) , 
4, 0.017101, 0, 0, 0.758282,-99)    );
  // itree = 254
  fBoostWeights.push_back(1.17369);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.900121,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.73315,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.153174,-99) , 
3, 0.432605, 0, 0, 0.322975,-99) , 
5, 0.989503, 0, 0, 0.515776,-99)    );
  // itree = 255
  fBoostWeights.push_back(1.45098);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.986855,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.890668,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.289766,-99) , 
2, -0.00273345, 1, 0, 0.635661,-99) , 
2, 0.00105924, 0, 0, 0.786374,-99)    );
  // itree = 256
  fBoostWeights.push_back(0.773206);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.00305337, 0, 1, 0.958007,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425484,-99) , 
5, 0.989003, 1, 0, 0.670716,-99)    );
  // itree = 257
  fBoostWeights.push_back(0.737464);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.00648693, 0, 1, 0.830259,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.364046,-99) , 
3, 0.100498, 0, 0, 0.617173,-99)    );
  // itree = 258
  fBoostWeights.push_back(1.19972);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.962959, 1, 1, 0.979994,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.72467,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.331676,-99) , 
0, 0.111822, 1, 0, 0.511474,-99) , 
3, 0.544309, 1, 0, 0.762599,-99)    );
  // itree = 259
  fBoostWeights.push_back(0.587097);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0.0168606, 1, 1, 0.698193,-99)    );
  // itree = 260
  fBoostWeights.push_back(0.713842);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.728269,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.332096,-99) , 
5, 0.989999, 0, 0, 0.467234,-99) , 
0, 0.131689, 0, 0, 0.54665,-99)    );
  // itree = 261
  fBoostWeights.push_back(0.831441);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.953895,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431086,-99) , 
0, 0.0890158, 0, 0, 0.697603,-99) , 
NN(
0, 
0, 
-1, 0.102124, 0, -1, 0.230962,-99) , 
3, 0.710829, 1, 0, 0.556099,-99)    );
  // itree = 262
  fBoostWeights.push_back(0.672769);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.246098, 1, 1, 0.941294,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.394107,-99) , 
2, 0.00449597, 1, 0, 0.585718,-99)    );
  // itree = 263
  fBoostWeights.push_back(0.629665);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.912143,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.590335,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.257494,-99) , 
3, 0.544375, 1, 0, 0.487753,-99) , 
3, 0.765974, 0, 0, 0.601398,-99)    );
  // itree = 264
  fBoostWeights.push_back(1.06544);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.915779,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.696116,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.217748,-99) , 
0, 0.100246, 0, 0, 0.388765,-99) , 
5, 0.990003, 0, 0, 0.611293,-99)    );
  // itree = 265
  fBoostWeights.push_back(0.900236);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.982005, 0, 1, 0.93307,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.316844,-99) , 
0, 0.107737, 1, 0, 0.564213,-99)    );
  // itree = 266
  fBoostWeights.push_back(0.358796);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.984004, 0, 1, 0.725948,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478534,-99) , 
2, 0.00457082, 1, 0, 0.604299,-99)    );
  // itree = 267
  fBoostWeights.push_back(0.949935);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.657248,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0335755,-99) , 
2, -0.000978239, 0, 0, 0.46599,-99) , 
5, -0.984504, 1, 0, 0.559073,-99)    );
  // itree = 268
  fBoostWeights.push_back(0.490293);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441981,-99) , 
4, 0.0153127, 1, 0, 0.581191,-99)    );
  // itree = 269
  fBoostWeights.push_back(1.40626);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0.110357, 1, 1, 0.881732,-99)    );
  // itree = 270
  fBoostWeights.push_back(1.00109);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.95033,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.723969,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.214556,-99) , 
0, 0.113529, 0, 0, 0.438515,-99) , 
5, 0.926018, 0, 0, 0.567869,-99)    );
  // itree = 271
  fBoostWeights.push_back(1.22219);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.811849,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.2295,-99) , 
3, 0.181732, 1, 0, 0.555875,-99) , 
4, 0.00848229, 1, 0, 0.680231,-99)    );
  // itree = 272
  fBoostWeights.push_back(0.978032);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -9.98694e-05, 1, 1, 0.800099,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.196334,-99) , 
5, -0.984004, 0, 0, 0.522798,-99)    );
  // itree = 273
  fBoostWeights.push_back(1.34031);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.982951,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.665415,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0555367,-99) , 
5, 0.973397, 0, 0, 0.296314,-99) , 
2, 0.000712068, 1, 0, 0.468384,-99)    );
  // itree = 274
  fBoostWeights.push_back(0.961621);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0.115195, 0, 1, 0.797984,-99)    );
  // itree = 275
  fBoostWeights.push_back(0.623314);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.909997, 1, 1, 0.70196,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.282294,-99) , 
0, 0.134662, 1, 0, 0.514789,-99)    );
  // itree = 276
  fBoostWeights.push_back(0.765596);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.862432,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580309,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.239834,-99) , 
6, 0.90398, 1, 0, 0.379224,-99) , 
0, 0.126617, 0, 0, 0.551044,-99)    );
  // itree = 277
  fBoostWeights.push_back(1.12726);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.986498, 0, 1, 0.881548,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.20809,-99) , 
1, 0.00349408, 1, 0, 0.520277,-99)    );
  // itree = 278
  fBoostWeights.push_back(1.0966);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.751375,-99) , 
NN(
0, 
0, 
-1, 0.110455, 0, -1, 0.163436,-99) , 
3, 0.529353, 0, 0, 0.227419,-99)    );
  // itree = 279
  fBoostWeights.push_back(1.45499);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.843677,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.243303,-99) , 
6, 0.971507, 1, 0, 0.563828,-99) , 
0, 0.0866036, 1, 0, 0.753633,-99)    );
  // itree = 280
  fBoostWeights.push_back(1.21688);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.936408,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.867835,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.246314,-99) , 
5, -0.851037, 1, 0, 0.441529,-99) , 
6, 0.983987, 0, 0, 0.64688,-99)    );
  // itree = 281
  fBoostWeights.push_back(0.959151);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0.071265, 0, 1, 0.797415,-99)    );
  // itree = 282
  fBoostWeights.push_back(1.33323);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.651812,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.182237,-99) , 
1, -0.00308257, 1, 0, 0.312153,-99) , 
5, 0.941514, 0, 0, 0.609311,-99)    );
  // itree = 283
  fBoostWeights.push_back(0.886302);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.667647,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.190708,-99) , 
3, 0.765778, 1, 0, 0.468582,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.127644,-99) , 
3, 0.114394, 0, 0, 0.343729,-99)    );
  // itree = 284
  fBoostWeights.push_back(0.526825);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.740807,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502356,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.104701,-99) , 
4, 0.00737426, 0, 0, 0.35979,-99) , 
6, 0.978489, 0, 0, 0.502372,-99)    );
  // itree = 285
  fBoostWeights.push_back(0.347617);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.834696,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441639,-99) , 
4, 0.0169159, 1, 0, 0.531673,-99)    );
  // itree = 286
  fBoostWeights.push_back(0.843891);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.94541,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.748598,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.33448,-99) , 
4, 0.0096466, 1, 0, 0.473952,-99) , 
0, 0.110458, 0, 0, 0.616211,-99)    );
  // itree = 287
  fBoostWeights.push_back(0.594494);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481684,-99) , 
4, 0.0147295, 1, 0, 0.677632,-99)    );
  // itree = 288
  fBoostWeights.push_back(0.967425);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.322957,-99) , 
0, 0.0712461, 1, 0, 0.46216,-99) , 
0, 0.110485, 0, 0, 0.579291,-99)    );
  // itree = 289
  fBoostWeights.push_back(1.10646);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.987985, 1, 1, 0.944478,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.26615,-99) , 
1, -0.00304262, 0, 0, 0.573539,-99)    );
  // itree = 290
  fBoostWeights.push_back(0.629792);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.983004, 0, 1, 0.872186,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422542,-99) , 
2, 0.00352875, 1, 0, 0.626107,-99)    );
  // itree = 291
  fBoostWeights.push_back(0.912097);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0.109887, 1, 1, 0.786339,-99)    );
  // itree = 292
  fBoostWeights.push_back(0.92338);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.544353, 1, 1, 0.84393,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.342243,-99) , 
5, -0.983004, 0, 0, 0.696002,-99)    );
  // itree = 293
  fBoostWeights.push_back(1.08319);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0.110518, 0, 1, 0.824539,-99)    );
  // itree = 294
  fBoostWeights.push_back(0.64023);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.993502, 0, 1, 0.751603,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.315136,-99) , 
2, 0.00466273, 1, 0, 0.505315,-99)    );
  // itree = 295
  fBoostWeights.push_back(0.770608);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481517,-99) , 
0, 0.107811, 0, 0, 0.677216,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.192867,-99) , 
3, 0.528891, 1, 0, 0.449803,-99)    );
  // itree = 296
  fBoostWeights.push_back(0.722983);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538732,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.153788,-99) , 
6, -0.943308, 0, 0, 0.379046,-99) , 
0, 0.0934163, 1, 0, 0.511493,-99)    );
  // itree = 297
  fBoostWeights.push_back(0.731517);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.966488,-99) , 
NN(
0, 
0, 
-1, -0.0017955, 0, -1, 0.304243,-99) , 
6, -0.975898, 1, 0, 0.412022,-99)    );
  // itree = 298
  fBoostWeights.push_back(0.887175);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.929503, 0, 1, 0.927925,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.381139,-99) , 
0, 0.126006, 1, 0, 0.666744,-99)    );
  // itree = 299
  fBoostWeights.push_back(0.697854);
  fForest.push_back( 
NN(
0, 
0, 
-1, 0.988503, 1, 1, 0.730455,-99)    );
   return;
};

// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}

inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
